### ISSUE TITLE
Add bookmarks to workstation browser

### ISSUE THREAD

**Issue by joshuathayer** [freedomofpress/securedrop-workstation#1]
It would be nice to have a bookmark for the SD Journalist Interface available in the sd-journalist tor browser (and for development, a bookmark for the submission interface).

One approach is to modify the bookmark DB directly. Bookmarks are stored in a sqlite DB at `~/.tb/tor-browser/Browser/TorBrowser/Data/Browser/places.sql`. There, the `moz_places` stores URLs (and data about visits, etc), and `moz_bookmarks` stores bookmarks, referring to URLs in `moz_places`. Bookmarking a URL means adding a row to both tables (at least). So, this approuach requires installing the `sqlite3` command and modifying that database.

**Comment by eloquence** [comment]
While a bookmark would be helpful, I would actually prefer to have the action in the Qubes menu directly take the user to the journalist interface, and be named accordingly. We should also remove actions from the menu that are not relevant.

**Comment by redshiftzero** [comment]
we're abandoning Tor Browser in favor of using the client, closing
