### ISSUE TITLE
define how VM-level applications read from QubesDB

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-workstation#1013]
## Affected components
- SecureDrop Client
- `securedrop-proxy`
- `sd-whonix`

## People and roles
Thus far:
- @cfm
- @legoktm

## Background

Since #1001, all [non-secret](https://github.com/freedomofpress/securedrop-workstation/issues/936#issue-2084949996) values used to configure SecureDrop Workstation and its VMs are set to keys in the `vm-config` hierarchy of QubesDB.  That is, a VM that needs the configuration value `QUBES_GPG_DOMAIN` has it set via `qvm-features`—

https://github.com/freedomofpress/securedrop-workstation/blob/962f4df81ec34b433eaa2a721b6bbf3b2d185cf2/dom0/sd-app.sls#L37-L41

—and can read it:

```sh-session
[user@dom0 securedrop-workstation]$ qvm-run --pass-io sd-app qubesdb-read /vm-config/QUBES_GPG_DOMAIN
sd-gpg
```

## Problem Statement

What we do not have yet is full consensus on the approaches discussed in #936 and prototyped in freedomofpress/securedrop-client#1883 for how VM-level applications should *read* these values from QubesDB.

## Solution impact

As a SecureDrop maintainer, I want to be able to configure each VM once, via QubesDB, and have all SecureDrop Workstation‒relevant applications in that VM inherit that configuration.

## Requirements and constraints

1. It MUST be trivial to extend our (first-party) Python and Rust programs for configuration from QubesDB.

2. It MUST still be possible to run our Python and Rust programs in a non-Qubes environment (i.e., where QubesDB is not available).

3. It MUST be easy to run a third-party program in a wrapper that configures it from QubesDB.

4. Requirements (1) and (3) MAY be satisfied by the same means.

## Exploration

For a program `$X`, we've prototyped the following approaches:

| Approach | Prototype/s | Comments
| --- | --- | --- |
| **(a) direct:** `$X` reads directly from QubesDB | [Python](https://github.com/freedomofpress/securedrop-client/pull/1883), [Rust](https://github.com/freedomofpress/securedrop-client/pull/1895) | Falls back to environment variables in the absence of QubesDB bindings.  QubesDB values are only writable from dom0. |
| **(b) environment:** `with-qubesdb $X` wraps `$X` with injected environment variables | https://github.com/freedomofpress/securedrop-client/pull/1883#issuecomment-1984908850 | Environment variables could be modified by the process itself, but probably not in a way that's interesting on our threat model. |
| **(c) file:** `with-qubesdb $X` wraps `$X` with a configuration file rendered from a template | https://github.com/freedomofpress/securedrop-client/pull/1883#issuecomment-1989639664 | Configuration files could be modified by the same or other processes, but probably not in a way that's interesting on our threat model. |

While there are multiple combinations of these approaches for first- versus third-party programs, this is probably the subset of proposals worth considering:

| | (1) | (2) | (3) | (4) |
| --- | --- | --- | --- | --- |
| First-party programs use | (a) direct | (a) direct | (b) environment[1] | (c) file[2] |
| Third-party programs use | (b) environment[1] | (c) file[2] | (b) environment | (c) file |
| Requires configuration files | ✗ | ✓ | ✗ | ✓ |
| Requires QubesDB bindings | ✓ | ✓ | ✗ | ✗ |
| All programs use the same approach | ✗ | ✗ | ✓ | ✓ |

**Notes:**
1. Edge case: a third-party program requires writing environment variables to a configuration file.
2. Edge case: a third-party program requires reading the configuration file into environment variables.

## Initial proposal

I favor proposal (1) or (2), in that order:
* If our programs are already coupled to Qubes OS via `qrexec`, I see no reason why they shouldn't also read natively from QubesDB.
* My [twelve-factor bias](https://github.com/freedomofpress/securedrop-client/pull/1883#issuecomment-1989626683) favors environment variables over configuration files whenever possible, but [this is not universal](https://github.com/freedomofpress/securedrop-client/pull/1883#issuecomment-1988704433).  :-)

If we *don't* want to read natively from QubesDB, then I'm agnostic between proposals (3) and (4).

**Comment by legoktm** [comment]
Thanks for summarizing, my preference is (1) or (2) as well. I don't have a big preference between the two, I think we should just implement whichever is wanted by the third-party programs we use, e.g. tor will want configuration in files.

**Comment by cfm** [comment]
Decided in today's team meeting:  We'll go with proposal (2) as follows:
1. First-party programs will read directly from QubesDB:
    1. `securedrop-proxy` will gain this functionality from freedomofpress/securedrop-client#1895  as soon as the Rust implementation in freedomofpress/securedrop-client#1718 is merged into `main`.
    2. `securedrop-client` will gain this functionality from freedomofpress/securedrop-client#1883 at our leisure.

2. For third-party programs, we will split out the `with-qubesdb` script prototyped in <https://github.com/freedomofpress/securedrop-client/pull/1883#issuecomment-1989639664> and review it separately for `sd-whonix`'s Tor authentication.  It will probably evolve into a boot-time systemd service rather than a runtime wrapper.
