### ISSUE TITLE
Create end user documentation

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#103]
As part of the version of the workstation to be audited, we should create basic end user documentation describing how the SecureDrop Workstation is intended to be used by journalists. This should cover:

- any initial configuration required by the user
- instructions for logging in, downloading submissions, viewing submissions, deleting submissions
- instructions for replying to sources
- instructions for managing stored submissions
- instructions for exporting documents
- Qubes-specific instructions (e.g., keeping your system up-to-date)

Good instructions are important for security: if we give bad advice, operational security failures may result. That's why we should have at least basic docs ready for the audit.

**Comment by eloquence** [comment]
For the purposes of the alpha release, it is sufficient if these instructions sit in the repository README (which needs to be updated as part of the client integration anyway) and/or a separate GDoc. They should cover manual instructions for exporting files from the workstation (via an export VM), so that we can get auditor feedback on this approach.

**Comment by redshiftzero** [comment]
@zenmonkeykstop is taking a first stab at this

**Comment by eloquence** [comment]
This is done for the purposes of the audit, proper RTD end-user documentation will be tracked in a future issue.
