### ISSUE TITLE
Refactor logging configuration from Salt (at provisioning) to systemd (at boot) 

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/securedrop-workstation#1033]
## Description
Implementing https://github.com/freedomofpress/securedrop-workstation/issues/1004 (salt -> systemd / qubes-services) for the particular case of logging.

Same [as the parent issue](https://github.com/freedomofpress/securedrop-workstation/issues/1004#issue-2264362305):
> ## How will this impact [SecureDrop/SecureDrop Workstation users](https://github.com/freedomofpress/securedrop-ux/wiki/Users)?
> 
> No user implications.
> 
> ## How would this affect the SecureDrop Workstation [threat model](https://github.com/freedomofpress/securedrop-workstation/#threat-model)?
> 
> Along with #1001, this assumes we are comfortable with runtime (boot-time) configuration of VMs' roles and services, [except for secrets](https://github.com/freedomofpress/securedrop-workstation/issues/936#issuecomment-1930590304).

**Comment by legoktm** [comment]
I agree with you that the positive approach seems more logical, but based on the implementation notes, it seems implementing the negative approach is easier (and also already done), so I'd favor that for now?

> removing files on boot could lead to race condition bugs

What are you worried about, given that systemd would prevent rsyslog from starting until after our service finishes?
