### ISSUE TITLE
Refactor mime-handling configuration from Salt (at provisioning) to systemd (at boot)

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/securedrop-workstation#1042]
* [x] I have searched for duplicates or related issues

## Description

Partly fixes #1004, by moving mime-time overrides onto systemd services for provisioning at boot.

## How will this impact [SecureDrop/SecureDrop Workstation users](https://github.com/freedomofpress/securedrop-ux/wiki/Users)?

No user implications.

## How would this affect the SecureDrop Workstation [threat model](https://github.com/freedomofpress/securedrop-workstation/#threat-model)?

Along with https://github.com/freedomofpress/securedrop-workstation/pull/1001, this assumes we are comfortable with runtime (boot-time) configuration of VMs' roles and services, https://github.com/freedomofpress/securedrop-workstation/issues/936#issuecomment-1930590304.

**Comment by rocodes** [comment]
Yup I agree with you @deeplow, I'm musing about the future (and/or the proxy) but don't think this should be part of the immediate game plan, the changes you've proposed are solid
