### ISSUE TITLE
[Qubes 4.1] Release securedrop-workstation-dom0-config 0.11.1

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-workstation#1057]
- RM: @rocodes 
- Deputy RM: @zenmonkeykstop 
- Comms: @rocodes / @nathandyer 
- QA: @rocodes @cfm 
 
This release targets Qubes 4.1 and is a hotfix release based off 0.11.0 .

For initial QA, the 0.11.1 rpm can be built locally from the `release/0.11.1` branch and applied via dnf as described in the test plan. For preflight testing, it should be installed via yum-qa.securedrop.org.

### Release:
- [x] [In release branch] Bump version via `update_version` script, and update [changelog in rpm .spec file](https://github.com/freedomofpress/securedrop-workstation/blob/main/rpm-build/SPECS/securedrop-workstation-dom0-config.spec)
- [x] [In release branch]  Create prod tag (signed by release signing key)
- [x] Build prod artifact, sign with release key, commit build logs
- [x] QA/smoketest of prod artifact (stuff rpm in dom0 of SDW prod machine)
- [x] Publish prod artifact to yum repo

### Post-release
- [ ] Retro if/as needed
- [ ] Update documentation

### Setup instructions
Testers, note: we are not updating the bullseye template with the new key, just the dom0 rpm and the deb packages in individual vms.

#### Testing RCs (yum-test, apt-test)
**Suggested test environment for RCs** (all on **staging** please so that you can also pull in the keyring deb!) is an upgrade scenario (no provisioning, just running the updater). If you don't have a 4.1 instance anymore, install Qubes 4.1 and set up your environment per test plan in https://github.com/freedomofpress/securedrop-workstation/pull/1101 (so just the old gpg key import into rpm and /etc/pki/), and follow the 'provisioning' test path below.  The true "Fresh install" isn't a required test plan, since we won't support fresh installs on 4.1.

RC testers will need to import the new test key: https://github.com/freedomofpress/securedrop-workstation/pull/972

#### Prod Preflight Testing (yum-qa, apt-qa)
**Suggested test environment for prod testing (yum-qa): Upgrade testing is required.** Please install a production version of SDW (latest sdw dom0 rc: 0.11) and verify basic functionality (VMs boot, updater can run even if no-op). Then, manually switch to the apt-qa and yum-qa repos as follows:
- [ ] in dom0, edit `/etc/yum.repos.d/securedrop-workstation-dom0.repo` so it points to yum-qa
- [ ] in the small and large bullseye templates, edit `/etc/apt/sources.list.d/securedrop_workstation.list` to point to apt-qa. Then shut down the templates.
- [ ] Run the updater.

### Test plan
- [ ] 0.11.1{-rcX} RPM installs successfully (note whether installed via dnf install or via the updater)
- [ ] provisioning (sdw-admin --apply) completes successfully if "fresh" install
- [ ] After provisioning or updating, `gpg /etc/pki/rpm-gpg/RPM-GPG-KEY-securedrop-workstation` shows key with updated expiry
- [ ] After rebooting, `rpm -q gpg-pubkey-7b22e6a3-*` shows one entry, ending in `66ad` (prod)
**Keyring testing**:
- [ ] `apt-cache policy securedrop-keyring` on SD debian VMs shows the 0.10.2-rc1 package installed (prod)
- [ ] `/etc/apt/trusted.gpg.d/securedrop-keyring.gpg` contains updated keyring (and no other sd keyring related files) (prod)

**Comment by rocodes** [comment]
### Test plan
envt: 4.1 staging fully-provisioned system
- [x] 0.11.1{-rcX} RPM installs successfully (note whether installed via dnf install or via the updater): updater
- [ ] provisioning (sdw-admin --apply) completes successfully if "fresh" install (n/a)
- [x] After provisioning or updating, `gpg /etc/pki/rpm-gpg/RPM-GPG-KEY-securedrop-workstation` shows key with updated expiry (yes but it's the test key cause staging) 
- [ ] After rebooting, `rpm -q gpg-pubkey-7b22e6a3-*` shows one entry, ending in `66ad` (prod) [not here yet, staging]
**Keyring testing**:
- [x] `apt-cache policy securedrop-keyring` on SD debian VMs shows the 0.10.2-rc1 package installed
- [x] `/etc/apt/trusted.gpg.d/securedrop-keyring.gpg` contains updated keyring (and no other sd keyring related files)

**Comment by rocodes** [comment]
(In-VM + in-dom0 smoketest of rpm and deb in 4.1 was good, and they are now up on apt-qa. Proceeding with prod preflight qa per test plan).

**Comment by cfm** [comment]
## Prod Preflight Testing (yum-qa, apt-qa)

**Environment:**  Long-running Qubes 4.1 system after `sdw-admin --uninstall` and reinstalling from Workstation 0.11.0

- [x] in dom0, edit `/etc/yum.repos.d/securedrop-workstation-dom0.repo` so it points to yum-qa
- [x] in the small and large bullseye templates, edit `/etc/apt/sources.list.d/securedrop_workstation.list` to point to apt-qa. Then shut down the templates.
- [x] Run the updater.

### Test plan
- [x] 0.11.1{-rcX} RPM installs successfully (note whether installed via dnf install or via the updater)
- ~~provisioning (sdw-admin --apply) completes successfully if "fresh" install~~
- [x] After provisioning or updating, `gpg /etc/pki/rpm-gpg/RPM-GPG-KEY-securedrop-workstation` shows key with updated expiry
- [x] After rebooting, `rpm -q gpg-pubkey-7b22e6a3-*` shows one entry, ending in `66ad` (prod)

**Keyring testing**:
- [ ] `apt-cache policy securedrop-keyring` on SD debian VMs shows the 0.10.2-rc1 package installed (prod)
- [ ] `/etc/apt/trusted.gpg.d/securedrop-keyring.gpg` contains updated keyring (and no other sd keyring related files) (prod)

**No,** but `/etc/apt/sources.list.d/securedrop_workstation.list` was reset by Salt from `apt-qa` back to `apt`.  Retesting template-level updates manually....

**Comment by rocodes** [comment]
Hm, sorry about that. As discussed elsewhere, updating the templates then rebooting is fine - thank you for amending

**Comment by rocodes** [comment]
Both the dom0 config rpm and the keyring deb have been released and communications have gone out to pilot participants. Tomorrow I will close out the relevant tickets. Thanks everyone :)

**Comment by rocodes** [comment]
Closed by https://github.com/freedomofpress/securedrop-yum-prod/pull/54 , docs changes not required
