### ISSUE TITLE
Multiple update notifications upon resuming a session 

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-workstation#1069]
* [x] I have searched for duplicates or related issues

## Description

If a user starts up SDW laptop, does not apply updates, and locks the screen for a period of time, upon logging in again  they may see more than one update prompt in sequence.

Mostly filing for searchability for our future selves.

## Steps to Reproduce

STR: (4.2 any build) Power on SDW, wait >2h.  Log in again. 

## Expected Behavior

One update notification

## Actual Behavior

Sequential update notifications

## Comments

Suggest wontfix - users shouldn't have the laptop idle and should apply updates when prompted

**Comment by legoktm** [comment]
Wontfix is fine with me too, they can also hit cancel on the duplicative prompts.
