### ISSUE TITLE
Enable AppArmor in the sd-journalist VM

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#108]
For Whonix templates the use of AppArmor profiles is disabled by default and is opt-in [0]. We should consider enabling AppArmor in both Whonix templates :
* whonix-ws: which will be used by journalist to browse the Internet on the securedrop-workstation
* whonix-gw: which will be used by the securedrop client to communicate with the SecureDrop server's journalist interface.

Since we should be moving to Whonix 14, this should be done as part of or after #122
[0] : https://www.whonix.org/wiki/Qubes/AppArmor

**Comment by redshiftzero** [comment]
Should this be ticket for enabling AppArmor for the tor process in `sd-whonix`?

**Comment by emkll** [comment]
Good point @redshiftzero, I have updated the ticket description to include both whonix gateway and workstation.
