### ISSUE TITLE
`sd-devices` menu should include file manager

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#1109]
The `sd-devices` application menu currently only lists `XTerm`. Since we're explicitly asking folks to [open the file manager](https://workstation.securedrop.org/en/stable/journalist/submissions.html#exporting-to-an-export-usb) to work with VeraCrypt devices, we should ensure that it's present in the menu.

**Comment by legoktm** [comment]
Erik checked that this was previously available (under Qubes 4.0 fwiw) so I'm marking this as a release blocker/regression rather than an enhancement.
