### ISSUE TITLE
RPM builds are not reproducible due to mtime timestamps

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-workstation#1110]
* [ ] I have searched for duplicates or related issues

## Description

See discussion on https://github.com/freedomofpress/securedrop-yum-test/pull/58, in some builds, the files do not have their mtime clamped, while in others they are.

**Comment by legoktm** [comment]
I haven't yet figured out how I was unable to build an unreproducible RPM, in my follow-up tests it is reproducible...so something went wrong. I've written a script that runs after the build and verifies the mtimes are clamped properly. At least it'll fail much earlier.

**Comment by cfm** [comment]
Also seen on `LICENSE` in <https://github.com/freedomofpress/securedrop-yum-test/pull/59#pullrequestreview-2152154818>.

**Comment by legoktm** [comment]
@rocodes and I seem to have figured out the RPM reproducibility issue, when they say "clamp mtime", they literally meant it, i.e. `min(file mtime, source_date_epoch)`, so if the file's mtime was older than the changelog date, it wouldn't be clamped and therefore unreproducible. This is documented at https://github.com/rpm-software-management/rpm/blob/master/docs/manual/buildprocess.md#reproducability

Given that `%build_mtime_policy` was only documented 3 months ago, I'm going to assume it's not in F37's rpm, but also even that doesn't do what we want, it just clamps. I think if we touch every file we should be set, as long as we don't set changelog times to be in the future. Maybe we touch to a time like a day in the future just in case?
