### ISSUE TITLE
Create securedrop-workstation debian metapackage

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#113]
This metapackage should as dependencies: the hardened `linux-image`, `linux-headers`, `paxctld`, `libelf-dev` (for building the Qubes kernel module) as well as any other packages deemed necessary.

**Comment by conorsch** [comment]
For clarity's sake, the metapackage proposed should be `securedrop-workstation-grsec`, not `securedrop-workstation`. Such a naming convention would match what we ship for SecureDrop servers, via the `securedrop-grsec` metapackage, which lists dependencies for linux-image and linux-headers packages.

>  as well as any other packages deemed necessary.

Those would be more appropriate for a `securedrop-workstation` metapackage, in which we bundle tooling for use by journalists, e.g. metadata redaction. We don't have a clear picture yet of precisely what those packages are, so I suggest we break out that ask into a separate ticket.

**Comment by emkll** [comment]
To further clarify the packages we will need after a discussion with @redshiftzero :

1. `securedrop-workstation-grsec`: SecureDrop workstation kernel metapackage that will pull in the appropriate grsecurity kernel version into the SecureDrop workstation Qubes template.
2. `securedrop-workstation-client`: SecureDrop workstation client, including the SecureDrop SDK, to be installed in the sd-svs client.
3. `securedrop-workstation-api-proxy` which will contain the API proxy used by the client to communicate to the Journalist Interface
4. One metapackage per type of template/VM we would like to maintain on the SecureDrop workstation to easily manage updates(e.g: svs, journalist)
