### ISSUE TITLE
Use Fedora 28 templates

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#114]
Fedora 26 is now end-of-life [0], AppVMs that use Fedora 26 template should be updated to a more recent release. We should use Fedora 28 as 27 will be EOL 1 month after 29 release which is is tentatively scheduled for later this year [1].

[0] : https://fedoraproject.org/wiki/End_of_life
[1] : https://fedoraproject.org/wiki/Releases/29/Schedule

**Comment by conorsch** [comment]
See here for upgrade instructions from Qubes team: https://www.qubes-os.org/doc/template/fedora/upgrade-27-to-28/

**Comment by conorsch** [comment]
Used the [detailed instructions](https://www.qubes-os.org/doc/template/fedora/upgrade-27-to-28/#detailed-upgrading-the-standard-fedora-27-template-to-fedora-28-1) to upgrade Fedora 26 -> Fedora 27, will run through the same process for 27 -> 28 and report back.

The config tests will need to be updated for F28, as we did in #67.

**Comment by emkll** [comment]
I recommend running `sudo qubes-dom0-update qubes-template-fedora-28` to pull the template directly from the qubes repos
