### ISSUE TITLE
Updater: updates are ignored on qubes updated in the last 7 days

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/securedrop-workstation#1140]
* [x] I have searched for duplicates or related issues

## Description

With the `qubes-vm-update` flags we were using, the updater was being "smart" about which qubes it targeted.  So if we specified `--targets template-1 template-2`, it would only update the templates whose `qvm-features last-updates-check` were > 7 days (the default) but which reported to updates available.

## Steps to Reproduce

1. Be on Qubes 4.2.2-rc1
2. Run `qubes-vm-update --targets sd-small-bookworm-template` (or any template which has updates)
3. Run again `qubes-vm-update --targets sd-small-bookworm-template`

## Expected Behavior

All templates are forced to update, regardless of Qubes' internal awareness of updatedness.

## Actual Behavior

Exits immediately with message: No qube selected for update.

## Comments

**Solution A (quick fix)** The solution is to use the [new](https://github.com/QubesOS/qubes-core-admin-linux/commit/1718936f40bc8f2e7554a61ac5fc2ea8db544f6e) `--force-update` flag, which fully respects the `--targets`.

**Solution B (more permanent) https://github.com/freedomofpress/securedrop-workstation/issues/1141** The alternative (if we're willing to drop the updates-every-8-hours to 24h), we can just add the flag `--update-if-stale 1`, which only updates the templates which haven't had updates in at least a day. If this requirement is not droppable, we can ask upstream if having a float value for `--update-if-stale` can be considered.

For now solution A suffices, but ideally we delegate this last-update-checking logic to the updater by going with solution B. Actually, I think the reason why we didn't go with solution B when implementing the updater integration in the first place was due to the fact that `--targets` would not respect stale templates. But now that's change -- it's the CLI interface change that created this GH issue!

**Comment by rocodes** [comment]
Thanks for the helpful report and investigation. Briefly I'd be in favour of moving to every 24h and `update-if-stale 1` and the GUI updater after this release, but appreciate you offering a quick fix as well
