### ISSUE TITLE
Reassess the need for `nopat` kernel option

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/securedrop-workstation#1171]
Currently, only [sd-whonix VMs](https://github.com/freedomofpress/securedrop-workstation/blob/5b4d10ae16b608e5769b0e541da21004e334d019/securedrop_salt/sd-sys-whonix-vms.sls#L28) have the nopat kernel option explicitly enabled.

With some git archeology I traced the original introduction to [this commit](https://github.com/freedomofpress/securedrop-workstation/commit/74a6a016436fdf7988bb0e625cd3ac5a734a6e60). It makes no mention of why nopat is needed. The linked [Whonix apparmor wiki page](https://www.whonix.org/wiki/Qubes/AppArmor) also does not provide any clues as to why this is needed.

From the [kernel documentation](https://www.kernel.org/doc/html/v4.14/admin-guide/kernel-parameters.html) I can't really infer the context in which this is needed.

>      nopat           [X86] Disable PAT (page attribute table extension of
>                        pagetables) support.

So my main question is: do we still need this?

**Comment by legoktm** [comment]
~~I don't know what nopat is for; I read through https://docs.kernel.org/next/arch/x86/pat.html and https://en.wikipedia.org/wiki/Page_attribute_table and still don't know why we'd set it.~~

OK, I dug harder and found https://lore.kernel.org/lkml/1329753687-29218-2-git-send-email-konrad.wilk@oracle.com/T/ and https://wiki.xenproject.org/wiki/Linux_3.0_bugs_impacting_Xen which probably answer it: PAT under Xen used to be buggy, so you had to manually set nopat.

This was built into Linux with https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=8eaffa67b43e99ae581622c5133e20b0f48bcef1 and https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c79c49826270b8b0061b2fca840fc3f013c8a78a so setting the option was no longer necessary (2013).

Then in late 2014, https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=47591df505129c9774af6cca2debf283a6e56ed7 landed, which fixed PAT-with-Xen. We have a much newer kernel than that, so we can safely remove the nopat option.
