### ISSUE TITLE
Improve contributing guidelines

### ISSUE THREAD

**Issue by ben-grande** [freedomofpress/securedrop-workstation#1176]
* [x] I have searched for duplicates or related issues

There is no documentation specific to securedrop-workstation on how to contribute to.

There is [securedrop workstation development](https://developers.securedrop.org/en/latest/workstation_development.html) and [contributing to securedrop](https://developers.securedrop.org/en/latest/contributing.html), but they are not enoguh to understand everything that is necessary to know to contribute to.

I'd like to contribute to securedrop but I am lost.

On another point, I'd like to ask for the development to be more open to external contributors, such as open meetings.

**Comment by cfm** [comment]
Thanks for filing this after our conversation, @ben-grande.  Let me know what you think of freedomofpress/securedrop-dev-docs#191, which will be linked here after #1177.  Are there other topics on which you'd like more details or resources?

**Comment by ben-grande** [comment]
The [development setup on Qubes](https://developers.securedrop.org/en/latest/setup_development.html#qubes) would be better if automated with salt states, but that depends if the developer will be able to copy the states to dom0 which involves getting a repo there or copying some (possibly 2) salt files.

I believe it is okay the contributing doc for now, mostly because I didn't contribute code yet, so I am not able to make proper assessments to see the missing steps.

**Comment by zenmonkeykstop** [comment]
Closing this initial ticket with the changes in https://github.com/freedomofpress/securedrop-dev-docs/pull/191 - @ben-grande or others, please feel free to make further reccomendations!
