### ISSUE TITLE
Remove sd-decrypt AppVM

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-workstation#121]
In the current incarnation of the workstation, the decrypt AppVM doesn't seem to be necessary. Instead, we can allow `qubes.Gpg` from `sd-svs`, which is where the UI will run and it is not network-connected. Note that the submission key will still be stored in vault VM `sd-gpg`. The advantages here are: simplify architecture and reduce memory consumption. Is there a reason why the `sd-decrypt` AppVM should be kept? (i.e. which threats are mitigated by `sd-decrypt`)

**Comment by emkll** [comment]
In the SecureDrop Workstation 0.1 milestone, we will no longer use a Whonix workstation as a Journalist VM: we will use the the SecureDrop client. 

Using a dedicated sd-decrypt vm under the the current model (journalist workstation is sd-whonix-ws) makes sense, as it removes the ability of a persistent, internet-connected vm with a large attack surface to directly communicate with the SVS (through `qvm-open-in-vm`).

Based on the current 0.1 milestone for the SecureDrop workstation, the (non-internet-connected) SVS will be running a Client application, communicating to the internet via a qrexec proxy. Given this architecture change, using sd-decrypt will no longer be necessary: If an attacker has already compromised `sd-svs`, they already have access to the decrypted files.
