### ISSUE TITLE
Update whonix to v14

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#122]
Whonix 14 has been released [0]. Whonix 14 uses Debian Stretch as a base OS. Whonix 13 uses Debian Jessie, which is no longer supported by the Debian security team [1] but still receives community support. We should update the whonix gateway (and workstation?).

The template can be installed in `dom0` as follows, and changing the netvm of the appropirate VMs should be more reliable than updating whonix 13 vms in place:
```
sudo qubes-dom0-update --enablerepo=qubes-template-community qubes-template-whonix-gw-14
```

[0] : https://forums.whonix.org/t/whonix-14-has-been-released/5404/5
[1] : https://wiki.debian.org/LTS

**Comment by edenemmanuel** [comment]
On Friday, 24 August, the Qubes OS team [announced that Whonix 13 is approaching EOL](https://www.qubes-os.org/news/2018/08/24/whonix-13-approaching-eol/) and have provided helpful instructions.

Also, worth noting:

>We also provide a fresh Whonix 14 TemplateVM package through the Qubes repositories, which you can install in dom0 by following the [Whonix installation guide](https://www.whonix.org/wiki/Qubes/Install). If you encounter any difficulties when attempting to upgrade or install Whonix templates, please consult the [Whonix Support](https://www.whonix.org/wiki/Support) page.

**Comment by redshiftzero** [comment]
Oops, we updated to Whonix 14 in commit b17faf0928c02f38f1290b6a6e369514a11cc9cd in #124, closing!

**Comment by kushaldas** [comment]
>sudo qubes-dom0-update --enablerepo=qubes-template-community qubes-template-whonix-gw-14

Reopening the issue as the exact same command, which worked before, can not find the template today. I will close it when more people can verify that it is working again. I found more people in the `#qubes` IRC channel with the same issue.

**Comment by kushaldas** [comment]
False alarm, the `qubes-dom0-update` tool behaves strangely if a package is already installed.
