### ISSUE TITLE
Run template update actions as part of "make all"

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#126]
We currently have two provisioning targets in the Makefile used to update EOL templates to maintained versions:

* `make update-fedora-templates`
* `make update-whonix-templates` (#124)

These are not run automatically as part of `make all`, but probably should be. We'll need to make sure that the scripts invoked are idempotent; at a glance, the conditional logic should be sufficient.

**Comment by joshuathayer** [comment]
I had a local dev branch which did this and did some testing to show that both make targets are idempotent (which they seemed to be).
