### ISSUE TITLE
Create PR template with test plan

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#132]
All PRs to this repo should include a test plan to validate changes do not include regressions. At the very least, we should expect:

* [ ] `make all` passes without error in `dom0`
* [ ] `make test` passes without error in `dom0`
* [ ] Successfully retrieved and viewed a submission

Adhering to such a simple test plan would have caught breaking changes introduced in #124. (See #127 for follow-up.) We should include the test plan in PR submission texts by default, to aid in review.

**Comment by eloquence** [comment]
A PR template has been added and refined since this was filed, so this can be closed:

https://github.com/freedomofpress/securedrop-workstation/commits/main/.github/PULL_REQUEST_TEMPLATE.md
