### ISSUE TITLE
Tag all Salt-managed VMs with "securedrop-workstation"

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#135]
There are a few "target-all-VMs" operations, e.g. destroy-all, create-all. Right now we're explicitly listing each VM referenced in the Salt config for use in these contexts, which creates a fair amount of duplication.

Let's tag all VMs with at least "securedrop-workstation" (in addition to any other more specific tags). Doing so would allow us to refer to the set of all VMs for programmatic actions such as base config, or destroy actions.

**Comment by redshiftzero** [comment]
done in 7b7b1a1
