### ISSUE TITLE
Convert sd-journalist to sd-proxy

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#138]
Porting the discussion from https://github.com/freedomofpress/securedrop-workstation/issues/107#issuecomment-409779664:

> We confirmed that a new `sd-proxy` VM (which takes the place of the `sd-journalist` VM) should expose a qrexec service called by `sd-svs`.

It's not just a nomenclature change, it's a full tooling swap. We'll need shake out the [sd-proxy](https://github.com/freedomofpress/securedrop-proxy) config (and packaging story) separately, which will unblock this work.

**Comment by eloquence** [comment]
Edited top-level task since #127 was resolved a while ago. To recap the key blocking tasks are #156, #131 (will be closed by #160) and #161.
