### ISSUE TITLE
Tor Browser not installed in sd-journalist

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#148]
When running the latest config from the master branch, Tor Browser is not properly installed in the `sd-journalist` VM.

### Steps to reproduce
1. Run `make all` in `dom0`.
2. Wait until provisioning run finishes.
3. Navigate to Qubes menu -> sd-journalist -> Tor Browser (AnonDist)
4. Observe error message "Tor Browser is currently not installed. (Folder /home/user/.tb/tor-browser does not exist.)"

@joshuathayer pointed me to https://forums.whonix.org/t/bug-tor-browser-missing-in-dispvm-tor-browser-missing-in-whonix-ws-14-templatevm/5712, which looks like the same issue. We should be able to wait for upstream to resolve, but this issue affects the dev env because Tor Browser must be re-downloaded on every `make all` action.

**Comment by conorsch** [comment]
Cursory debugging indicates that running `update-tor-browser` inside `whonix-ws-14` resolves.

**Comment by redshiftzero** [comment]
this is resolved, Tor Browser is installed in `sd-journalist`
