### ISSUE TITLE
Update mimetype handling for Debian Stretch

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#158]
The submission handling logic relies on custom mimetype associations in order to ensure that submissions are never opened in the `sd-svs` AppVM (where the SecureDrop Client runs), but rather opens in a network-less DispVM. Once inside the DispVM, mimetypes are also important: the proper application must be selected to ensure a positive user experience. For example, we want to ensure that plaintext submission are opened in `gedit`, not `nano` or `vim`. 

Use of `xdg-open` _should_ be sufficient to ensure proper handling of mimetypes, but some additional dependencies may be required:

* `gvfs-bin` and `libgnomevfs2-bin` (to ensure `xdg-mime` operates correctly)
* `nautilus` should be present in the `sd-svs` VM (but isn't included by default in the `debian-9` template); we can revisit after #138 is implemented

We also want to ensure that system paths such as `/usr/share/applications/mimeapps.list` are not vulnerable to clobbering by upstream changes. It's also an option to declare the mimetype associations in `~/.config/mimeapps.list`, but using a non-system path will complicate both packaging logic and the use of TemplateVMs (since AppVMs receive their own $HOME by default, not copied from the base TemplateVM).

See the discussion thread in https://github.com/freedomofpress/securedrop-workstation/pull/155#issuecomment-426804059 for reference.

**Comment by conorsch** [comment]
While testing #160, noticed that JPG images open in a DispVM in Firefox. That's not what we want (although it does display the image). Let's force an appropriate handler for that type.

**Comment by kushaldas** [comment]
>`/usr/share/applications/mimeapps.list`

Just now verified that on Debian Stretch that file does not exists.

## How to test?

```
sudo apt-get install apt-file
sudo apt-file update
sudo apt-file find /usr/share/applications/mimeapps.list
```

I even checked this:

```
~$ sudo apt-file find /usr/share/applications/ | grep list
cinnamon-desktop-data: /usr/share/applications/x-cinnamon-mimeapps.list
gnome-session-common: /usr/share/applications/gnome-mimeapps.list
kde-telepathy-contact-list: /usr/share/applications/org.kde.ktpcontactlist.desktop
knowthelist: /usr/share/applications/knowthelist.desktop
```

@conorsch We are good to go :)
