### ISSUE TITLE
Define initial MIME type and application mapping

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#168]
As described in #75, ideally we'll ultimately be able to have a clear mapping of various supported file types against carefully chosen applications, and a comparison with the feature set of the Tails SVS.

Initially, however, we can make do with a preliminary subset of supported MIME types and applications. For the purposes of the audit, our goal is to demonstrate that files can be opened in different external applications using disposable VMs -- the specific choices do not have to be final.

What we need to close this task is a table that includes a reasonable subset of common document/media MIME types, common file extensions for that MIME type (for easy testing/identification), and the recommended handler application which should ideally exist as a Debian 9 stretch package we can specify as a dependency.

In the alpha release, all other MIME types will be unsupported and trigger an error message.

**Comment by eloquence** [comment]
Here is my initial set of recommendations:
https://docs.google.com/spreadsheets/d/1l-DGR5UnnvYA5jfeZtplER933ANPWgFLx_uWbnJZKWI/edit#gid=0

There are some caveats for certain handlers, please inspect the notes (black triangles on some cells). For example, if we rely on `xdg-open`, the default viewer after installing the recommended packages will not make sense for PDF files (will open in LibreOffice) or for Ogg Vorbis files (will open in video player).

**Comment by conorsch** [comment]
Great coverage, @eloquence ! Convenient that we can use `libreoffice` as a catch-all; I'd assumed we'd have to manage each subapp separately. The caveats you note are on point. The list here is useful both for assigning the relevant handlers, as well as managing PaX flags on the relevant binaries where necessary, now that #156 is resolved.

Also flagging that MP3 support and other formats may require non-free repos to be configured; I'd prefer to skip those for now and rely on the stable repos where possible, unless we have interview feedback that suggests prioritizing. 

We should also have a fallback option that bails out of the handler selection and displays a message to the user if an application format is unsupported—fine to punt to another issue to keep this one focused.

**Comment by eloquence** [comment]
NB, this is all based on testing in the debian9.5 template that shipped with Qubes 4.0. I did not have to configure any non-free repos to get MP3 working in audacious -- it just worked immediately. Debian 9.5 post-dates the MP3 patent expiry date,  which may be why, but I didn't confirm that.

**Comment by conorsch** [comment]
> I did not have to configure any non-free repos to get MP3 working in audacious -- it just worked immediately.

That's great news, happy we're downstream from those changes, then. Looks like we have strong coverage of common formats here, but perhaps we'll uncover more based on interview feedback.

Given that we'll want to ship updates to these over time, creating a Debian package for `sd-svs-disp` (as distinct from the `sd-svs` VM) sounds like the right approach. We can add to #167 if you agree, @eloquence ; in the meantime, happy to implement via Salt as a stopgap so we can push forward with testing the mapping behavior.

**Comment by eloquence** [comment]
SGTM, for now, added a checkbox to this effect to #167, tentatively suggesting `securedrop-svs-disp-config` for consistency w/ other meta-packages.

**Comment by eloquence** [comment]
Confirmed; we should be fine for CSVs.

Note that LibreOffice will become the default handler for plain text files after it is installed; I would suggest overriding that and forcing use of `gedit` (also noted in spreadsheet).

**Comment by eloquence** [comment]
Closing this task based on Mickael's and Conor's review, should be a reasonable starting point for building the SVS template.
