### ISSUE TITLE
Force hard system shutdown instead of suspend/hibernate

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#178]
For security reasons (e.g., full-disk encryption state, application of automatic system updates, etc.), we should ensure that the system is shut down instead of suspended/hibernated. At minimum, this should occur when closing the laptop lid; if we can disable (at least at the UI level) suspend/hibernate altogether, that would be preferable.

**Comment by conorsch** [comment]
> this should occur when closing the laptop lid

That we can do via `/etc/systemd/logind.conf`, setting `HandleLidClose=poweroff` (then bounce `systemd-networkd`) in `dom0`. Tested it and it does indeed power off the machine when the lid is closed. 

We'll need something else for disabling suspend altogether. A third case: when the machine is left idle for many hours, probably worth a shutdown, as well.

**Comment by eloquence** [comment]
> That we can do via `/etc/systemd/logind.conf`, setting `HandleLidClose=poweroff`

Nit: the setting is named `HandleLidSwitch`. I can confirm that changing it to `poweroff` and running `sudo systemctl restart systemd-logind` alters the behavior on my X1 Carbon as expected.

**Comment by emkll** [comment]
Closed via https://github.com/freedomofpress/securedrop-workstation/pull/475 and https://github.com/freedomofpress/securedrop-workstation/pull/473
