### ISSUE TITLE
Journalist provisioning story

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-workstation#18]
For comparison, the process of an admin provisioning a journalist workstation with our Tails workflow is currently:

1. Install Tails on USB drive
2. Enable persistent volume
3. Boot to the new drive and add the secrets (SecureDrop login info, ATHS token for journalist interface for the online journalist workstation and the submission private key for the Secure Viewing Station).

A zeroth order provisioning story for the Qubes workstation would be:

1. Install Qubes on target workstation
2. `sudo qubes-dom0-update securedrop-workstation` (see #17 for packaging)
3. Sprinkle in secrets - note we need to get these _into dom0_
4. Execute `run.sh` to provision (or the equivalent command in the eventual `securedrop-workstation` package)

**Comment by eloquence** [comment]
Lot of progress since this was filed, thankfully. Install docs being worked on here:
https://github.com/freedomofpress/securedrop-workstation-docs/pull/21

I'd suggest closing this once the docs land, and then tracking additional improvements iteratively.

**Comment by eloquence** [comment]
Closing per above. See https://workstation.securedrop.org/en/stable/admin/install.html for current install docs.
