### ISSUE TITLE
Workstation bootstrapping instructions or script

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#183]
Most of the workstation configuration will be ensured by #171 , but minor workstation configuration in dom0 will remain:

* FPF's repo is enabled in dom0 (requiring yum config in dom0 and the use of `--enablepo`
* Ensure that `securedrop-update` correctly tracks FPF repo for updates
* Configure install-time parameters (e.g. journalist interface onion/HidServAuth, if required)
* Install the `securedrop-workstation` package in dom0

Let's either provide instructions or a very simple script to bootstrap the workstation and its configuration. This should be addressed once #171 and #157 have been merged.

**Comment by kushaldas** [comment]
This should also make sure that if should not do the steps `prep-salt` in the `Makefile` when we install things via rpm in `dom0`. For my manual testing, I had to update the `Makefile` to remove the `clean` step and comment out `prep-salt`.
I would assume that we should get `securedrop-workstation-install` bash script in the repo which will assume that everything is installed via RPM and then also take arguments for config and also the secret key and then do the rest (what Makefile does).

**Comment by eloquence** [comment]
Resolved via docs for now; may revisit when we switch to RPMs.
