### ISSUE TITLE
Update application tests to run under Python 3

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-workstation#188]
The configuration tests under '/tests' are written for Python2.
On `dom0`, compare the results of 
```
make test
```
and
```
python3 -m unittest discover tests
```
The tests should be updated to run under Python3, and the Makefile targets should use Python3 explicitly.

**Comment by conorsch** [comment]
Took a look at this while builds were running; the diff is _quite_ small to update the config tests (as usual, update string handling to use `.decode("utf-8")` where appropriate). Will submit as part of another PR later today.
