### ISSUE TITLE
Fedora-26 still used for sys- VMs

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#189]
On a clean install, the current config logic will leave the core `sys-*` VMs based on `fedora-26`, which has been EOL'd. We should explicitly reassign a dependency on the latest Fedora VM (currently fedora-28) for those machines.

There may be existing Qubes-maintained Salt logic we can reuse in `/srv/formulas/base/virtual-machines-formula/qvm`.

Related to #111, #181, #186.

**Comment by kushaldas** [comment]
The current latest available version of Fedora in Qubes is `Fedora 29`.

**Comment by conorsch** [comment]
We're right to close this issue given changes in #248, but we'll certainly be revisiting the issue of updating EOL templates for the `sys-*` VMs once `fedora-30` is standard.
