### ISSUE TITLE
Whonix 13 templates still used for sys-whonix

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#191]
On a clean install, the current provisioning logic still leaves `sys-whonix` configured to use `whonix-gw` as its template, which is EOL'd. We should update the logic to force the association on `whonix-gw-14`. 

Note that there is logic in place in `/srv/formulas/base/virtual-machines-formula/qvm/*whonix*` to update the associations already, so we should begin by analyzing that logic and determining why it's insufficient. It may be as simple as the "template" pref not being updated for running VMs (at least that's true when using `qvm-prefs -s <vm> template <new_template>` via CLI). 

Related: #186, #189.

**Comment by emkll** [comment]
If we aren't targeting the fix for the alpha, we should consider just waiting for 4.0.1 where whonix-14 templateVMs will be included in the iso by default, no cleanup necessary: https://www.qubes-os.org/news/2018/11/05/qubes-401-rc1/
