### ISSUE TITLE
grsec kernel not installed by make all target on Qubes install with default debian-9 template

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-workstation#197]
On my 6th-gen Carbon X1 and a T480, both with Qubes installed booting with EFI instead of legacy mode, `make all` on current master fails to build the workstation template VM correctly (or to install the client packages on sd-svs) - the VM uses the default kernel, 4.9.0-6-amd64, instead of the custom grsec one.

**Comment by conorsch** [comment]
@zenmonkeykstop Can you share error output here? In a problematic template, run `aptitude show securedrop-workstation-grsec` and `sudo aptitude install -y securedrop-workstation-grsec`; include output from both.

**Comment by zenmonkeykstop** [comment]
Also, tried upgrading a kernel manually on a HVM domain built from the default debian-9 template:

```
echo "deb http://ftp.debian.org/debian stretch-backports main" | sudo tee -a /etc/apt/sources.list > /dev/null
sudo apt-get update
sudo apt-get -t stretch-backports upgrade
sudo apt-get install linux-image-4.17.0-0.bpo.1-amd64
```
This fails with a grub-probe error:
```
dpkg: error processing package linux-image-4.17.0-0.bpo.1-amd64 (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up linux-image-4.9.0-6-amd64 (4.9.88-1+deb9u1) ...
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-4.9.0-6-amd64
Warning: couldn't identify filesystem type for fsck hook, ignoring.
I: The initramfs will attempt to resume from /dev/xvdc1
I: (UUID=5c3382da-946c-4f73-bafa-36495e3162ad)
I: Set the RESUME variable to override this.
/etc/kernel/postinst.d/zz-update-grub:
/usr/sbin/grub-probe: error: failed to get canonical path of `/dev/mapper/dmroot'.
run-parts: /etc/kernel/postinst.d/zz-update-grub exited with return code 1
dpkg: error processing package linux-image-4.9.0-6-amd64 (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 linux-image-4.17.0-0.bpo.1-amd64
 linux-image-4.9.0-6-amd64
```

**Comment by zenmonkeykstop** [comment]
@conorsch the FPF apt repos aren't being added under /etc/apt either, so aptitude just errors out with:
```
E: Unable to locate package securedrop-workstation-grsec
```

**Comment by conorsch** [comment]
The FPF apt repos missing sounds like a separate issue, perhaps a race condition where we're inadequately declaring explicit dependency chains in the Salt logic. 

Since the upstream Debian kernel _also_ fails, the EFI mode is the best lead we have in terms of variables. Let's try the same workflow on the same hardware, with a legacy-mode install of Qubes, rather than EFI, and see if that resolves.

**Comment by emkll** [comment]
This sounds similar to an error I have encountered before, that was resolved by https://github.com/QubesOS/qubes-issues/issues/3178

**Comment by zenmonkeykstop** [comment]
@joshuathayer since you have a working install with EFI - does /dev/mapper/dmroot get created correctly in your sd-workstation-template VM?

**Comment by zenmonkeykstop** [comment]
looks like the qubes-kernel-vm-support package version that ships with the debian-9 template is a bit old and doesn't include a fix for the missing /dev/mapper/dmroot symlink. running `sudo apt-get upgrade` in the template gets the latest version. Rebooting, then running `sudo apt-get install securedrop-workstation-grsec` (or `sudo apt-get -f install` if it was previously broken) and rebooting gets the 4.14.74-grsec kernel.
