### ISSUE TITLE
Clean install can run out of disk space pulling in templates

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#202]
During a fresh install, the config logic downloads several GBs of packages, mostly in the form of dom0 templates, particularly:

* `qubes-template-fedora-28`
* `qubes-template-whonix-gw-14`
* `qubes-template-whonix-wg-14`

The multiple fetches routinely cause disk quota errors, as the dnf cache on sys-firewall fills up. A reboot of the entire workstation generally resolves; we should resize the root volume on sys-firewall in order to accommodate for the fetching.

**Comment by marmarek** [comment]
Using Qubes 4.0.1 may help, as it ships with Whonix 14 by default and also debian-9 and fedora-29.

**Comment by conorsch** [comment]
Thanks @marmarek, looking forward to testing a clean install of 4.0.1 to verify that behavior.

**Comment by eloquence** [comment]
We've not seen this issue on recent installs which ship with templates we need. Keeping this issue open radar though in case we run into it again with future install requirements.

**Comment by eloquence** [comment]
We've not seen new reports of this issue for a long time, presumably due to the default templates that ship with recent releases of Qubes, so closing.
