### ISSUE TITLE
Hardening / stripping down templates

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-workstation#21]
We should consider applying additional hardening to the templates used in the workstation, in particular:

* The template used for `sd-journalist` (right now this is `whonix-ws` but we might want to fork off that template if we end up hardening the template (i.e. `qvm-clone` the template)) since it is internet connected
* The disposable VM template used to open SecureDrop submissions (since SecureDrop submissions are just arbitrary files from anonymous people)

**Comment by redshiftzero** [comment]
Regarding grsec, let's test out the workaround provided here: https://github.com/QubesOS/qubes-issues/issues/3178

**Comment by eloquence** [comment]
In addition to template stripping and configuration hardening, we agreed that some mitigation against arbitrary code execution, esp. in the display VM and in Internet-connected VMs, is a must-have deliverable for the version of the workstation to be audited, so I've added this issue to the 0.1alpha milestone. 

A grsec-patched kernel for the most sensitive VMs remains our top priority, but we can investigate whether other strategies (e.g., very strict AppArmor profiles, additional sandboxing) are adequate for the first release if we run into major feasibility issues.

**Comment by eloquence** [comment]
Closing in favor of #239 and other more specific issues (e.g., #234 , #19, #22).
