### ISSUE TITLE
Add an export/print VM

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#213]
Current Readme instructions provide manual instructions for provisioning a template to export files to USB or via OnionShare, but we should automate this process to reduce complexity and user error. We will need to add a custom tag (e.g.: `sd-export`) and explicitly allow qubes-rpc policies for the export AppVM (For example, `qubes.Filecopy -> sd-svs $tag:sd-export allow`)

**Comment by eloquence** [comment]
This task should be considered blocked until #84 is resolved.

**Comment by eloquence** [comment]
Note: This VM will likely also be used for printing. 

Changed issue title accordingly. As discussed in #84, a persistent-name disposable VM with consistently attached devices may be a good candidate architecture. The client will support collecting a bunch of files in a "briefcase" (potentially from different sources), and then exporting them as a group to said disposable VM for export/printing.

**Comment by eloquence** [comment]
As of #259 we now have provisioning support for a basic export VM; print support will be addressed in follow-up. Closing this issue in favor of a specific one focused on print requirements.
