### ISSUE TITLE
make test fails because test expects sd-whonix templateVM to be whonix-gw-14

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-workstation#215]
`make test` fails in dom0 with message:
```
======================================================================
FAIL: test_sd_whonix_config (test_vms_exist.SD_VM_Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kog/securedrop-workstation/tests/test_vms_exist.py", line 42, in test_sd_whonix_config
    self.assertTrue(vm.template == "whonix-gw-14")
AssertionError: False is not true
```
sd-whonix' templateVM is actually sd-whonix-template going by the salt config.

**Comment by conorsch** [comment]
> sd-whonix' templateVM is actually sd-whonix-template going by the salt config.

That just changed, as of 482c24554cbcde1d6f2d8e5bb63deff08736d0f8; latest master includes sd-whonix being based on `whonix-gw-14`; you'll have to `make clean` then `make all` to get the update. (`make all` is significant faster now, since #210).

**Comment by conorsch** [comment]
It's necessary to run `make all` because as far as I can tell, it's not possible for us to "force" the template designations via Salt; in that sense, the Salt logic isn't quite as declarative as we'd hope.

**Comment by zenmonkeykstop** [comment]
looking at my command history, I had run `make clean` first - but I'll give it another go.

**Comment by zenmonkeykstop** [comment]
Not reproducible now. Closing this.
