### ISSUE TITLE
UX during processing

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-workstation#23]
We should add lots of nice notifications so that users understand (to the degree possible) what is going on when the VMs are processing the submission. For example, if a given step is particularly slow they should get a notification that is it going to be slow ("Please wait! This can take a moment!") so they don't start wildly clicking everywhere or think the workstation is broken.

**Comment by joshuathayer** [comment]
I think this is covered by #40, which has the beginnings of a GUI for exactly that. Though it's not a great interface, I think it's sufficient to close this issue- we can make new issues for changes to it.
