### ISSUE TITLE
Display system alert recommending shutdown after 5 days of activity

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#236]
To ensure security updates are applied and to reduce the risks of memory-based attacks, we should display a warning to the user if the workstation has been running continuously for more than 5 days. The warning could say something like:

"This SecureDrop Workstation has been operating for more than 5 days. for security reasons, we recommend leaving the workstation powered on only when it is in use. Would you like to shut down the workstation now?

[ Yes, shut down workstation ] [ No ]"

**Comment by pierwill** [comment]
Looking into this. Considering creating `scripts/uptime-notify` to run as a cronjob. The basic logic would be to run every hour. If system uptime exceeds 5 days, the script would then begin sending notifications on the hour using `notify-send`: "This SecureDrop Workstation has been operating for more than 5 days. For security reasons, we recommend restarting the system."

**Comment by redshiftzero** [comment]
For security updates, we want to warn the user to perform updates after 5 days, here's a doc with the various cases we should consider:  https://docs.google.com/document/d/1cCpcpLRiKC0tm_vsD4k4Q1Fr5_R34htCb8FNTV8mRCI/edit# (comments welcome). We can work on the UI piece now but we should hold off on modifying the conditions that the updater pops up until the behavior in #396 is merged.
