### ISSUE TITLE
Workstation update process

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-workstation#24]
If we decide to make a change to the VM structure here, then we'd need to ship an update (if the hot take in #17 pans out, then via the `securedrop-workstation` `dom0` package). Without further modifications in Qubes, they'd be notified of a `dom0` update and we'd need to manually have users kick off an update in `dom0`. 

Is this what we want? I think ideally we don't want to require user intervention to update the `securedrop-workstation` config.

**Comment by eloquence** [comment]
We agreed that some scripted update process for all templates used by the SecureDrop Workstation is a must-have feature for the 0.1alpha release, due to the significant risks potentially associated with running outdated templates.

**Comment by adrelanos** [comment]
https://www.whonix.org/wiki/Dev/Automatic_Updates

**Comment by kushaldas** [comment]
I am splitting up the update story for different parts of the Qubes.

I am using Fedora as an example.



## Where will all of the following commands/code execute?

All of the below commands/code will execute in  **dom0**. These should be
packaged as an rpm first, and then we should add the repository inside of
**dom0** before any other step. For the rest of the document, this rpm name is
**sdqubesadmin**


After this initial installation in dom0, everything else should be done by either
cronjob or using a GUI application in dom0 where users can just click.

### Getting the new template vm

TemplateVMs are packaged as rpm and available to *dom0*. This should be done
using the following steps. I am writing the bash example, but in real life I
would have a proper Python script and a GUI application which the users can
click to do update etc.



```
rpm -q qubes-template-fedora28
status=$?

if test $status -eq 1
then
    sudo qubes-dom0-update qubes-template-fedora28
fi
```


### Install our application into the TemplateVMs

We can have a yum repo file (or debian source file) pointing to the correct repository,
and that should also be packaged inside of the rpm of dom0.

When we have a new template installed, as the second step, our script should install
this repo file in the correct location in the templateVM.


```
qvm-copy-to-vm fedora-28 /usr/share/sdqubesadmin/sdqubes.repo
qvm-run fedora-28 "sudo mv /home/user/QubesIncoming/dom0/sdqubes.repo /etc/yum.repos.d/
```


### Update the templateVM to the latest packages

Qubes has an formal way to do this, but, that requires a bit of user interaction.
If our *sdqubesadmin* GUI application we can call the commands like:


```
qvm-run fedora-28 "sudo dnf update -y" --pass-io
```

After this, the script should restart all of the SecureDrop related appVMs.

This update step can be cron job, or a button click in the *dom0*.

### Install our SecureDrop client/proxy application

This is easy when we have our repository inside of the template.

```
qvm-run fedora-28 "sudo dnf install -y  securedrop-client securdrop-proxy securedrop-whatnot" --pass-io
```

After this, the script should restart all of the SecureDrop related appVMs.


^^ as we will have everything packaged as operating system package, this will
make sure that none of the appVMs are out of sync.


### What if we have a new templageVM? How to update all of our appVMs?


For the example, I am taking Fedora 29 as a future templateVM.

We will first repeat the steps given above to get the templateVM, and then update and get all of our
packages installed properly inside of it. Then say we have 3 appVMs for SecureDrop, 

- sd-svs
- sd-proxy
- sd-secret

The following
Python3 code (again, inside of the **dom0** ) can update the templates for those appVMs.



```Python
import qubesadmin

app = qubesadmin.Qubes()
new_template = app.domains["fedora-29"]  # This will be configurable to choose the latest template

sdvms = ["sd-svs", "sd-proxy", "sd-secret"]

for dom in app.domains:
    if dom.name in sdvms:
        # We have our domains
        dom.template = new_template

```

We should first check for if the vms are running for not, and only update
after shutting them down. But, that should be part of full implementation (not
for this example comment).

**Comment by kushaldas** [comment]
I also think we can minimize our usage of salt and just use Python script from dom0 to create/update/setup our application VMs. It will be much easier to maintain.

**Comment by conorsch** [comment]
For those who've not seen it yet, the conversation with the Qubes maintainers pointing us to the "placeholder" strategy for enabling updates to TemplateVMs is here: https://github.com/QubesOS/qubes-issues/issues/2718#issuecomment-381643740
