### ISSUE TITLE
Consider removing xdg-open from the app VM to ensure documents are not accidentally opened

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-workstation#243]
To aid developer agility, it may be necessary to have a switch for opening docs in disposable VMs to use `xdg-open` on Linux of `open` (I think) on macOS. As a preventative measure if there is a misconfiguration, `xdg-open` should be stripped from that VM.

**Comment by eloquence** [comment]
Closing in favor of https://github.com/freedomofpress/securedrop-client/issues/115 regarding the developer agility proposal. Our MIME type handling now provides secure defaults for the different AppVMs.
