### ISSUE TITLE
Add a regression test to our workstation repo for jessie sources

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-workstation#244]
## Description

Add a regression test to detect any jessie apt sources and fail if found.

## More info 

After installing `Qubes 4.0.1`, follow the `securedrop-workstation` readme instructions until you get to this point: https://github.com/freedomofpress/securedrop-workstation#building. Here, you will run `make all` and you might hit this error (like I did):

```
E: The repository 'https://deb.debian.org/debian jessie-backports Release' does no longer have a Release file.
```

Since we're on Stretch `jessie-backports` needs to be updated to `stretch-backports`. 

The issue is documented and said to be fixed here: https://github.com/QubesOS/qubes-issues/issues/4917

---
_I will confirm a workaround. It might be as easy as running the `Qubes Updater` and re-creating the debian and sd-dev templates._

**Comment by creviera** [comment]
This process worked for me:

1. Update repo in `sources.list`.

```sh
[user@debian-9 ~]$ sudo sed -i 's/jessie/stretch/g' /etc/apt/sources.list
```

2. Open Qube Manager and remove sd-workstation-template if it exists. This will be recreated in step 4 when you run `make all`.

3. 

3. Start over from here: https://github.com/freedomofpress/securedrop-workstation#download-configure-copy-to-dom0

This process should also work:

**Comment by eloquence** [comment]
This is an outdated issue (we're on Debian 10 and no sources.list update should be required during the installation), closing.
