### ISSUE TITLE
Updates for Qubes 4.0.1

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-workstation#245]
Qubes 4.0.1 includes Whonix 14 and Fedora 29, so we should:

- [x] Run through workstation provisioning on Qubes 4.0.1 and update the README to indicate we should install on Qubes 4.0.1
- [x] Handle removal of jessie-backports repo - https://github.com/QubesOS/qubes-issues/issues/4917
- [x] Update `test_all_fedora_vms_uptodate ` [here](https://github.com/freedomofpress/securedrop-workstation/blob/5d7a5642b6a8675a7b247a755aa0401a0687be93/tests/test_vms_platform.py#L71) to point to fedora 29
- [x] Remove section in docs instructing users to remove EOL whonix templates: https://github.com/freedomofpress/securedrop-workstation#upgrading-sys-whonix-and-whonix-ws-appvms-to-whonix-14
- [x] Remove section in docs instructing users to upgrade to Fedora 28: https://github.com/freedomofpress/securedrop-workstation#upgrading-sys-net-sys-usb-and-sys-firewall-to-fedora-28

**Comment by redshiftzero** [comment]
Once this issue is completed, #191 and #189 can be closed

**Comment by conorsch** [comment]
WIP branch at https://github.com/freedomofpress/securedrop-workstation/tree/245-first-run-for-qubes-4.0.1

There's one remaining problem: the `quiet=true` param doesn't seem to be working, which is causing the jessie-backports cleanup to fail on specifically the Whonix VMs. We can probably make that conditional without use of the `quiet` param. Will circle back and take another look.
