### ISSUE TITLE
Provide offline documentation for SecureDrop and SecureDrop Workstation

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-workstation#261]
As a journalist or admin user of the workstation, I would like an easy to locate thing to click on, to access what the team has carefully composed in the online RTD... but that does not require network access.

It would furthermore be helpful if "Read More" links within the Client could navigate to items within this documentation, but that would only be a COULD, to the MUST of simple offline docs access that's easily findable by any workstation user.

---
## Slack Convo About 

redshiftzero [10:49 AM]
spitballing: we could potentially do something like add a “docs download” API endpoint to the journalist interface which could enable the journalist to download a PDF of the documentation corresponding to the given securedrop release. this would get processed like other PDFs in the workstation and opened in a dispVM without network access

GitHub APP [10:49 AM]
eloquence
Comment on #4473 [docs] Add 0.12.2->0.13.0 workstation update guide
> for workstation docs.

(To clarify for posterity, meaning http://github.com/freedomofpress/securedrop-workstation docs, since that change is required for correct client behavior and has no relevance for most SecureDrop users.)
freedomofpress/securedropToday at 10:49 AM

mickael [10:50 AM]
or we can ship a PDF and bundle it in the client deb? like a `?` on the top bar, opens the pdf in dispvm (edited) 

redshiftzero [10:50 AM]
yep that would work too
thats better ^

eloquence [10:50 AM]
I personally like the idea of coupling it to packaging. it's a bit awkward for updates but has advantages for simplicity and network privacy

huertanix [10:50 AM]
Are there Gnome HIG guidelines on how to do app docs?

**Comment by eloquence** [comment]
Our ReadTheDocs Builds provide PDFs, e.g.: https://workstation.securedrop.org/_/downloads/en/stable/pdf/

`sd-app` has a mechanism for opening PDFs in disposable VMs. Perhaps the best way to action this issue would be to implement a user guide button, as seen in Nina's most recent prototypes, and ensure that we include an updated PDF with each release of `securedrop-client`. That would make this a client issue.

One question is under what circumstances we would open an offline version, vs. just opening the online docs in Tor.

**Comment by eloquence** [comment]
Closing in favor of https://github.com/freedomofpress/securedrop-client/issues/1169
