### ISSUE TITLE
Open LibreOffice files in sd-svs-disp VMs

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#266]
While LibreOffice is installed as part of #263, LibreOffice documents do not automatically open in the disposable VMs:
![Screenshot_2019-06-03_12-00-59](https://user-images.githubusercontent.com/15223328/58817106-f9bff000-85f8-11e9-81f8-339e8fa3ac30.png)

We should ensure LibreOffice files open automatically once they are send to an sd-svs-disp DispVM.

Originally uncovered as part of https://github.com/freedomofpress/securedrop-workstation/pull/263#pullrequestreview-245718564 , relevant parts copy pasted below for convenience:

This is because xdg-open relies on the file extension and not magic numbers (file appears to rely on a file's magic numbers)
```
user@sd-svs-disp:$ xdg-mime query filetype 1-single-celled_authorship-doc 
application/zip
user@sd-svs-disp:$ file --mime-type 1-single-celled_authorship-doc 
1-single-celled_authorship-doc: application/vnd.openxmlformats-officedocument.wordprocessingml.document
```
Changing the extension does change the association:
```
user@sd-svs-disp:$ mv 1-single-celled_authorship-doc 1-single-celled_authorship-doc.doc
user@sd-svs-disp:$ xdg-mime query filetype 1-single-celled_authorship-doc.doc 
application/msword
```
We could either:
a) Write a wrapper script that receives the file from sd-svs, looks at magic numbers and opens it with the correct application, or
b) See if xdg-mime supports using only magic numbers (however preliminary research came back empty so far)
c) Add extensions to submissions on the SecureDrop server code

**Comment by eloquence** [comment]
See comment in https://github.com/freedomofpress/securedrop-workstation/pull/263#issuecomment-499697253 , is this moot as soon as we resolve https://github.com/freedomofpress/securedrop-client/issues/163 ? If so that may be a better candidate for the next sprint.

**Comment by eloquence** [comment]
(Per chat with @emkll closing for now in favor of https://github.com/freedomofpress/securedrop-client/issues/163 ; we can revisit if that is insufficient.)
