### ISSUE TITLE
Release securedrop-proxy 0.1.4 and securedrop-client 0.0.8

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#268]
Needed to unblock build automation (https://github.com/freedomofpress/securedrop-debian-packaging/pull/44) due to switch to `pip-tools`. We're aiming to fully automate nightly builds soon after this release.

Blocked by https://github.com/freedomofpress/securedrop-client/pull/404

**Comment by redshiftzero** [comment]
Now that release tags are up, freedomofpress/securedrop-debian-packaging#44 and the other nightly build tasks are unblocked. Remaining steps on this issue now that tags have been created in:

- https://github.com/freedomofpress/securedrop-proxy/pull/35
- https://github.com/freedomofpress/securedrop-client/pull/428

is to build debian packages, make a PR (or two PRs) into securedrop-debian-packaging with the packaging related changes (e.g. the changelogs) and upload the built packages to the qubes test apt server.

**Comment by redshiftzero** [comment]
closing since it was completed, thanks @creviera and @emkll
