### ISSUE TITLE
Update kernel for SecureDrop workstation templates to 4.14.125 or later

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#269]
The workstation currently uses grsec kernel version 4.14.74 for SecureDrop VMs; the latest stable version available is 4.14.125. To ensure continued testing with a recent kernel, we should update to the latest stable grsec patch.

**Comment by conorsch** [comment]
Done, see:

* https://github.com/freedomofpress/securedrop-workstation/pull/276
* https://github.com/freedomofpress/securedrop-debian-packaging/pull/60
