### ISSUE TITLE
Apt upgrade logic requires dist-upgrade

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#273]
During a recent kernel version bump (https://github.com/freedomofpress/securedrop-debian-packaging/pull/60), we observed that SDW VMs are not automatically receiving the new version:

```
The following packages have been kept back:
  securedrop-workstation-grsec
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

The problem appears to be lack of `dist-upgrade` in the upgrade logic https://github.com/freedomofpress/securedrop-workstation/blob/b49c5f29d84de363b0c005b71667e4f9cb2d3a83/dom0/fpf-apt-test-repo.sls#L35-L41. Let's at least add dist-upgrade and confirm upgrades are automatic. Worth considering using Qubes's qubes.update-vm state, but that's likely better handled as part of #51.

Also noting that the template build process uses a different location for the apt repo: https://github.com/freedomofpress/qubes-template-securedrop-workstation/blob/ce19add9e0dc817c7c83e6863b0ec66e34894b00/securedrop-workstation/04_install_qubes_post.sh#L45 Let's update the logic to reuse that same location, otherwise we'll have duplicate (and potentially conflicting) config files.

**Comment by emkll** [comment]
The securedrop-update daily cron does pass the dist-upgrade flag[0], so this should affect new installs only, up until the daily cron runs.

[0] : https://github.com/freedomofpress/securedrop-workstation/blob/master/dom0/securedrop-update#L50
