### ISSUE TITLE
Update securedrop-workstation TemplateVM rpm package

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#275]
There have been a large amount of updates in the securedrop-workstation template since it's last build. Provisioning from scratch (or after deleting securedrop-workstation template) would require to install new kernels and update all packages, and downloading the template directly would be much quicker.

The test plan for #269 included creating a template using new kernel images, and they are tracked in the LFS repo. We should upload the built template RPM to the yum repo to ensure quicker workstation build times.

**Comment by conorsch** [comment]
New RPM has been uploaded. We have a PR tracking the artifact here: https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/3 Had some trouble formulating a dom0 command to upgrade the RPM in place, so trying a purge-then-install-clean to confirm the latest version is working.

**Comment by conorsch** [comment]
All set. New template is installed and all tests are passing. Verifying old/new versions:

```
[user@dom0 securedrop-workstation]$ sudo dnf info qubes-template-securedrop-workstation | grep -i release
Release     : 201905141842
```

and after the upgrade:

```
[user@dom0 securedrop-workstation]$ sudo dnf info qubes-template-securedrop-workstation | grep -i release
Release     : 201906251955
```

Unfortunately the new package won't _automatically_ be installed for developers. They'll need to force the upgrade in order to take advantage of it. While I haven't confirmed myself, the following command _should_ upgrade the template in-place, provided one has previously run `make all` (so that the repo config and pubkey are in place):

```
sudo qubes-dom0-update --action=upgrade qubes-template-securedrop-workstation
```

**Comment by conorsch** [comment]
Moving to "ready for review" to give team members a chance to test the upgrade-in-place command above. Fine to close, as the work described here is complete.

**Comment by emkll** [comment]
Thanks for uploading the packages, @conorsch . Unfortunately, I too was unable to upgrade RPM (and template) in place using `qubes-dom0-update`, even with `--enablerepo` parameter. I've opened #302 to track this issue.

Otherwise, `make clean` and removal of all templates, and provisioning using the new template works as expected.
