### ISSUE TITLE
Finalize export metadata format

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#280]
#259 implemented a basic, manual export workflow and specified (in the README) a metadata format for exports:

```
.
├── metadata.json
└── export_data
    ├── file-to-export-1.txt
    ├── file-to-export-2.pdf
    ├── file-to-export-3.doc
    [...]
```

metadata.json example:

```
{
  "encryption-method": "luks"
  "encryption-key": "Your encryption passhrase goes here"
}
```

Before we implement export support in the client (https://github.com/freedomofpress/securedrop-client/issues/21) we should be sure that this is the format specification we want to go with. For example, is there other information we want to include in the metadata or folder structure (e.g., source name, date/time of export)?

**Comment by eloquence** [comment]
It may be worth comparing this approach with the ZIP folder structure generated by downloads from the Journalist Interface, which looks like this:

```
all
├── recessive accreditation
│   ├── 1_2019-07-07
│   │   └── 1-recessive_accreditation-msg.gpg
│   └── 2_2019-07-07
│       └── 2-recessive_accreditation-msg.gpg
└── surviving authentication
    ├── 1_2019-07-07
    │   └── 1-surviving_authentication-doc.gz.gpg
    └── 2_2019-07-07
        └── 2-surviving_authentication-msg.gpg
```

The date used for the folders is the "last updated" date for a given source (https://github.com/freedomofpress/securedrop/blob/develop/securedrop/store.py#L137).

**Comment by eloquence** [comment]
See also the related issue of handling filename conflicts: #270

**Comment by emkll** [comment]
A draft of the metadata archive format specification can be found in the following document https://docs.google.com/document/d/1qoQMMGjB9d9mHelZg_lncgiMjjB1BxIvZot_2Y6KjqM for discussion as part of the 7/24-8/7 sprint.

**Comment by creviera** [comment]
@emkll I gave the google doc a first pass review and left a few comments and some suggestions.

**Comment by redshiftzero** [comment]
also dropped some comments inline, otherwise LGTM!

**Comment by emkll** [comment]
Thanks @creviera and @redshiftzero for the comments/suggestions, they have all been addressed/accepted, and they should now be consistent with the changes in https://github.com/freedomofpress/securedrop-export/pull/5 . I think this should now be sufficient to close the ticket. If anyone disagrees, please feel free to repoen/comment.
