### ISSUE TITLE
Can no longer log into SecureDrop Client

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-workstation#284]
## Description

Last week I decided to switch my Qubes workstation from using my staging server vms, which I run on my development machine (very convenient way to have full control over the servers and for testing the client in Qubes), to the SF servers. This required an update to `config.json`, running `make all`, which had several iterations of errors and eventually required that I delete all the sd template vms and do a `make clean && make all`. This took several hours to complete (and that was just for one run). Sometimes it's hard to know whether or not there was an error, so I ran `make all` again and saw it complete successfully (i think) skipping all the tasks that were already completed.

The first time I set up Qubes to work with the staging servers, I modified `sd-svs` so that it could have access to the internet (FOR DEVELOPMENT ONLY) so I could get the client and test run it. I might have made more modifications than this to the vm, but I can't remember. 

This time, after getting the client setup with its dependencies in `sd-svs`, I ran the client and saw a timeout error in the logs when I tried to log in. I also get a timeout error when I run the client installed via apt. I get a different error when I  try runinng the client from `sd-dev` (seeing this error message in the logs https://github.com/freedomofpress/securedrop-sdk/blob/b78636f62f91d2382625d8cfc25ec3266b6211dd/sdclientapi/__init__.py#L200).

Some things that make me think that something went wrong during `make all`:

 * I had to manually add the onion address for the journalist interface to the `sd-whonix` vm's tor config.

 * I ran the Anon connection wizard for both `sd-whonix` and `sys-whonix`, selecting the "Connect" option.  I verified that `torify curl <journalist_interface.onion>` works. I'm able to log into the SF journalist interface using Tor Browser from `sd-proxy`. I'm not 100% sure this wasn't working originally, but `make all` was stuck on the step that outputs the line: "sd-whonix:" so we wanted to make sure this was set up corrrectly.

* I also had to manually update `/etc/sd-proxy.yaml` in sd-proxy, which had an old onion address still.

Even after all this, I cannot get to the journalist interface via the SecureDrop Client.

**Comment by conorsch** [comment]
@creviera Is the problem as described above still affecting you? Subsequent runs of `make all` _should_ enforce the connection settings declared in `config.json`, provided they were fetched to dom0 via `make clone`. In certain instances, you may need to restart VMs for them to take effect.

**Comment by creviera** [comment]
I think the problem was that I had some wrong configuration files and some vms that were never re-provisioned. Now that I've done this a few times and have become more organized with my config files and onion urls, I'm able to switch between servers smoothly, and it takes about 10 minutes each time.

Thanks everyone for the help! Closing this ticket now.
