### ISSUE TITLE
Allow securedrop-workstation template in-place upgrades via qubes-dom0-update

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#302]
The SecureDrop workstation ships a base template based on Debian-9 that contains the grsec-hardened kernel.

In https://github.com/freedomofpress/securedrop-workstation/issues/275 , we provided an updated template containing new kernels and upgraded packages. However, `sudo qubes-dom0-update --action=upgrade qubes-template-securedrop-workstation` did not upgrade the template directly in dom0. The template had to be removed and reinstalled in order to use the latest version. Note that the all templates are automatically updated via apt via a daily cron in dom0.

The `version` field did not change from one template to another, but the `release` field is different (build date). 

Investigation work is required to understand why these templates don't update in place, and if the versions need to be bumped or additional metadata is needed in the rpm repo.

**Comment by gonzalo-bulnes** [comment]
2022-08 Closing as stale since it hasn't been reproduced.
