### ISSUE TITLE
use split-gpg for dev env

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-workstation#303]
## Description

Update docs once how we want to move forward with https://github.com/freedomofpress/securedrop-client/issues/497

#### Background

The developer environment on Qubes does not use `split-gpg`. Instead it uses a development gpg private key inside a gpg keychain that is stored in the temporary configuration directories. This is also how it works in a non-Qubes environment.

It might make sense to use `split-gpg` with the key configured in the `sd-gpg` AppVM instead. This could make it easier to maintain (perhaps not if we still have to maintain the dev key and setup code for non-Qubes development) and also to understand the differences between running `python -m securedrop_client` with proxy vs `./run.sh` without proxy. The only difference should be whether or not we use the `securedrop-proxy` RPC service and Tor is used.

**Comment by gonzalo-bulnes** [comment]
Covered by existing docs on setting up development environments.
