### ISSUE TITLE
`make all` hangs after sd-gpg-import-submission-key step

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#336]
`make all` hanging, network was fine, no CPU usage.

This was for a from-scratch November 10 build from `master` at the time; I later re-ran `make all` from the same commit and it succeeded. Will debug further if I encounter it again.
![Screenshot_2019-11-10_19-20-39](https://user-images.githubusercontent.com/213636/68882669-a4c2f280-06dd-11ea-95f3-a7ed8e35024d.png)

**Comment by conorsch** [comment]
Any time you encounter a hang during provisioning, check the logs in dom0 at:

* `/var/log/xen/console/guest-<vm_name>.log`
* `/var/log/xen/console/guest-disp-mgmt-<vm_name>.log`

and see if that sheds any light on the problem. I also typically open a shell in the target VM and run `sudo ps aux | grep -P (dpkg|apt)` to check if there are any active package installs that could be holding things up. The package installation is unlikely the culprit for the `sd-gpg` hang you mention, but still worth checking.

**Comment by emkll** [comment]
From the screenshot, it appears the gpg import completed successfully (return code 0). The hanging issue you describe is likely due to another step. Other useful information to debug is to see what management vms are running at the time (these are disposable VMs used by qubes for salt provisioning), you can do so by running `sudo xentop` in dom0.

**Comment by conorsch** [comment]
Encountered this today. Agree with @emkll that `sd-gpg` config completed successfully; the "hung" task hasn't yet printed to stdout, so the terminal output is showing the most recent successful task. 

For me, it was `sd-svs`. Next time someone encounters this, check for results such as:

```
[root@dom0 ~]# grep -rF 'INFO: task xenbus:25 blocked for more than 120 seconds' /var/log/xen/console/*.log
/var/log/xen/console/guest-sd-svs.log:[  242.656401] INFO: task xenbus:25 blocked for more than 120 seconds.
/var/log/xen/console/guest-sd-svs.log:[  363.488192] INFO: task xenbus:25 blocked for more than 120 seconds.
/var/log/xen/console/guest-sd-svs.log:[  484.320251] INFO: task xenbus:25 blocked for more than 120 seconds.
/var/log/xen/console/guest-sd-svs.log:[  605.152115] INFO: task xenbus:25 blocked for more than 120 seconds.
/var/log/xen/console/guest-sd-svs.log:[  725.984248] INFO: task xenbus:25 blocked for more than 120 seconds.
/var/log/xen/console/guest-sd-svs.log:[  846.816223] INFO: task xenbus:25 blocked for more than 120 seconds.
/var/log/xen/console/guest-sd-svs.log:[  967.648067] INFO: task xenbus:25 blocked for more than 120 seconds.
/var/log/xen/console/guest-sd-svs.log:[ 1088.480122] INFO: task xenbus:25 blocked for more than 120 seconds.
/var/log/xen/console/guest-sd-svs.log:[ 1209.312067] INFO: task xenbus:25 blocked for more than 120 seconds.
/var/log/xen/console/guest-sd-svs.log:[ 1330.144166] INFO: task xenbus:25 blocked for more than 120 seconds.
```

I wasn't able to open a terminal in `sd-svs` to debug interactively.

**Comment by eloquence** [comment]
Has been a while since anyone reported this during `make all` (never reported during prod install), so marking for closing soon.

**Comment by eloquence** [comment]
Closing as no further repros.
