### ISSUE TITLE
fedora VMs fail to upgrade: unrecognized arguments: --dist_upgrade

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#339]
## STR:

Run `sudo /etc/cron.daily/securedrop-update` in `dom0`

## Expected behavior:

Al VMs are updated

## Actual behavior:

Output looks like this:

```
fedora-30: OK
fedora-29: ERROR (exit code 20, details in /var/log/qubes/mgmt-fedora-29.log)
sd-proxy-template: OK
sd-export-template: OK
whonix-gw-14: OK
whonix-gw-15: OK
sd-svs-disp-template: OK
fedora-30: ERROR (exit code 20, details in /var/log/qubes/mgmt-fedora-30.log)
debian-9: ERROR (exit code 20, details in /var/log/qubes/mgmt-debian-9.log)
...
```

The fedora logs show "dnf upgrade: error: unrecognized arguments: --dist_upgrade"

**Comment by eloquence** [comment]
(Note the "fedora-30: OK" entry at the top, followed by an error for the same VM later)

**Comment by eloquence** [comment]
Incidentally, the Debian error appears tobe unrelated:

```
Error running 'pkg.upgrade': E: The repository 'https://deb.debian.org/debian jessie-backports 
Release' does no longer have a Release file.
```

**Comment by creviera** [comment]
i see this too

**Comment by conorsch** [comment]
Rather than running dist-upgrade specifically, we should be reusing the `upgrade.qubes-vm` Salt SLS, maintained by the Qubes team. That state file is smart enough to handle differences between Debian/Fedora intelligently, _and_ it ensures CVE patches, e.g. #249.
