### ISSUE TITLE
RPM key script appends same line to end of rc.local

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#347]
I have observed by rc.local file in sys-firewall containing a large number of repeated entries: 
```
[...]
/rw/config/sd-copy-rpm-repo-pubkey.sh
/rw/config/sd-copy-rpm-repo-pubkey.sh
/rw/config/sd-copy-rpm-repo-pubkey.sh
/rw/config/sd-copy-rpm-repo-pubkey.sh
/rw/config/sd-copy-rpm-repo-pubkey.sh
/rw/config/sd-copy-rpm-repo-pubkey.sh
/rw/config/sd-copy-rpm-repo-pubkey.sh[user@sys-firewall ~]$ 
```
This is because the `file.line` mode is set to `insert` in [0] . Per the salt docs [1], `ensure` might be a better fit here to prevent multiple entries. 

[0] : https://github.com/freedomofpress/securedrop-workstation/blob/28e3f42cebb5853b2e845436129dab406b95f660/dom0/sd-sys-firewall-files.sls#L17:L23

[1] : https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.line

**Comment by conorsch** [comment]
Good catch, @emkll, definitely should be cleaned up. Looks like [file.append](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.append) may suffice, as we already use that elsewhere: https://github.com/freedomofpress/securedrop-workstation/blob/e63773d059c97f9d9d712ac38593591c31cc4bc0/dom0/sd-whonix-hidserv-key.sls#L6-L10
