### ISSUE TITLE
High-level docs reorg: Getting Started

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#35]
The README should be broken up into sections targeting the major use cases of this repo. At present, those are developers trying to do one of two things:

* Try it out, meaning use a Qubes workstation to run the SecureDrop Workstation environment.
* Explore diagrams to understand how the system works and what the motivation is for building it.

Two breakout sections would map well to the above use cases:

* Getting started
* How it works

We should resolve #33 before taking action here.

**Comment by eloquence** [comment]
The README looks nothing like it did when this was filed and we have https://workstation.securedrop.org/ for end user docs now, so closing - more organizational improvements always welcome.
