### ISSUE TITLE
Document VM template changes for Qubes 4

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#36]
The documentation recommends altering VM templates to support testing repos:

> Open a shell on your Fedora 25 template and run [...] and in your Debian template VM [...]

What's the procedure for doing this in Qubes 4? The VM manager that was present in Qubes 3.2 has been removed in Qubes 4. We should update the documentation with clear instructions on steps necessary.

**Comment by adrelanos** [comment]
Due to popular request, Qubes VM Manager (QVMM) is back in Qubes R4.

**Comment by eloquence** [comment]
This issue is outdated and refers to documentation that no longer exists. We do have detailed docs now in https://workstation.securedrop.org/ , including for complex changes like upgrading templates to `fedora-31`: https://workstation.securedrop.org/en/stable/admin/upgrading_to_fedora_31.html
