### ISSUE TITLE
App menu for sd-svs fails to sync

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#365]
On an install from latest `master`, I am unable to add the SecureDrop Client to the application menu. Clicking "Refresh Application" results in an error:

>Command '['qvm-sync-appmenus','vmname'] returned non-zero exit status 1.

On dom0, running `qvm-sync-appmenus sd-svs` I get:

>  FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/qubes-appmenus/qubes-start.desktop'

**Comment by eloquence** [comment]
This was partially resolved after recent `make all` runs - the "SecureDrop Client" application now appears in the list again. However, the "Refresh Applications" button still returns the same error. Unsure if this is a regression since I only clicked it to fix the earlier problem.

**Comment by redshiftzero** [comment]
might be upstream: https://github.com/QubesOS/qubes-issues/issues/5296

**Comment by eloquence** [comment]
On recent builds I do not see the "SecureDrop Client" application menu entry, and the sync error still exists. It looks like the upstream fix is currently in testing for 4.1.

Arguably, now that we want users to launch the preflight updater instead of the client directly, we don't want it to appear in the menu. Are there proactive changes we should make to _prevent_ it from appearing in the app menu?

**Comment by eloquence** [comment]
Since we want the user to launch the app via the desktop icon, we currently do not need to track this. As far as the user circumventing the launcher, there are many ways they could do so or otherwise mess with the default config, so I don't think it's worth being particularly concerned about the app menu in that regard.
