### ISSUE TITLE
Investigate make all errors with sd-proxy

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#366]
Initially reported by @kushaldas in https://github.com/freedomofpress/securedrop-workstation/pull/358#issuecomment-564517762

We should insure make all properly provisions VMs and make tests are passing.

I suspect the issue is with the template update not being applied to the AppVM, and both TemplateVM/AppVM need reboot, either during or after the install.

**Comment by eloquence** [comment]
Outdated test failures, closing.
