### ISSUE TITLE
Whonix 15 template adds glitchy, duplicate sdwdate-gui

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#369]
As of the Whonix 15 upgrade, I see the following two icons in the tray (shown with context menu expanded):

![Screenshot_2019-12-12_01-54-44](https://user-images.githubusercontent.com/213636/70689918-5f58fd00-1c6a-11ea-8253-0abbb5e0aeab.png)
![Screenshot_2019-12-12_01-55-19](https://user-images.githubusercontent.com/213636/70689919-5ff19380-1c6a-11ea-8d18-68b2ed3ec92a.png)

This is [sdwdate-gui](https://github.com/troubadoour/sdwdate-gui) which is [part of Whonix 15](https://phabricator.whonix.org/T300). 

Since it appears to be capable of managing more than one VM, it would be ideal if we can de-duplicate it so that only a single icon is displayed. In my build I am also noticing issues with the icon being glitchy -- you may be able to make out some visual artifacts in the screenshot above. The more I interact with the widget, the glitchier it gets. This may be an upstream issue, in which case it would be good to track it.

**Comment by emkll** [comment]
After merging https://github.com/freedomofpress/securedrop-workstation/pull/387 : (and disabling `qubes.getDate` policy outbound), there is now one widget per-vm (the sd-proxy widget will no longer work on the sys-whonix widget). This helps with consistency.

If we want to de-duplicate is to allow qubes.getDate inbound for one of these VMs and disable the widget.

**Comment by eloquence** [comment]
Upstream Qubes issue for the icon glitchiness: https://github.com/QubesOS/qubes-issues/issues/5653

**Comment by adrelanos** [comment]
> Upstream Qubes issue for the icon glitchiness: [QubesOS/qubes-issues#5704](https://github.com/QubesOS/qubes-issues/issues/5704)

Icon glitchiness was fixed upstream by Qubes.

**Comment by eloquence** [comment]
It was indeed, though hasn't landed in 4.0 yet; will close if the fix indeed ported to 4.0.

**Comment by eloquence** [comment]
The glitchiness has been gone for a while and there's a new icon now (the Whonix logo). The duplication is still something we may want to visit, but may be rendered moot with template consolidation (#471).
