### ISSUE TITLE
Code signing / verification

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#37]
As a Qubes Workstation user, I do not want to execute malicious code in `dom0`.

Provide a way for a user to validate the integrity of the `securedrop-workstation` code. This could be achieved through:

- Sign tags/releases with using GitHub
- Building (signed) packages

**Comment by conorsch** [comment]
In the meantime, all developers should also be signing git commits.

**Comment by conorsch** [comment]
At present we plan to ship updates via two mechanisms:

* Signed RPMs for installation in `dom0`
* Debian packages for installation in Template- and AppVMs, where the Release file is signed in the apt repository

For the alpha, we'll continue using a "test" GPG key that's shared among several developers, to increase velocity. Before moving into prod deployments, we'll revisit the signing workflow to discuss the transition to the SecureDrop Release Signing Key.

**Comment by eloquence** [comment]
In addition to the use of the test key, for the purposes of the alpha, we have agreed to document the signed tags across all relevant repositories that constitute the alpha release.

**Comment by emkll** [comment]
### Signing sources

SecureDrop Workstation code spans across the following repositories:

https://github.com/freedomofpress/securedrop-client
https://github.com/freedomofpress/securedrop-debian-packaging
https://github.com/freedomofpress/securedrop-proxy
https://github.com/freedomofpress/securedrop-sdk
https://github.com/freedomofpress/securedrop-workstation
https://github.com/freedomofpress/qubes-template-securedrop-workstation


#### Release
1. For each release, a tag will be signed in all the above repos.

2. We should track a Makefile target in securedrop-debian-packaging repo that contains release tags for each repository(and each release will have a tag in securedrop-debian-packaging repo). This script validates the tag signature, pulls down tag and builds debs for that given tag (including metapackages securedrop-workstation and securedrop-workstation-grsec for the template).

3. Metadata (e.g. commit hash for release) should be tracked inside the .deb  @kushaldas suggested in `/usr/share/packagename/release-info.txt`

### Signing binaries/packages

#### debs
Apt-(test-)qubes.freedom.press Release file signed containing checksum of the debs, in the same way it is done for SecureDrop.

#### rpms
The entire RPM must be signed themselves must be signed. This process also requires a Fedora machine/VM (looks like it was packaged in jessie (EOL), but not in stretch). Finally, the private key must be set up in the vault vm (with or without smartcard)

`rpm -Kv` indicates if digests and sigs are OK. Before signature it should not return signature, and `rpm -qi <file>.rpm` will indicate an empty Signature field.

To sign RPMS:
`sudo dnf install rpm-build /usr/bin/rpmsign`
Set your vault vm in /rw/config/gpg-split-domain
Edit ~/.rpmmacros with the following contents:
```
%_signature gpg
%_gpg_name <gpg_key_id>
%__gpg /usr/bin/qubes-gpg-client-wrapper
%__gpg_sign_cmd %{__gpg} qubes-gpg-client-wrapper --no-verbose --detach-sign %{__plaintext_filename} --output %{__signature_filename}
```
Sign the rpm:
`rpm --resign <rpm>.rpm` (--addsign would allow us to apply multiple signatures to the RPM)
Verify that the rpm is signed:
`rpm -qi<file.rpm>` should now show that the file is signed
`rpm -Kv` will complain that signature is not ok (`Digests SIGNATURES NOT OK`)
This is because the rpm key needs to be added locally:
`sudo rpm --import <publicKey>.asc`
`rpm -Kv` will now say signatures are ok (`Digests signatures OK`)


I have not yet managed to extract a file/manifest to sign in order to provide a detached signature to place into the RPM.
