### ISSUE TITLE
Provisioning of old templates can silently fail or hang on make all

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#370]
The `provision-all` script applies the state to all VMs tagged sd-workstation: https://github.com/freedomofpress/securedrop-workstation/blob/e999834fed9f7b47a865f43b63801e91683b7a88/scripts/provision-all#L22

Because we do not remove the securedrop-workstation-template (the FPF-created Stretch-based template) after installing/using our securedrop-workstation-buster-template, the install can hang/fail as the state is being applied to that TemplateVM. We could either:

- remove the securedrop-workstation-template (the Stretch one) (via dom0 rpm)
- remove the `sd-workstation` tag on securedrop-workstation-template
- replace the `sd-workstation` tag (e.g. sd-workstation-old)  on securedrop-workstation-template

(related to #361)

**Comment by conorsch** [comment]
Let's remove it. It's already no longer requested for installation, and there's no state in it, given that it's a TemplateVM.
