### ISSUE TITLE
tinyproxy in whonix-ws-15 is failing to start

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop-workstation#377]
```
● tinyproxy.service - Tinyproxy lightweight HTTP Proxy
   Loaded: loaded (/lib/systemd/system/tinyproxy.service; enabled; vendor preset: enabled)
  Drop-In: /usr/lib/systemd/system/tinyproxy.service.d
           └─30_not_needed_in_qubes_by_default.conf
   Active: inactive (dead)
Condition: start condition failed at Mon 2019-12-16 05:47:40 UTC; 2s ago
           └─ ConditionPathExists=/var/run/qubes-service/tinyproxy was not met
     Docs: man:tinyproxy(8)
           man:tinyproxy.conf(5)

Dec 13 15:26:20 host systemd[1]: Condition check resulted in Tinyproxy lightweight HTTP Proxy being skipped.
Dec 16 05:47:40 host systemd[1]: Condition check resulted in Tinyproxy lightweight HTTP Proxy being skipped.
```

This is causing all apt commands to fail.  This is propagating to `sd-proxy-template` too.

**Comment by kushaldas** [comment]
I manually touched the `/var/run/qubes-service/tinyproxy` file, the service is up after that. I still don't understand if it is required. Restarted the `sys-whonix` vm a few times and tested network on it, now apt seems to be working.

**Comment by adrelanos** [comment]
I don't remember the details of this anymore.
https://github.com/QubesOS/qubes-issues/issues/1401

Maybye something in Qubes source code should be creating `/var/run/qubes-service/tinyproxy` and the question is why it does not do that anymore.

Or more likely `/lib/systemd/system/qubes-updates-proxy.service` starts tinyproxy. Then the question is why `/var/run/qubes-service/qubes-updates-proxy` does not exist. Which code is responsible for creation of `/var/run/qubes-service/qubes-updates-proxy` and why does this not happen anymore?

**Comment by adrelanos** [comment]
debian-10:

    sudo systemctl status qubes-updates-proxy
```
● qubes-updates-proxy.service - Qubes updates proxy (tinyproxy)
   Loaded: loaded (/lib/systemd/system/qubes-updates-proxy.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Tue 2020-02-11 05:31:31 EST; 20min ago

Feb 11 05:31:31 debian-buster systemd[1]: Condition check resulted in Qubes updates proxy (tinyproxy) being skipped.
```

----

tinyproxy.service runs neither in sys-whonix nor debian-10 nor in whonix-ws-15. OK.

qubes-updates-proxy.service runs neither in debian-10 nor in whonix-ws-15. OK.

qubes-updates-proxy.service runs in sys-whonix. OK.

----

sys-whonix:

    sudo systemctl status qubes-updates-proxy-forwarder.socket 

```
● qubes-updates-proxy-forwarder.socket - Forward connection to updates proxy over Qubes RPC
   Loaded: loaded (/lib/systemd/system/qubes-updates-proxy-forwarder.socket; enabled; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Tue 2020-02-11 10:23:04 UTC; 33min ago
           └─ ConditionPathExists=/var/run/qubes-service/updates-proxy-setup was not met
   Listen: 127.0.0.1:8082 (Stream)
 Accepted: 0; Connected: 0;

Feb 11 10:23:04 host systemd[1]: Condition check resulted in Forward connection to updates proxy over Qubes RPC being skipped.
```

qubes-updates-proxy-forwarder.socket does not run in sys-whonix. OK.

qubes-updates-proxy-forwarder.socket runs in debian-10 and in sys-whonix. OK.

----

Hope that helps to debug this.

> This is causing all apt commands to fail.

Therefore we can question the premise that `tinyproxy.service` is related to APT failing. If you post specific APT errors, I might be able to help more.

**Comment by eloquence** [comment]
Old failure with no reported repros, closing.
