### ISSUE TITLE
Old Salt files can conflict with new `make dev` run

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#380]
On a Whonix 14 system, running `make all` failed with "Recursive requisite found", specifically reporting issues with the IDs `anon-whonix`, `sys-whonix-template-config`, `whonix-ws-15-dvm`, and `qvm-appmenus --update whonix-ws-15-dvm`. Full logs here: 

https://gist.github.com/eloquence/38eaadfe38c17a590aa5912c74bc10b0

After poking around at issues with Whonix updates, I re-ran the relevant Salt state with `sudo qubesctl state.sls qvm.anon-whonix`. This produced the output logged here:

https://gist.github.com/eloquence/3b4332f935d076620949a6b2e40d4ca1

After this command, a `make clean && make all` run completed without error.

**Comment by emkll** [comment]
It seems like a salt file in your `/srv/salt` directory was conflicting with the latest changes introduced in master. Our `make all` target does not clean salt prior to running https://github.com/freedomofpress/securedrop-workstation/blob/master/Makefile#L10 . Perhaps calling `clean-salt` prior to `prep-salt` might resolve here.

We should also consider a sd-specific folder in `/srv/salt/` to ensure reliability of salt cleanup.

**Comment by eloquence** [comment]
The suggestion to run `clean-salt` prior to `prep-salt` is tracked in #434, so closing this specific report that is likely just a symptom of the issue.
