### ISSUE TITLE
set management_dispvm property on a per VM basis

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-workstation#382]
Regardless of how #373 is resolved, I think we should set the `management_dispvm` property on each VM we're using for SecureDrop. This will ensure that we are using a management VM based on a template that we know will get frequent updates, i.e. the same one we are using for sys-net and sys-firewall, and thus will have predictable state. Otherwise, the template may remain in the state it was in at the time of install, leading to increasing drift as a function of time which may in turn lead to unpredictable behavior. Using `qubes-prefs` to set the management VM globally is also a fine approach.

**Comment by conorsch** [comment]
We started doing this in https://github.com/freedomofpress/securedrop-workstation/pull/383/files#diff-dd42a9973187dd9e366e59ea79e71ac9R30. We don't alter `qubes-prefs management_dispvm`, we leave that at `default-mgmt-dvm`, but we set the template for `default-mgmt-dvm` to be whatever the currently supported (by SDW) version of Fedora is.
