### ISSUE TITLE
document memory requirements for provisioning

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-workstation#386]
We should recommend a minimum 16 GB of memory for using the SD workstation. We would ideally automate this check (ref https://github.com/freedomofpress/securedrop-workstation/pull/383#issuecomment-567395723) but for now at least documenting it in the readme would be wise.

**Comment by eloquence** [comment]
Requirements have since been added both to the README and to the install guide.

https://workstation.securedrop.org/en/stable/admin/install.html
