### ISSUE TITLE
use securedrop.Log service in all workstation subcomponents

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-workstation#398]
blocked on https://github.com/freedomofpress/securedrop-log/issues/7

Once we decide on the method of actually using the logging qrexec service in each VM (python logging handler versus something else), we should use it to send log messages from securedrop-proxy, securedrop-export, securedrop-client to the sd-log AppVM

**Comment by eloquence** [comment]
(Promoted to release blocker per previous discussion)

**Comment by kushaldas** [comment]
proxy, client, and export now has logging to `rsyslog` enabled.
