### ISSUE TITLE
Create release management guide

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#400]
For prod workstation releases, we need to create an RM guide that covers all steps of the process, similar to the one we have for SecureDrop Core:

https://docs.securedrop.org/en/release-1.2.0/development/release_management.html

**Comment by redshiftzero** [comment]
wip is here (FPF staff only can edit): https://docs.google.com/document/d/1CWVPIuX3SbWUHoE-q6-Y09GLpq3SspaLejvp2blrv24/edit#
