### ISSUE TITLE
Skip VM updates if last check was performed <X hours ago

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#402]
The launcher app currently checks for updates every single time, which can take a while. It would be good to skip this step if it has been performed very recently.

Open questions:
- Should the launcher GUI be shown to the user at all in this case, or be bypassed entirely?
- What is the maximum amount of time that may pass without checking for updates again?

**Comment by eloquence** [comment]
>  Should the launcher GUI be shown to the user at all in this case, or be bypassed entirely?

I would vote to bypass the GUI entirely in this case, and to immediately launch the client instead.

**Comment by eloquence** [comment]
Nominating as beta requirement as we don't want users to have to wait several minutes if they need to restart the client for any reason during a single session.

**Comment by eloquence** [comment]
In addition to the "client restart" scenario, we currently run the "check for updates" on reboots as well, which means that the dom0 updates take especially long to go through.

**Comment by zenmonkeykstop** [comment]
So reqs for this are:
- If updater has run within N hours, don't show GUI but go straight to client
- If system has been rebooted by updater, don't show GUI but go straight to client
- Otherwise, show GUI

Also adding:
- In either of the first two cases, log the no-GUI start.

**Comment by emkll** [comment]
Yes that seems correct @zenmonkeykstop:

- read timestamp in `sdw_last_updated` flag from `~/.securedrop-launcher`
- if  `sdw_last_updated` < 8h and `last_required_reboot_performed()` [1]: start client
- else show launcher

[1] https://github.com/freedomofpress/securedrop-workstation/blob/master/launcher/sdw_updater_gui/Updater.py#L292

**Comment by zenmonkeykstop** [comment]
OK, adding an update_skip_delta value (in sec) in config.json, and a "--update-delta" (positive) integer arg to the launcher with Salt setting it appropriately.

Behavior will be:
- if reload flag is set, clear reload flag and skip update check
- if reload flag not set, `--update_delta` not set or = 0, skip update check
- if reload flag not set, `--update_delta` is set and > 0,  and if `sdw_last_updated - now > update_delta`, do update check
