### ISSUE TITLE
Perform update checks concurrently

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#403]
On my system (3rd gen X1 Carbon), the "Checking for workstation updates" stage currently takes about 4 minutes, even when no updates are available (I stopwatched it). That's a long time to ask a journalist to wait before being able to use the client. It would be good to find ways to get this number down. A concurrency of 2 or greater has been suggested to improve update performance.

**Comment by zenmonkeykstop** [comment]
Deferring to upstream changes in the Qubes updater.
