### ISSUE TITLE
Update dataflow diagram with latest VM names

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#408]
VM names were updated in https://github.com/freedomofpress/securedrop-workstation/pull/407 . We should update the dataflow diagram to ensure the names of the VMs are up-to-date. 

The diagram source can be found in https://github.com/freedomofpress/securedrop-workstation/blob/master/docs/images/data-flow-diagram.draw
The png version https://github.com/freedomofpress/securedrop-workstation/blob/master/docs/images/data-flow-diagram.png should also be updated.

**Comment by eloquence** [comment]
I'll take care of these edits.
