### ISSUE TITLE
USB device error: re-attaching LUKS-encrypted drive fails, must kill sys-usb and target VM

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-workstation#426]
Documenting this here even though I believe it is a Qubes upstream issue because it may come up as a support issue.  Also needs a bit more investigation to determine exactly how to repro consistently.

When attaching and then detaching a USB drive, sometimes I encounter a state where the device cannot be re-attached to the same VM, or to any other VMs, and the GUI/USB widget reports that a device is attached to a target VM, but `sudo fdisk -l` in that VM does not see the device. Even when "removed" (detached and physically removed), the device cannot be re-attached VM unless I kill and restart both `sys-usb` and the target VM.  
 
Sometimes, the device is simultaneously displayed as mounted/unlocked and encrypted [screenshot 1], and is also displayed simultaneously at different mount points (eg `xvdi` and `xvdj`) [screenshots 2 onward]. The 'operation pending' is never completed [2].  Sometimes, I will also see the `empty response from qubesd` error notification, as mentioned in https://github.com/QubesOS/qubes-issues/issues/4784.   

I think I need to do some more testing to isolate what is happening here. @zenmonkeykstop  reports having experienced something similar, and also having to kill vms from dom0 console in order to get back to workable state.

![schroedinger_transfer_device](https://user-images.githubusercontent.com/22777700/73004511-70eb0400-3dd5-11ea-8a1e-2e4f8014edf8.png)
![schroedinger_device_2](https://user-images.githubusercontent.com/22777700/73004508-70eb0400-3dd5-11ea-85c8-bab5d26d241d.png)
![schroedinger_device_3](https://user-images.githubusercontent.com/22777700/73004509-70eb0400-3dd5-11ea-99a1-4852e68a849f.png)
![schroedinger_device_4](https://user-images.githubusercontent.com/22777700/73004510-70eb0400-3dd5-11ea-892f-4c5db8970bea.png)

(Possibly) Related: 
https://github.com/QubesOS/qubes-issues/issues/4784 
https://github.com/QubesOS/qubes-issues/issues/2616
https://github.com/QubesOS/qubes-issues/issues/2094
https://github.com/QubesOS/qubes-issues/issues/5047

**Comment by eloquence** [comment]
Update from 2022-08-11 review with @tina-ux @nathandyer @l3th3 @eloquence:
- Further investigation/repro required, labeled accordingly.
- @rocodes Have you seen this issue recently on Qubes 4.1?

**Comment by rocodes** [comment]
Have not seen this issue recently, think it's fair to close and reopen only if we encounter this again
