### ISSUE TITLE
`make clean` does not reliably kill sd-proxy

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#429]
I routinely see output like this from `make clean`: 

```
Destroying VM 'sd-devices'... OK
Destroying VM 'sd-app'... OK
Destroying VM 'sd-devices-dvm'... OK
Destroying VM 'sd-gpg'... OK
Destroying VM 'sd-log'... OK
qvm-remove: error: Domain is not powered off: 'sd-proxy'
Destroying VM 'sd-proxy'... Traceback (most recent call last):
  File "./scripts/destroy-vm", line 78, in <module>
    destroy_all()
  File "./scripts/destroy-vm", line 68, in destroy_all
    destroy_vm(vm)
  File "./scripts/destroy-vm", line 46, in destroy_vm
    subprocess.check_call(["qvm-remove", "-f", vm.name])
  File "/usr/lib64/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['qvm-remove', '-f', 'sd-proxy']' returned non-zero exit status 1
Makefile:130: recipe for target 'destroy-all' failed
make[1]: *** [destroy-all] Error 1
make[1]: Leaving directory '/home/erik/securedrop-workstation'
Makefile:89: recipe for target 'clean' failed
make: *** [clean] Error 2
```

`qvm-kill sd-proxy` in `dom0` resolves, but it looks like https://github.com/freedomofpress/securedrop-workstation/blob/master/scripts/destroy-vm is trying to do the same thing but not succeeding for some reason.

**Comment by conorsch** [comment]
Nearly daily, I run the following command locally to shut down all the SDW VMs, when switching to work on a different project:

```
qvm-ls --tags sd-workstation --raw-list | xargs qvm-shutdown --wait
```

Rather recently—within the past week or so—the command just started complaining about the sd-proxy shutdown not working. See screenshot:

![sd-proxy-still-running-why](https://user-images.githubusercontent.com/657862/73030583-d3043300-3dee-11ea-9fa0-9682f68f7d48.png)

Can't say with certainty that an upstream change in tooling is causing this, but I can certainly verify I'm seeing similar behavior of late.

**Comment by eloquence** [comment]
Update from 2022-08-11 review with @tina-ux @nathandyer @l3th3 @eloquence:
- Not observed in a while, closing as stale.
