### ISSUE TITLE
Feedback FIFO created with wrong file type

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#43]
This bug report only applies to the `feature/feedback` branch. 

The `sd-process-download` script was failing in the automated "feedback" workflow. Running it manually showed the following:

```
$ /usr/local/bin/sd-process-download all.zip 

(python:2121): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

[...snip...]

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/rw/usrlocal/bin/pipereader.py", line 31, in read
    poller.register(fifo)
IOError: [Errno 1] Operation not permitted

/tmp/tmpPgC2nf is still not a file
OK FOUND /tmp/tmpPgC2nf
```

The `Operation not permitted` error was the tip-off. Running `stat` on `~/myfifo` showed a regular file, when it should be a FIFO. Presumably the Salt provisioning scripts are not setting the filetype correctly, thus the error.

These steps, run manually, resolved the issue locally:

```
rm ~/myfifo
mkfifo ~/myfifo
```

Salt scripts will need to be updated to set the correct filetype on creation.

**Comment by conorsch** [comment]
Modifying `sd-journalist/sd-process-feedback` to create the FIFO if it doesn't exist would be sufficient for a quick fix. More durable would be to add a provisioning line to the Salt config, since the Salt config doesn't currently reference the FIFO at all. Will try for the latter.

**Comment by joshuathayer** [comment]
This should be handled now by a change in #40 (we build the FIFO via salt, now!)
