### ISSUE TITLE
Updater Progress Bar UI Updates

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-workstation#431]
To better manage user expectations, I'm recommending 2 things for "as we have time for them" (tho likely post-Beta) updates...
1. Animate the stripes on the progress bar, so that it displays as a rolling barber pole throughout the process. This is important for consumer-type users, who expect that when things on the screen stop moving around they are either broken or halted.
2. Instead of showing numeric percentages, display `Step 1` and do that for "steps" 1-10 (assuming there are 10 or 11 steps, based on the 10% increments it currently operates within).

My initial recc on Slack to Jen was to just kill the percentage numbers, but then I remembered Kev or Mikael saying it's helpful when troubleshooting, to know which displayed percentage things broke at. Steps 1-10 feels like a nice compromise to achieve the same goals as the percentage alpha value, but without the confusion around why it always jumps from 33% to 43% etc.

Both of these changes are being recommended, after seeing the super-sweet updater in progress, for the first time.

**Comment by eloquence** [comment]
Update from 2022-08-11 review with @tina-ux @nathandyer @l3th3 @eloquence:
- Closing as stale, we'll revisit updater UX in context of future visual identity work.
