### ISSUE TITLE
Integrate repo github alerts into gittr

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop-workstation#44]
specifically --> https://gitter.im/freedomofpress/securedrop

**Comment by msheiny** [comment]
Test making a comment.

**Comment by msheiny** [comment]
Ohhhh snappppp! its working!!!

![image](https://user-images.githubusercontent.com/1727935/34269931-54ce9384-e654-11e7-9b30-afa8ce3f3613.png)

**Comment by dachary** [comment]
You're my hero !
