### ISSUE TITLE
[UI/UX] Updater GUI shows "100%" even if updates failed

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-workstation#460]
The preflight updater gui shows a progress bar at 100%, even if updates have failed (see attached screenshot). 

This is possibly confusing from a user experience point of view, or at least, it momentarily confused me!

![updates_failed_100](https://user-images.githubusercontent.com/22777700/74769811-110f3e00-5259-11ea-9162-dfb45004eb74.png)

**Comment by eloquence** [comment]
Agreed; the progress bar in general should IMO not carry into the subsequent dialogs, but it definitely should not appear here.

**Comment by eloquence** [comment]
Update from 2022-08-11 review with @tina-ux @nathandyer @l3th3 @eloquence:
- This is not current updater behavior, closing as stale.
