### ISSUE TITLE
sdw-last-updated not created/updated after update that requires reboot

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#462]
## Steps to reproduce
1. Remove `~/.securedrop_launcher/sdw-last-updated` if it exists, or note its contents
2. Perform an update using the preflight updater that includes fedora updates and requires a reboot
3. Inspect `sdw-last-updated` (you don't have to actually reboot, but you're welcome to)

## Expected behavior

`sdw-last-updated` is up-to-date

## Actual behavior

`sdw-last-updated` is not written / stale, causing `sdw-notify` to fire again. Due to the skip logic introduced in #402, `sdw-last-updated` will not be written in the immediately subsequent run, either.

## Can I have some logs?

[Yes](https://gist.github.com/eloquence/5941ee586682e3afe3cfb2ca4833779d).

**Comment by eloquence** [comment]
There appear to be two related issues with the current updater logic:

- When we check for updates in the Fedora VM, we don't interpret the exit code -- we just treat "0" as "all good" and everything else as "problem or upgrade required". As a consequence, we don't determine whether a reboot is required until upgrades are complete. This is the `check_call` logic [here](https://github.com/freedomofpress/securedrop-workstation/blob/master/launcher/sdw_updater_gui/Updater.py#L114).

- As of #402, we write the `sdw-last-updated` file to disk if a reboot is required, but only during the "check for updates" stage. This is the `UpdateThread` logic [here](https://github.com/freedomofpress/securedrop-workstation/blob/master/launcher/sdw_updater_gui/UpdaterApp.py#L253). Note that there is no corresponding check for REBOOT_REQUIRED in the `UpgradeThread` logic [here](https://github.com/freedomofpress/securedrop-workstation/blob/master/launcher/sdw_updater_gui/UpdaterApp.py#L293).

As a consequence of this logic, we never create or update the `sdw-last-updated` file to disk in the "reboot required" case. This means `sdw-notify` will fire again even after a reboot, as it queries that file for the last successful update.

I think the easy fix is to add the REBOOT_REQUIRED check to `UpgradeThread`. I do think it would separately make sense to make the `dnf` result check smarter, so we can also detect the reboot case in the UpdateThread (exit code 100 means updates are available).

@zenmonkeykstop @emkll If that above reasoning makes sense to you, I can put in a small PR for the former and test it.

**Comment by eloquence** [comment]
Tracking as release blocker since it causes incorrect security notifications to be displayed to the user, which prevent them from focusing on their work at hand.

**Comment by zenmonkeykstop** [comment]
With a bit more explanation from @eloquence this makes sense, :+1: from me.

**Comment by eloquence** [comment]
@emkll Am I correct that this code path will never be entered?

https://github.com/freedomofpress/securedrop-workstation/blob/master/launcher/sdw_updater_gui/UpdaterApp.py#L93-L116

Near as I can tell, none of the `UpdateThreads` (as opposed to `UpgradeThreads`) will ever return `REBOOT_REQUIRED`. `_check_updates_dom0` and `_check_updates_fedora` (the ones that will trigger the reboot requirement) will return `UPDATE_REQUIRED` instead.  Only `overall_update_status` can return this result, if a reboot requirement from a prior run has not been met yet.

If that's correct, I would suggest we remove this dead code path as part of the PR that resolves this issue.

I can also see if we can move some more business logic into `Updater.py`. The 0% test coverage on `UpdaterApp.py` really worries me for complex cases like this.

**Comment by eloquence** [comment]
> If that's correct

It's not - that code path exists to handle the UI updates needed when the user restarts the updater when a reboot is still required. It gets its result from the VM status aggregation logic in `overall_update_status`, which tests whether the machine has been rebooted or not; it was added in #436. We may be able to remove that logic if we implement #457.

Therefore nothing else to do for this issue for now, marking #465 ready for review.
