### ISSUE TITLE
Consider sending dom0 logs (including launcher logs) to sd-log VM

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#463]
In https://github.com/freedomofpress/securedrop-workstation/pull/447/, we centralize logging for all workstation Debian-based AppVMs, but dom0 logs are not sent to `sd-log`, as the packaging and log forwarding mechanics may be different

We should consider forwarding dom0 logs to `sd-log` VM, either through `securedrop-log` RPC mechanism, or a Makefile target that will qvm-copy-to-vm the logs to `sd-log`

**Comment by conorsch** [comment]
If we're going to start shipping logs from dom0 into an AppVM, it's worth reconsidering the `securedrop-log` RPC architecture: AppVM syslogs _already_ land in dom0, so we could scoop those up and avoid the inter-VM connections for aggregation, instead going dom0->sd-log always. As long as app code continues to log to the AppVM's syslog, that should work.

**Comment by zenmonkeykstop** [comment]
There would be threat model implications of exporting logs from dom0, and if the main use case  is to get launcher logs in for support purposes, it might be better to allow users to see and export the logs from the updater itself in the result of a failure. Closing this ticket in favour of an issue in securedrop-updater to that effect.
