### ISSUE TITLE
`make all` fails on `run-prep-upgrade-scripts`

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#474]
Seeing cascading failures as a result of a failure on `run-prep-upgrade-scripts` in a clean `make all ` run from `master` today. It appears to be attempting to run checks in VMs that don't exist yet.

https://gist.github.com/eloquence/43ed243c787656fef610368a67c4ca19#file-make-all-output-2020-02-28-L515-L534

Exiting out from `securedrop-handle-upgrade` allowed me to complete the run.

**Comment by kushaldas** [comment]
I tried a few times, I could not reproduce this one.

**Comment by eloquence** [comment]
I've also not seen this again so closing for now until we get another report of it.
