### ISSUE TITLE
sd-whonix is calling logging qrexec while make clean

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop-workstation#477]
During `make clean` if `sd-log` gets cleanup before `sd-whonix`, there is possibility that we will get a qrexec service dialog from `dom0`. I saw it once.

## How to see the dialog (test steps)?

- [ ] `make all`
- [ ] `make clean` again and again and then you may see that.

**Comment by conorsch** [comment]
>there is possibility that we will get a qrexec service dialog from dom0

You mean a GUI notification appears? That doesn't sound particularly troublesome. Does the `clean` action still exit zero?

**Comment by conorsch** [comment]
In standup, @kushaldas explained that the "qrexec service dialog" means the interactive pop-up opened  in dom0, prompting for user input. In order to resolve, we could hardcode the order of VM removal to make sure `sd-log` is cleaned up last.

**Comment by conorsch** [comment]
Closing in preference of #536, which includes a screenshot. :sparkle:
