### ISSUE TITLE
Migrate to fedora 26 templates

### ISSUE THREAD

**Issue by joshuathayer** [freedomofpress/securedrop-workstation#48]
Fedora 25 was EOLed and Qubes has made Fedora 26 templates available. We should move any VMs off of 25 to 26.

**Comment by conorsch** [comment]
Announcement by Qubes here: https://www.qubes-os.org/news/2018/01/06/fedora-26-upgrade/ Running these commands is not onerous, but we'll need tests to confirm that F26 is active in the relevant VMs, and fail is F25 is found.

**Comment by conorsch** [comment]
Near as I can figure, the Qubes Admin API doesn't expose the base OS underlying a given app VM in a concise manner. One _can_ easily retrieve the template on which a VM is based, but that's still not the answer we want to write a pass/fail test for F25. 

Looks like we'll have to resort to parsing the contents of `/etc/os-release` on each VM and validating that against a list of permitted platforms.

**Comment by conorsch** [comment]
Performed the manual commands [described in the Qubes docs](https://www.qubes-os.org/doc/template/fedora/upgrade-25-to-26/#qubes-40-instructions) before @redshiftzero helpfully pointed out _there's a better way_: https://github.com/QubesOS/qubes-issues/issues/3499 Will ask reviewers to use that method when the PR goes up.
