### ISSUE TITLE
[prod] whonix-ws-15 and whonix-gw-15 updates failing after SecureDrop install/uninstall

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-workstation#492]
Running Qubes updater against `whonix-ws-15` or `whonix-gw-15` after install and uninstall (using RPM from #489) fails with the following error: 
```
Updating whonix-ws-15

Error on updating whonix-ws-15: Command '['sudo', 'qubesctl', '--skip-dom0', '--targets=whonix-ws-15', '--show-output', 'state.sls', 'update.qubes-vm']' returned non-zero exit status 1
whonix-ws-15: ERROR (exception [('/srv/salt/_tops/base/sd-workstation.top', '/tmp/tmppv2g52/srv/salt/_tops/base/sd-workstation.top', "[Errno 2] No such file or directory: '/srv/salt/_tops/base/sd-workstation.top'")])
```

**Comment by zenmonkeykstop** [comment]
This is related to #489 - a symlink to `/srv/salt/sd-workstation.top` isn't being removed as part of the uninstall.

**Comment by eloquence** [comment]
@zenmonkeykstop it looks like this was fixed per https://github.com/freedomofpress/securedrop-workstation/pull/489/commits/50f3cd625cb5f9bd661dacf46daa3e49a1eef6dd and your comment in https://github.com/freedomofpress/securedrop-workstation/pull/489#pullrequestreview-373158902 ?

**Comment by zenmonkeykstop** [comment]
Yep, symlink is being removed now.

**Comment by eloquence** [comment]
Closed per above.
