### ISSUE TITLE
print is not disabled for for unprintable file types.

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-workstation#508]
Currently the print option is displayed for all file types under test. File types that do not have a meaningful static 2D representation should not have a print option.

- audio and video files currently print arbitrary numbers of blank pages
- zip and 7z files print blank pages, rar files fail silently after the user is presented with the print panel

**Comment by redshiftzero** [comment]
agreed, linking https://github.com/freedomofpress/securedrop-client/issues/918

**Comment by zenmonkeykstop** [comment]
my bad! should have checked client issue list first!
