### ISSUE TITLE
Add further explicit incoming/outgoing denials for RPC services that are not needed

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-workstation#509]
We have both incoming and outgoing deny-by-default RPC policies for almost all services and instead we whitelist only what is needed by `sd-workstation` tagged VMs. Prior to the pilot beta release, a review of the RPC policies revealed that we aren't modifying: 

- [ ] `qubes.GetDate`
- [ ] `qubes.GetImageRGBA`
- [ ] `qubes.GetRandomizedTime`
- [ ] `qubes.NotifyTools`
- [ ] `qubes.NotifyUpdates`
- [ ] `qubes.SyncAppMenus`

We should review each service and determine if any of these are not needed by `sd-workstation` tagged VMs (or a subset thereof), and if so, add explicit denials.

**Comment by eloquence** [comment]
Related: #672 for policy default when no policy file exists.

**Comment by rocodes** [comment]
Closing in favour of https://github.com/freedomofpress/securedrop-workstation/issues/672
