### ISSUE TITLE
`make all` did not update /etc/sd-proxy.yaml file with new JI url

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-workstation#512]
# STR

1. recreate your staging instance following these instructions: https://docs.securedrop.org/en/release-0.14.0/development/virtual_environments.html#staging (go ahead, it's fun!)
2. update your `config.json` file on `dom0` with the new key and url for the journalist interface
3. run `make all`
4. open `/etc/sd-proxy.yaml` on `sd-proxy`

# Excpected

for the file to contain the new url

# Actual

the previous url is still in that file and until you update it you won't be able to connect to the server from the client

**Comment by kushaldas** [comment]
@creviera did you restart the `sd-proxy` vm?

**Comment by creviera** [comment]
I did not restart `sd-proxy` during `make all` and ended up editing `/etc/sd-proxy.yml` by hand and that fixed the issue.

**Comment by conorsch** [comment]
Rebooting the AppVM (i.e. `sd-proxy`) is indeed required to get the new state from the TemplateVM (i.e. `sd-proxy-template-buster`). That's hardly ideal, @creviera, so you're right that the logic could be smarter about whether the desired state is active or not. 

In the spirit of #471, we should consider moving the proxy config into the private volume for `sd-proxy`, which would sidestep the need to reboot. For edge cases when reboots are still required, we can detect volumes out of sync, via similar logic to how the Qubes Manager UI indicates when a VM should be restarted to apply updates.

**Comment by eloquence** [comment]
The configuration was indeed moved to a private volume in https://github.com/freedomofpress/securedrop-proxy/pull/79, which sidesteps the need to reboot the VM on config changes. Closing this old issue.
