### ISSUE TITLE
Provide "make help" target

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#52]
For newcomers to the repo, it's very handle to list all Makefile targets with a friendly description of what each target does. We can make the targets self-documenting by providing structured comments, as we already do over in the SecureDrop repository: https://github.com/freedomofpress/securedrop/blob/58ab66e76f6a5fb23d8bf3d9c969f4e4d89d37d9/Makefile#L141-L147

Note that #40 and #47 both contain Makefile changes, so let's wait for those to go in before implementing the `help` target as described here, otherwise we'll be rebasing constantly to resolve conflicts.

**Comment by joshuathayer** [comment]
👍
