### ISSUE TITLE
Use RPM to manage dom0 files in all environments

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#538]
We currently have three "environments" for developing the Workstation config:

* dev - uses latest HEAD in the developer's local git repo
* staging - uses nightly RPMs built by CI
* prod - stable signed release channel

Both staging & prod use RPM logic to manage which files go where in dom0, but the "dev" scenario uses bash scripts to copy things around. Let's stop doing that, and use an RPM even for active local development. We're far more likely to catch potential packaging and provisioning errors that way, plus it'll simplify a lot of the "clean" and "provision" logic to have a single point of update.

Originally suggested in https://github.com/freedomofpress/securedrop-workstation/issues/505#issuecomment-602814288

**Comment by eloquence** [comment]
I think this duplicates #469, but that was more of a discussion issue, so if we agree on this approach (I believe we all do), I think we can close #469 and keep this one.

**Comment by conorsch** [comment]
Opened a draft PR with a partial implementation https://github.com/freedomofpress/securedrop-workstation/pull/587

While documenting errors on #505, brief discussion among the team suggested it'd be great to have this issue resolved in order to address 505 more rapidly. Also, it'd be great to land this change prior to implementation toward #471
