### ISSUE TITLE
Remove securedrop-workstation dir on dom0 as part of `make clone`

### ISSUE THREAD

**Issue by joshuathayer** [freedomofpress/securedrop-workstation#54]
Currently, `make clone` on dom0 copies the files on the developer's work VM into `~/securedrop-workstation` on dom0. This brings over any changes the developer has been working on, but any *removed* files in the repo on the work VM will still exist in the copy on dom0. We've seen this cause hard-to-diagnose bugs.

We could address this by removing `~/securedrop-workstation` on dom0 as part of the `make clone` process. Thus, the now-empty directory would only be populated by files present in the developer's work VM. A potential downside is that any files changed by the user directly on dom0 would be overwritten. But, that's a workflow we discourage, anyway: all changes should be made in a branch in the work VM.

**Comment by conorsch** [comment]
Resolved by #57.
