### ISSUE TITLE
Create a small template for reporting test results

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#541]
We've agreed that it makes sense to standardize reporting of workstation test results a bit, to ensure we consistently capture version and environmental data. For example:
- host OS used for testing (Qubes vs. Linux/Mac; versions thereof)
- server environment (dev/staging/prod)
- workstation environment (dev/staging/prod)
- client environment (e.g., `sd-app` vs. an `sd-dev` type setup)
- commit hash; any applied patches

While automatic gathering of this data may help in future, for now let's just agree on a standard format to use & what information is most important to gather. See this report by Allie, for example: https://github.com/freedomofpress/securedrop-client/issues/1025#issuecomment-611215532

**Comment by eloquence** [comment]
@zenmonkeykstop said he wants to take a first stab at this during the 4/22-5/6 sprint period, can just be a wiki page for now.

**Comment by zenmonkeykstop** [comment]
First stab here: https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-test-case-report-template

This might make more sense as an issue template, now that I look at it.

**Comment by conorsch** [comment]
Looks great! 

> might make more sense as an issue template

We can always port it at some point, but I see value in using the test-results when reviewing PRs, as well, so wiki page as a first attempt definitely make sense.

**Comment by eloquence** [comment]
Thanks for initializing @zenmonkeykstop, closing - we can take further edits to the wiki :-)
