### ISSUE TITLE
Update grsecurity kernels for workstation templates

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#546]
We are currently 4.14.169 kernels on the workstation (as of today, 4.14.179 has been released), we should consider upgrading these as part of a regular schedule. There have not been any major vulnerabilities and we do we the grsecurity patchset for additional hardening.

Checklist (based on https://github.com/freedomofpress/securedrop-workstation/issues/546#issuecomment-652203513)

- [x] Review/merge https://github.com/freedomofpress/ansible-role-grsecurity-build/pull/59
- [x] Review/merge https://github.com/freedomofpress/securedrop-debian-packaging/pull/176
- [x] Review/merge https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/46
- [x] Wait for packages to be uploaded, make clean/make all and review/merge https://github.com/freedomofpress/securedrop-workstation/pull/582
- [x] Test in dev/staging
- [x] Review/merde PR to prod LFS repository - https://github.com/freedomofpress/securedrop-debian-packages-lfs/pull/29
- [x] Upload source tarball to s3

**Comment by zenmonkeykstop** [comment]
Plan to move to 4.14.179 or get in sync with core (4.14.175)?

**Comment by emkll** [comment]
The current build logic does not make it easy to build historical versions, we should target whatever the latest version is at the time we build the kernels (currently 4.14.179)

**Comment by eloquence** [comment]
For the 5/20-6/3 sprint, we're aiming to build a workstation kernel and get an LFS PR up (not merged), but our priority is a smooth 0.3.0 release including the fedora-30->31 transition (#544).

**Comment by zenmonkeykstop** [comment]
PRs required to unlock testing have been submitted as follows:
- https://github.com/freedomofpress/ansible-role-grsecurity-build/pull/58
- https://github.com/freedomofpress/securedrop-debian-packaging/pull/174
- https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/42
- https://github.com/freedomofpress/securedrop-workstation/pull/565

Some preliminary testing has been done against the kernel by manually installing it in `securedrop-workstation-buster` and reprovisioning the workstation. Outstanding tasks before the LFS PR can be issued include:

- More testing, including apt upgrade scenarios
- Uploading the source offer tarball to S3 (I need to verify/acquire credentials or delegate this)

(Have updated docs while going through the process.)

**Comment by zenmonkeykstop** [comment]
There's been a relevant CVE and grsec patch while these PRs were in the queue, so they will be closed and replaced with a new kernel build soon.

**Comment by zenmonkeykstop** [comment]
A new set of PRs required to unlock testing have been submitted as follows:

- https://github.com/freedomofpress/ansible-role-grsecurity-build/pull/59
- https://github.com/freedomofpress/securedrop-debian-packaging/pull/176
- https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/46
- https://github.com/freedomofpress/securedrop-workstation/pull/582

Some preliminary testing has been done against the kernel by manually installing it in securedrop-workstation-buster and reprovisioning the workstation. Outstanding tasks before the LFS PR can be issued include:

- More testing, including apt upgrade scenarios
- Uploading the source offer tarball to S3

**Comment by eloquence** [comment]
(In light of the number of PRs involved and the need for coordinated review, tracking the issue rather than the individual PRs on the board.)

**Comment by eloquence** [comment]
This was completed, and the new kernel has been released to all workstation users, see https://apt.freedom.press/pool/main/s/securedrop-workstation-grsec/
