### ISSUE TITLE
Release securedrop-client 0.2.0 and securedrop-proxy 0.3.0

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-workstation#547]
There are two packages for the workstation subprojects that are ready for pre-release QA: 
* https://github.com/freedomofpress/securedrop-proxy/pull/74
* https://github.com/freedomofpress/securedrop-client/pull/1083

Next steps:
- [x] Define test plan based on changelogs in those above PRs. That will be linked here.
- [x] Perform QA using nightly packages (if something else is ready for merge in proxy/client we can stop the nightlies temporarily). QA reports should be posted as responses to this ticket and tickets filed in the appropriate repositories for any issues (if you're not sure where a bug report should go please ask and we can point you in the right direction). 
- [x] Final package release https://github.com/freedomofpress/securedrop-debian-packaging/releases/tag/0.2.9
- [x] Merge docs
- [x] Let pilot orgs know of any fixes that are relevant for them

**Comment by eloquence** [comment]
FYI I started putting outlines for testing in https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-Beta-Acceptance-Tests#release-specific-test-plans ; happy to help flesh those out further and add to the PRs.

**Comment by emkll** [comment]
Client and proxy packages, as well as communications and docs have been published.
