### ISSUE TITLE
Release securedrop-workstation 0.3.0

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#548]
This is a placeholder to track the release of the securedrop-workstation 0.3.0 RPM containing updated provisioning code.

### QA Period
- [x] Update version and changelog https://github.com/freedomofpress/securedrop-workstation/pull/550
- [x] Finalize test plan based on changelog above
- [x] Cut release candidate tag https://github.com/freedomofpress/securedrop-workstation/releases/tag/0.3.0-rc1
- [x] Upload package to dev rpm server: https://github.com/freedomofpress/securedrop-workstation-dev-rpm-packages-lfs/pull/8
- [x] Perform QA

### Final Release
- [x] Cut/sign release tag
- [x] Sign package with release key
- [x] Upload package to prod rpm server https://github.com/freedomofpress/securedrop-workstation-prod-rpm-packages-lfs/pull/7
- [x] Let pilot orgs know of any fixes that are relevant for them

### Release-specific test plan
Draft added by @eloquence below, 2020-05-19

#### Scenario: Fresh install

Fixes for **#527** (merged in **#530**) and **#514** (merged in **#535**)
- [ ] During a fresh install of 0.3.0, observe that you do not see the error "Recurse failed: none of the specified sources were found".
- [ ] During a fresh install of 0.3.0, observe that you do not see errors like "Temporary failure resolving 'apt-test.freedom.press'" that cause the installation to fail

#### Scenario: Running preflight updater

**#522**, and **#531** (merged in **#532**)
- Run the command `tail -f ~/.securedrop_launcher/logs/launcher.logs` in a `dom0` terminal (you can `touch` the file to create it if it does not exist yet). This will give you a real-time view of log entries added by the updater. 
- Run the preflight updater manually from `dom0` using `/opt/securedrop/launcher/sdw-launcher.py --skip-delta 0` (this ensures that it will run even if no updates are available)
- After the "checking for updates" stage and before applying updates, launch the VM `sd-app-buster-template`.
- [ ] Observe that `sd-app-buster-template` is shut down in the final stage of the update
- [ ] Observe that `sys-usb` is successfully restarted after updates

#### Scenario: Post-install configuration

**#526** and **#529** (merged in **#533**)
- Apply `sd-send-app-clipboard`, `sd-receive-app-clipboard` and `sd-receive-logs` tag to select VMs by following the [end user documentation](https://github.com/freedomofpress/securedrop-workstation-docs/pull/35). See the [detailed test plan in #533](https://github.com/freedomofpress/securedrop-workstation/pull/533), as well:
   - [ ] Observe that RPC policies for `qvm-copy` are in effect where expected
   - [ ] Observe that RPC policies for copy & paste are in effect where expected and you can copy and paste between VMs
   - [ ] Observe that `qvm-copy` and `qvm-copy-to-vm` commands are still prohibited for VMs not whitelisted via tags
   - [ ] Observe that clipboard operations are still prohibited for VMs not whitelisted via tags

#### Scenario: Uninstall
**#526**
- [ ] Observe that custom RPC tags added during testing are successfully removed
- [ ] Observe that RPC policies in `/etc/qubes-rpc/policy/qubes.ClipboardPaste` and `/etc/qubes-rpc/policy/qubes.Filecopy` are reset to their original values

**Comment by eloquence** [comment]
(Added draft test plan to issue body.)

**Comment by eloquence** [comment]
Starting with uninstall of my automatically updated RPM so I can do a fresh install of RC1:
- Added tags to VMs per test plan
- [x] Observe that custom RPC tags added during testing are successfully removed (see output below)
- [x] Observe that RPC policies in `/etc/qubes-rpc/policy/qubes.ClipboardPaste` and `/etc/qubes-rpc/policy/qubes.Filecopy` are reset to their original values

```
----------
          ID: remove-rpc-policy-tags
    Function: cmd.script
        Name: salt://remove-tags
      Result: True
     Comment: Command 'salt://remove-tags' run
     Started: 15:55:16.985669
    Duration: 565.528 ms
     Changes:   
              ----------
              pid:
                  11943
              retcode:
                  0
              stderr:
              stdout:
                  Removing tag 'sd-send-app-clipboard' from VM 'sd-journalist'.
                  Removing tag 'sd-receive-app-clipboard' from VM 'sd-journalist'.
                  Removing tag 'sd-send-app-clipboard' from VM 'vault'.
                  Removing tag 'sd-receive-logs' from VM 'work'.
----------
```

**Comment by eloquence** [comment]
## Fresh install 
- [x] During a fresh install of 0.3.0, observe that you do not see the error "Recurse failed: none of the specified sources were found".
- [x] During a fresh install of 0.3.0, observe that you do not see errors like "Temporary failure resolving 'apt-test.freedom.press'" that cause the installation to fail

Note: I did see #519 during the first run, but unfortunately lost the output from that. Second run resolved.

**Comment by eloquence** [comment]
#### Scenario: Running preflight updater

**#522**, and **#531** (merged in **#532**)
- Run the command `tail -f ~/.securedrop_launcher/logs/launcher.logs` in a `dom0` terminal (you can `touch` the file to create it if it does not exist yet). This will give you a real-time view of log entries added by the updater. 
- Run the preflight updater manually from `dom0` using `/opt/securedrop/launcher/sdw-launcher.py --skip-delta 0` (this ensures that it will run even if no updates are available)
- After the "checking for updates" stage and before applying updates, launch the VM `sd-app-buster-template`.
- [x] Observe that `sd-app-buster-template` is shut down in the final stage of the update
- [x] Observe that `sys-usb` is successfully restarted after updates

#### Scenario: Post-install configuration

**#526** and **#529** (merged in **#533**)
- Apply `sd-send-app-clipboard`, `sd-receive-app-clipboard` and `sd-receive-logs` tag to select VMs by following the [end user documentation](https://github.com/freedomofpress/securedrop-workstation-docs/pull/35). See the [detailed test plan in #533](https://github.com/freedomofpress/securedrop-workstation/pull/533), as well:
   - [x] Observe that RPC policies for `qvm-copy` are in effect where expected
   - [x] Observe that RPC policies for copy & paste are in effect where expected and you can copy and paste between VMs
   - [x] Observe that `qvm-copy` and `qvm-copy-to-vm` commands are still prohibited for VMs not whitelisted via tags *(spot-checked)*
   - [x] Observe that clipboard operations are still prohibited for VMs not whitelisted via tags *(spot-checked)*

**Comment by eloquence** [comment]
Environment type: Qubes staging,
Client version: 20200526 nightly
Workstation version: 0.3.0rc1
Server version: SecureDrop 1.3.0 staging, Qubes environment

Updated to fedora-31.
- [x] Upgrade succeeded without user-facing errors (Salt error/traceback printed on console, see #559; progress bar misleading, see #560)
- [x] User gets prompted for reboot
- [x] `sys-net`, `sys-usb` and `sys-firewall` updated to `fedora-31`
- [x] Client passes initial smoke test

Now re-testing export flow.

**Comment by eloquence** [comment]
:tada: USB auto-attach logic to `sd-devices` still working beautifully after fedora-31 upgrade was applied `sys-usb` (tested with block device and unsupported printer)

**Comment by zenmonkeykstop** [comment]
- Installed 0.2.4(prod), upgraded to 0.3.0-rc2 via preflight updater as per [wiki instructions](https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-dom0-QA-testing).
- Added `sd-receive-app-clipboard, sd-receive-logs, sd-send-app-clipboard` tags to `vault` VM

## Scenario: Post-install configuration
- [x] Observe that RPC policies for qvm-copy are in effect where expected **verified for sd-* VMs**
- [x] Observe that RPC policies for copy & paste are in effect where expected and you can copy and paste between VMs **verified for sd-app and vault VM pair**
- [x] Observe that qvm-copy and qvm-copy-to-vm commands are still prohibited for VMs not whitelisted via tags **verified for sd-* VMs, sd-log and vault pair**
- [x] Observe that clipboard operations are still prohibited for VMs not whitelisted via tags **verified for sd-app and work VM**

**Comment by emkll** [comment]
Closed via https://github.com/freedomofpress/securedrop-workstation-prod-rpm-packages-lfs/pull/7
