### ISSUE TITLE
dom0 update issue: Domain sys-firewall sent unexpected file

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#553]
@ninavizz experienced the following update failure during a `dom0` update (the SecureDrop Workstation preflight updater failed, after which I encouraged her to try using Qubes' own updater):

![qubes-update](https://user-images.githubusercontent.com/213636/81997739-847cdd80-9605-11ea-983c-6f1f854b4a08.jpg)

This seems to be a very unusual error, a [Google search](https://www.google.com/search?q=qubes+"sent+unexpected+file") turns up only the code which generates it. Tracking in our repo for now until we understand it better.

**Comment by ninavizz** [comment]
Erik advised I reboot and try again, and I got the same result. This is a screenie of the resulting logs... :(
![oops2](https://user-images.githubusercontent.com/8262612/82101289-fe25d180-96c0-11ea-81fd-06b75741ad8b.png)

**Comment by conorsch** [comment]
> turns up only the code which generates it

The code in question: https://github.com/QubesOS/qubes-core-admin-linux/blob/a3098d517f9f85af4ec02db4077ecf2192f340a5/dom0-updates/qubes-receive-updates#L83-L85

See discussion in https://github.com/freedomofpress/securedrop-workstation/issues/540#issuecomment-628157150. We recently uploaded an rpm to the staging yum repo with a tilde in the filename—which fails the regex validation in `qubes-receive-updates`, even though it's technically a valid rpm. Immediate fix is removing that problematic rc file from the dom0 repo. Then, in #540, we'll discuss solutions to the naming pragma.

**Comment by conorsch** [comment]
Changes in https://github.com/freedomofpress/securedrop-workstation-dev-rpm-packages-lfs/pull/9 should have resolved, running updater in "staging" env now to confirm resolved...

**Comment by conorsch** [comment]
Confirmed successful update via SD graphical updater on login, using dedicated test-only hardware running the "staging" env for the Workstation. We still have outstanding work regarding the rc, see #540 for details.

**Comment by conorsch** [comment]
Confirming that graphical updater in "staging" env successfully upgraded to 0.3.0 rc1, after merge of:

* https://github.com/freedomofpress/securedrop-workstation/pull/554
* https://github.com/freedomofpress/securedrop-workstation-dev-rpm-packages-lfs/pull/10

Haven't performed functional testing, but clearly we've resolved the installation problems originally documented in this ticket. We'll continue with QA following #548
