### ISSUE TITLE
Workstation laptop does not shut down when laptop lid closed

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-workstation#574]
#### Environment
Lenovo Thinkpad X1 Carbon 6Gen / Qubes 4.0.3
SecureDrop Workstation (Prod, up-to-date)

#### Description
It appears there is a regression on the laptop-lid-shutdown feature, which I previously tested on this production laptop:
* Closing the lid does not shut down the machine
* The laptop has "Suspend" and "Hibernate" options available in the Log out menu. Hibernate appears to lock the screen with the Xcreensaver session login screen, but not hibernate the computer.  
  
#### STR 
Apply updates as needed, use SecureDrop Workstation laptop, close the lid.

#### Expected
Laptop shuts down
 
#### Actual   
Laptop remains on (suspended) and opening it reveals the Xscreensaver session login screen.

**Comment by eloquence** [comment]
(Trying to repro this now)

**Comment by eloquence** [comment]
I can't reproduce this, @rocodes. The fact that you also still have the "Suspend" and "Hibernate" options suggests to me that this is perhaps a configuration issue, as the removal of those options and the altered lid-close behavior are handled by different code paths, both of which check whether the environment is set to "prod" or "staging".

Please note that (confusingly) you will _not_ have a `prod` build if you run `make all` with `config.json` set to prod; it will reset your configuration to `dev`. Do you recall how you built this particular prod environment?

**Comment by rocodes** [comment]
This laptop was provisioned in a prod provisioning walkthrough and I did not believe I had run `make all` since, being on prod and all....but I must have, because sure enough my configuration was reset to `dev`. Thanks @eloquence.  Closing sheepishly
