### ISSUE TITLE
make dom-rpm failing on Fedora

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop-workstation#598]
It failed with the following error

```
Please provide a source image with `from` prior to commit
```

## Steps to reproduce

- [ ] checkout the code in a Fedora Vm
- [ ] Have docker installed and running (`systemstl start docker`)
- [ ] `make dom0-rpm`

**Comment by conorsch** [comment]
As of https://github.com/freedomofpress/securedrop-workstation/pull/666, this isn't an issue anymore: `make dom0-rpm` appears to work just fine under Fedora. The `make install-deps` still assumes Debian, which is a minor inconvenience, but overall I believe we're covered here.

**Comment by eloquence** [comment]
(Closing per above)
