### ISSUE TITLE
Nightly builds are broken

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#606]
Nightlies haven't been updated since August 19, e.g.:
https://apt-test.freedom.press/pool/main/s/securedrop-client/

**Comment by conorsch** [comment]
Looking into this, since we'll want the nightly publish logic working upon review of e.g. https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/58 Saw this error in the logs:

```
INFO:reprepro-auto-publish:Preparing packages for distro focal
includedeb called with file '' not ending with '.deb'
To ignore use --ignore=extension.
There have been errors!
```

Which seems like a fairly straightforward whitespace-handling problem.

**Comment by conorsch** [comment]
Updated the relevant script, now seeing 2020-08-31 packages https://apt-test.freedom.press/pool/main/s/securedrop-client/

**Comment by emkll** [comment]
Looks like the Sept 1 nightlies didn't make it to apt-test

**Comment by conorsch** [comment]
Mea culpa: I'd commented out the cron job while investigating, and didn't re-enable after patching the script. Monitoring for a few more minutes to confirm the cron logic catches the repo up with the latest packages.

**Comment by conorsch** [comment]
Ahoy! https://apt-test.freedom.press/pool/main/s/securedrop-client/securedrop-client_0.2.1-dev-20200902-060111%2Bbuster_all.deb Also seeing https://apt-test.freedom.press/pool/main/s/securedrop-workstation-grsec/securedrop-workstation-grsec_4.14.186%2Bbuster2_amd64.deb which means that https://github.com/freedomofpress/securedrop-workstation/pull/604 is unblocked, will comment over there.
