### ISSUE TITLE
[Qubes 4.1] make dom0-rpm support for Fedora 32

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#611]
Initially reported in https://github.com/freedomofpress/securedrop-workstation/issues/600

A locally-built `securedrop-workstation-dom0-config` package fails to install in dom0 with the following error:
```
ERROR
  Problem: conflicting requests
    - nothing provides python (abi) = 3.5 needed by securedrop-workstation-dom0-config-0.4.0-1.fc25.noarch
```

This is likely because the FPF-managed container used to build the rpms [1] is based on Fedora 25 (Qubes 4.0.1 dom0)
 
We should:
- create a separate fedora-32 rpm builder image
- create a separate makefile target for fedora 32 (so that we can build both 4.0.x (F25) and 4.1.x (F32) dom0 config packages)
- consider moving the dockerfile(s) to the securedrop-workstation repository (similar to what we do for the RPM repo management) 
- Are we even using the above rpm repo management Dockerfile?

[1]  https://github.com/freedomofpress/containers/blob/af86bb4b0fc7edc00d62cc56ef0e27f3311d22c7/rpmbuilder/Dockerfile#L1
[2] https://github.com/freedomofpress/securedrop-workstation/blob/main/docker/CreateRepoRPM/Dockerfile

**Comment by kushaldas** [comment]
>This is likely because the FPF-managed container used to build the rpms [1] is based on Fedora 25 (Qubes 4.0.1 dom0)

Yup, that is the cause here.

**Comment by emkll** [comment]
Confirmed that using a Fedora 32 based container image and `ARG FEDORA_PKGR_VER=0.6.0.4-1.fc32` resolves using a local container build, without any further changes.

**Comment by conorsch** [comment]
If we bump the builder image to f32, can we use that same image to build rpms for dom0 on 4.0, which is f25? I'd expect so, but we were pinning the old fedora version specifically to match what the eventual install target will be. That may be overly cautious. 

> Are we even using the above rpm repo management Dockerfile?

No, should have been removed as part of #349, but overlooked it. It can be removed at any time.

**Comment by kushaldas** [comment]
>If we bump the builder image to f32, can we use that same image to build rpms for dom0 on 4.0, which is f25? 

Things should fail as Fedora needs packages built on the same version of the OS.
