### ISSUE TITLE
Prod uninstall doesn't reset power menu

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#625]
Recently I provisioned non-dedicated hardware with a "prod" Workstation install. After uninstalling, my power menu wasn't reset to include the "Suspend" option:

![sdw-dom0-power-menu-prod-settings-persist](https://user-images.githubusercontent.com/657862/97031323-f5111a00-1514-11eb-8323-aec2fbc438c9.png)

It's certainly possible I messed up on the uninstall, or overlooked an error that was accurately reported. Inspecting the diff in https://github.com/freedomofpress/securedrop-workstation/pull/475, I tried to run `update-xfce-settings reset-power-management`, but wasn't able to: when run as root, there's an error about being unable to connect to dbus. When run as normal user, I can't read the file at `/srv/salt/update-xfce-settings`. If I copy that file out to `/tmp/`, then I'm able to run it, and the menu was restored properly.

If someone else can reproduce this (likely as part of https://github.com/freedomofpress/securedrop-workstation/pull/619 test plan), then we should resolve. Simply copying the script to `/usr/bin/` as part of the RPM, or folding its logic into `sdw-admin`, would suffice. Not a blocker for 0.5.0, certainly.

**Comment by eloquence** [comment]
Hm, the logic in `sd-clean-all` _should_ be running as the GUI user, and the script will then attempt to identify the appropriate DBUS session. But that logic always struck me as potentially brittle:


```bash
# This script requires a valid DBUS session to work. When run non-interactively,
# we assume that a sesssion is running for the current user.
if [ -z "${DBUS_SESSION_BUS_ADDRESS:-}" ]; then
   export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"
fi
```

I'll try to repro on my next uninstall.

**Comment by conorsch** [comment]
Since opening, I've installed and uninstalled prod environments several times, and have not been able to reproduce the power menu problems reported above. Closing as a fluke.
