### ISSUE TITLE
[0.5.0] Logging client config not set up for appvms built from large, small templates.

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-workstation#631]
SecureDrop log aggregation uses rsyslog to send appvm logs to `sd-log` - this requires a config file be present in `/etc`. This file is not being set up in the appvms during a fresh install, so no logs are being recorded.

There are probably 2 ways to fix this:
- add the file in the templates (one disadvantage is that all appvms will now record logs, including sd-gpg)
- add some config under /rw for specific VMs to set up the config file and restart rsyslog on startup

**Comment by eloquence** [comment]
For comparison, on an upgraded system (via sad path), I am able to continue to log to `sd-log` like so:

- `logger foo` in `sd-app`
- Line `user: foo` appears in log on `sd-log` immediately

(VM boot logs are also present)

**Comment by emkll** [comment]
Good find, reproduced this myself on a clean install (after also ensuring the base template is removed). After the first install, `/etc/sd-rsyslog.conf` is absent from both the small and large templates, so the logging doesn't work for AppVMs based on these templates, only on a clean install scenario.

The reason upgrade testing is working is that `sd-{small,large}-buster-template` are based on `securedrop-workstation-buster` which inherits `/etc/sd-rsyslog.conf` that is already present.
