### ISSUE TITLE
`systemd-modules-load.service` error during initial provisioning

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#644]
We've received two independent reports about an error during provisioning, at this stage:

```
depmod...
Job for systemd-modules-load.service failed because the control process exited with error code.
See "systemctl status systemd-modules-load.service" and "journalctl -xe" for details.

DKMS: install completed
```

Repeated run of `sdw-admin --apply` resolved.

**Comment by conorsch** [comment]
Make that three independent reports, one by @eloquence just now. Looks like the u2mfn problem rearing its head again, related to changes we made in https://github.com/freedomofpress/securedrop-debian-packaging/pull/189 The upstream version has changed from `4.0.30` -> `4.0.31`, see https://github.com/QubesOS/qubes-linux-utils/commit/97271bab41f588b0c9dc8cbcf3ff70bd775e1ec3

Looks like the issue affects first-time clean installs, but not upgrades. Let's patch the version of u2mfn in the metapackage and proceed with release QA for 0.5.1 (#643).

**Comment by conorsch** [comment]
In order to reproduce the failure, I had to run `sudo dnf remove qubes-template-securedrop-workstation-buster`. Reminder that the `make clean` action in the dev env does not purge the RPM, but the `sdw-admin --uninstall` action (for staging or prod) does.
