### ISSUE TITLE
Add tests for launcher/UpdaterApp.py

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#649]
Related to #646 

We currently, by policy, targeting 100% test coverage for `Updater.py`, which contains most of updater logic.

While `UpdaterApp.py` primarily handles the UI, we should still consider adding test coverage there to prevent regressions, given that we are introducing new functionality and further complexity (e.g. handling migrations)

**Comment by zenmonkeykstop** [comment]
Test coverage has been increased from 2022 on. Closing, but test coverage for new launcher should also be at acceptable levels.
