### ISSUE TITLE
Validation regex may be overly restrictive

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#660]
We validate the auth token for the v3 onion service in: https://github.com/freedomofpress/securedrop-workstation/blob/bdd07b29f919ce445907a20fd9c5ee0979bfb01a/scripts/validate_config.py#L14

I have recently set up an instance with v3 onion service, and the X25519 secret for the onion service had at least one `0` character in it, which may make the regex above overly restrictive.

**Comment by eloquence** [comment]
The [client auth](https://community.torproject.org/onion-services/advanced/client-auth/) docs note that the v3 keys are to be formatted as base32. All publicly available docs suggest using the `base32` utility, which implements the alphabet defined in RFC 4648. That in turn excludes 0 and 1. Following these docs I've not been able to create a key with a 0 or 1. Are you still able to reconstruct how and at which stage you saw a key with a 0 in it?

**Comment by eloquence** [comment]
The relevant code from securedrop-admin:
https://github.com/freedomofpress/securedrop/blob/427675858c49ef67573bb002b37fce06c029a84d/admin/securedrop_admin/__init__.py#L717-L718

This uses the `base64.b32encode` function, which also implements the alphabet specified here: https://tools.ietf.org/html/rfc3548.html#page-6

**Comment by eloquence** [comment]
Per discussion with @emkll closing for now until we see further evidence of such keys being generated.
