### ISSUE TITLE
Further restrict RPC policies for `sd-viewer` DispVMs

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#680]
Identified as an informational finding in the attack surface analysis in the December 2020 audit report, the audit team recommends disabling every RPC except those essential for SecureDrop Workstation, such as `securedrop.Log`, and additionally to disable the ability of the sd-viewer DispVM to create further DispVMs (#677). Some files are also `.bak` files (related to #675)

| To dom0       | To sd-log     | To a DispVM    |
| :------------- | :----------: | -----------: |
qubes.WindowIconUpdater | securedrop.Log | qubes.VMShell.bak
qubes.FeaturesRequest | |qubes.GetImageRGBA
qubes.FeaturesRequest.bak || qubes.OpenURL.bak
qubes.GetRandomizedTime | |qubes.OpenInVM.bak
qubes.GetDate | |qubes.PdfConvert.bak
qubes.StartApp.bak
qubes.NotifyUpdates
qubes.NotifyTools
qubes.SyncAppMenus
qubes.ReceiveUpdates

[Original issue description by @emkll]

**Comment by rocodes** [comment]
Superseded by #672
