### ISSUE TITLE
Consider avoiding `assert` statements in validate_config.py

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#683]
Informational finding `TOB-SDW-024` from the [2020 SecureDrop Workstation audit (PDF)](https://media.securedrop.org/media/documents/Trail_of_Bits_SecureDrop_Workstation_Audit_2020.pdf)  notes that `assert` statements are optimized out if Python is ever run with the [`-O` or `-OO` flags](https://docs.python.org/3/using/cmdline.html#cmdoption-o) and recommends eventually factoring them out in favor of `if` conditions and custom exceptions in `validate_config.py`, which is not test code but used during the installation.

**Comment by pierwill** [comment]
I'd be happy to help with this. Would we need a small helper function that tests for truth and exits on false?

**Comment by gonzalo-bulnes** [comment]
> Would we need a small helper function that tests for truth and exits on false?

I was thinking along the same lines. I think I'd make all those functions return a `bool` and either exit early with a function like @pierwill suggests, or collect all the steps and exit `0` or `1` if any of the checks returned `False`.

**Comment by zenmonkeykstop** [comment]
Planning to investigate config validation in the near future, will take this ticket on as a first step.
