### ISSUE TITLE
Repository is missing a LICENSE file

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#70]
This repository is missing a LICENSE file. I suggest that we use AGPLv3, purely for consistency with the main SecureDrop codebase.

https://github.com/freedomofpress/securedrop/blob/develop/LICENSE

**Comment by redshiftzero** [comment]
Thanks for filing this @eloquence - AGPLv3 sounds good to me. @joshuathayer what do you think?

**Comment by joshuathayer** [comment]
Works for me! I'll open a PR today.
