### ISSUE TITLE
`update_version.sh` modifies `securedrop-workstation-dom0-config.spec` in more places than necessary

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop-workstation#709]
# Description

`version`and `srcname` vars are being replaced by hard-coded values when we run the `update_version.sh` script, see https://github.com/freedomofpress/securedrop-workstation/commit/29e290c121ff9b49e4b88db98f07cf88009cbd70#diff-5d2e11f87f29c1289d107de90bd520aa145edde09453d280d1c446e84b7c3aa0R24. We only need to set `%global version` to the correct version for this to work. 

ref: https://github.com/freedomofpress/securedrop-workstation/pull/703/commits/3f1a8f5abe5e7fca5d1e2def766fa79d0d4f6cdc

**Comment by zenmonkeykstop** [comment]
No longer relevant due to version script updates.
