### ISSUE TITLE
'NoneType' object has no attribute 'label' during provisioning

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-workstation#72]
# Description 

On Qubes 4.0-rc4, during provisioning I hit `'NoneType' object has no attribute 'label'` for each execution of  `sudo qubesctl --targets * state.highstate`. 

# Steps to Reproduce

1. `make all` in `dom0`

# Expected Behavior

VMs provisioned as expected with all modifications applied

# Actual Behavior

When the provisioning hits the `sudo qubesctl --targets * state.highstate` step for each VM, the following appears in the output:

```
sd-whonix: ERROR (exception 'NoneType' object has no attribute 'label')
```

then it proceeds onto the next VM. VMs are created, but without some custom files (maybe all custom files, I haven't checked all of them - that said at minimum, in `sd-whonix`, the `HidServAuth` line is missing from `/etc/tor/torrc`). 

# Comments

I have tried provisioning VMs one at a time and hit the same issue. Anyone seen this before or have a suggested place to look to debug further?

**Comment by joshuathayer** [comment]
Interesting. I'll try to reproduce this and see if I learn anything.

**Comment by redshiftzero** [comment]
Well, I rebuilt my workstation on the final 4.0 release and this is no longer an issue. I'm not actually sure what the issue _was_, but in the interest of not descending into a rabbit hole 😇 🐰  I will close this ticket and instead encourage anyone else who sees this going forward to reopen this ticket.
