### ISSUE TITLE
Improve updater error handling and user experience

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-workstation#720]
## Problem
From the 2021 SD Summit, some user pain-points & opportunity areas were flagged that are desired to be acted upon.

1. Improved Failure Messaging
   - Primary time-sink painpoint between Admins and FPF support staff, and Journalists/Admins
   - Primary need is simple plain-language "This Happened" messaging to parse from common errors returned in logs
   - Nice-To-Have would be ability to export logs directly to another qube, or to view entire log to cut-and-paste
2. Improved experience between "Remind Me Later" and "Do It Now" oscillation (#595)
3. Improved identification of the Reminder window as being tied to the SD Preflight Updater
4. Improved experience for users to more explicitly consent to be reminded again to run the updater, or to quit the Client (if running) and run the updater now. Currently, the user has to click the "close

![Updater-Nag_AsIs2](https://user-images.githubusercontent.com/8262612/129287945-d8b160f1-754b-4e8c-81df-fe5f41ea3dcd.png)

## Solution
Improved installer experience from Qubes, directly. Until then—what minimal investments can we make in the SDW updater, to keep Admin tears to a minimum and to smooth-out the updater experience for everyday Journalist users?

Did some mox: https://drive.google.com/drive/folders/167S2mnoRvL0OS0eNm0KcezVoQgNLcM5S?usp=sharing

**Comment by zenmonkeykstop** [comment]
Flagging for @deeplow's attention but closing the issue itself - we're moving to using the Qubes Updater so a lot of the minimal investments above would no longer be applicable.
