### ISSUE TITLE
Use Fedora 34 in sys-* VMs 

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#735]
It'll soon be that time again. We're still running Fedora 33 (#691), which goes EOL on 2021-11-30: https://endoflife.date/fedora Unfortunately, it looks like there's no `qubes-template-fedora-34` RPM available in the dom0 repos for 4.0 yet. Lets investigate upstream and try to get a sense of timeline.

**Comment by conorsch** [comment]
Great opportunity to tackle #702.

**Comment by conorsch** [comment]
Still in progress upstream, see https://github.com/QubesOS/qubes-issues/issues/6568. We can and should pull the template in from the "testing" repository to evaluate how it'll work.

**Comment by creviera** [comment]
I can [enable the the qube template test repos](https://www.qubes-os.org/doc/how-to-install-software/#testing-repositories) tomorrow and test the fedora-34 template with our updater. i think the fedora-35 template will also be accessible, so worth testing with that too to put us much further away from the next eol.

**Comment by conorsch** [comment]
Sounds wonderful, @creviera. In the interest of clarity, I see the testing steps we can do on this issue immediately as:

1. Run `sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing qubes-template-fedora-34` to grab the "testing" rpm.
2. Edit this var: https://github.com/freedomofpress/securedrop-workstation/blob/0197699e372e83cf62dfe7bc4b96bd9cc9883502/dom0/sd-sys-vms.sls#L12 to use `fedora-34`
3. Run the updater
4. Log into the client and test is functionally.

If you run into any errors, document them here and we'll investigate. Any blockers for our needs will need to be reported upstream, but let's confer amongst ourselves first.

**Comment by creviera** [comment]
I was able to follow @conorsch's steps above and do basic client testing that included:
:heavy_check_mark: Export-to-usb workflow 
:heavy_check_mark: Syncing with the server
:heavy_check_mark: Downloading and decrypting new files, messages, and replies sent via the web clients

**Comment by creviera** [comment]
Oh, never mind about testing `fedora-35`, since it's not yet on the testing repo: https://github.com/QubesOS/qubes-issues/issues/6969

**Comment by conorsch** [comment]
Good news, upstream's already published the F34 RPM in the prod repo for Qubes 4.0.4. We're now unblocked to migrate and release the change. Let's get an RPM up with changes and try to ship next week, to stay ahead of the EOL date. @creviera if you've got a branch lying around, mind opening a PR?
