### ISSUE TITLE
Test ThinkPad T14 Qubes/SDW compatibility

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#749]
The availability of the ThinkPad T490 has been intermittent at best over the last few months, and it is now marked as "no longer available". We now have the first T14 (with @cfm) and other orders have been placed. Let's test it with Qubes 4.0.4/4.1 and the SecureDrop Workstation to determine whether it can potentially replace the T490 as our standard recommendation.

**Comment by cfm** [comment]
I've successfully validated my ThinkPad T14 hardware and installed Qubes 4.0.4 on it.  My full notes are in Confluence.  For the record here, the only noteworthy detail so far is that `sys-net` to boot requires [`no-strict-reset`](https://www.qubes-os.org/doc/pci-troubleshooting/#domain--has-failed-to-start-internal-error-unable-to-reset-pci-device--no-flr-pm-reset-or-bus-reset-available) on the `Ethernet controller: Intel Corporation` device, just like the T490 in #741.

Next week I'll proceed with the rest of the SecureDrop Workstation installation.

**Comment by eloquence** [comment]
@cfm Awesome, thanks for the write-up. If you are able to install SDW successfully, it would be great to add it to the official docs (https://workstation.securedrop.org/en/stable/admin/hardware.html). If you don't get around to that this sprint I may be able to do it working off your notes.

**Comment by cfm** [comment]
SecureDrop Workstation is installed and running successfully!  No major detours required from the current stable instructions, but I'll put some documentation tweaks in tomorrow.
