### ISSUE TITLE
Research task: Tails/Qubes viewing feature comparison

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#75]
We should ensure that any file in a plausible submission format that can be successfully viewed with a Tails workstation can also be viewed with the SecureDrop workstation.

The first task is a research task, the result of which would be a list as follows:

| File Format  | Tails Default App | SD Workstation Default App
| ------------- | ------------- |------------- |
| DOC  | LibreOffice | AbiWord|

Totally made up example, but you get the gist. I think we'd want at minimum to cover common/likely submission/archiving formats including:

- Archives: zip, tgz, rar, 7z 
- Documents: pdf, txt, doc, docx, xls, xlsx, ppt, pptx, odt, ods, odp
- Images: jpg, png, gif, tif, djvu, webp, svg
- Media: avi, mp3, mpg, mov, ogv, ogg, wav, webm

(I'm probably missing obvious ones, please add comment and I will update above list.)

The overall user story here is that, as a Tails user, I don't want to experience a regression in terms of my ability to inspect submissions when switching to the SD Workstation.

**Comment by joshuathayer** [comment]
Files open in disposable VMs, which are based on fedora 26, so any files handled in fedora 26 will  open correctly in the workstation. I'll see about making a complete list.

**Comment by eloquence** [comment]
Per the work done in #168, we have broad, comparable file format support now, and can track additional, individual filetypes through separate issues (e.g., #614).
