### ISSUE TITLE
Enable CUPS in sd-devices

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/securedrop-workstation#757]
So the CUPS service has [now been disabled by default for security reasons](https://github.com/QubesOS/qubes-core-agent-linux/pull/364). I haven't been in touch with the SecureDrop Workstation for a while, but I'm guessing this will impact the project by breaking printing.

The mitigation should be just a matter of [enabling the CUPS service](https://github.com/QubesOS/qubes-issues/issues/7281#issuecomment-1044376334) in the sd-devices (which I'm guessing is the qube responsible for printing).

**Comment by ninavizz** [comment]
The issue you linked-to, only began because I recognized CUPS in a Qubes team chat-stream, from the Workstation project. Thx for filing this, @deeplow!

**Comment by eloquence** [comment]
Hi @marmarek, is the change in https://github.com/QubesOS/qubes-core-agent-linux/pull/364 going to only land in 4.2, or will it  / has it been backported to 4.1?

**Comment by marmarek** [comment]
4.2

**Comment by eloquence** [comment]
Thanks Marek. Milestoned accordingly. (Thanks @deeplow for filing originally!)
