### ISSUE TITLE
Switch to fedora-35 when available

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#763]
fedora-34 will reach end of life on May 17 (https://endoflife.date/fedora). We should prepare to migrate once fedora-35 templates are available (cf. #736).

**Comment by rocodes** [comment]
Fedora 35 template in the testing repo is working well for me; I'll put up a PR in draft mode that we can flip over as soon as the template lands in stable. (The timing looks like it will be pretty tight)

**Comment by rocodes** [comment]
Thanks @andrewdavidwong (and sorry for the invocation)! This is an older ticket, we have June 7 on our sprint-planning calendar, but appreciate the update.
