### ISSUE TITLE
Logging broken on Qubes 4.1 [in-place upgrade]

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#773]
On my in-place upgraded Qubes 4.1 system, I see no logs being ingested to `sd-log` at all. Instead, I see lines like the following repeated in AppVMs like `sd-app`:

```
Apr 18 16:05:29 localhost rsyslogd: omprog: program '/usr/sbin/sd-rsyslog' (pid 1857) terminated; will be restarted [v8.1901.0 try https://www.rsyslog.com/e/2119 ]
Apr 18 16:05:29 localhost rsyslogd: action 'action-0-omprog' suspended (module 'omprog'), retry 0. There should be messages before this one giving the reason for suspension. [v8.1901.0 try https://www.rsyslog.com/e/2007 ]
Apr 18 16:05:30 localhost rsyslogd: action 'action-0-omprog' resumed (module 'omprog') [v8.1901.0 try https://www.rsyslog.com/e/2359 ]
```

I see no policy denial errors in dom0.

**Comment by eaon** [comment]
Reproduced this (with 4.1 repositories in buster) and tracked it down to the [`/etc/qubes-rpc/securedrop.Log`](https://github.com/freedomofpress/securedrop-log/blob/main/securedrop.Log) not having the executable bit set. Looks like that would require a new release of `securedrop-log`.

**Comment by eloquence** [comment]
Thanks Michael! Since the securedrop-log change was merged, closing this, we can re-verify in final QA if it works as expected.
