### ISSUE TITLE
Export broken on Qubes 4.1 [in-place upgrade/4.1 repos]

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#775]
# Steps to reproduce

On a 4.1 system with 4.1 packages in TemplateVMs:
- Attempt to export a file with the SecureDrop Client

# Expected behavior

File is exported

# Actual behavior

Error message: "Export failed"

# Analysis

There are two issues here:

1. `qvm-open-in-vm` is used for export, so the same AppArmor issue resolved via https://github.com/freedomofpress/securedrop-client/pull/1485 comes into play here.
2. Once this is addressed, the other issue is that `qvm-open-in-vm` from 4.1 [redirects output to `/dev/null`](https://github.com/QubesOS/qubes-core-agent-linux/blob/3a5afc2525d5e01122e28aeb6f9192ea28751537/qubes-rpc/qvm-open-in-vm#L75) (same commit that introduced the AppArmor issue). We parse that output to test export results, so all of this logic no longer works:
https://github.com/freedomofpress/securedrop-client/blob/main/securedrop_client/export.py#L115-L118

**Comment by eloquence** [comment]
`qvm-open-in-vm` is a pretty basic script that ultimately just makes calls like `/usr/lib/qubes/qrexec-client-vm sd-devices qubes.OpenInVM "/usr/lib/qubes/qopen-in-vm" [somefilename]`, so we could just avoid using it altogether. This would allow us to reduce the number of AppArmor allowals, and resolve the issue with `/dev/null` redirection.

@marmarek I'm curious what the reasoning is to redirect output to `/dev/null` when it previously wasn't?

**Comment by marmarek** [comment]
> @marmarek I'm curious what the reasoning is to redirect output to `/dev/null` when it previously wasn't?

It fixes https://github.com/QubesOS/qubes-issues/issues/6562, but also adds extra hardening to not print data controlled by another VM to the terminal.

**Comment by marmarek** [comment]
Direct `qrexec-client-vm` call sounds like a good approach.

**Comment by eloquence** [comment]
FYI @creviera @eaon the following invocation has worked for me from `sd-app`:

`/usr/lib/qubes/qrexec-client-vm -- sd-devices qubes.OpenInVM "/usr/lib/qubes/qopen-in-vm" -- test.sd-export`

(Where `test.sd-export` is a tgz file that contains only a metadata.json with `{ "device": "usb-test"}` - I can run that successfully to get a status back from sd-devices on Qubes 4.1.)

If you don't beat me to it, I can try replacing the call in SecureDrop Client and test that on 4.0 and 4.1.
