### ISSUE TITLE
Release securedrop-workstation-dom0-config 0.6.3 for Qubes 4.0

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-workstation#791]
# Description

Release `securedrop-workstation-dom0-config-0.6.3-1.fc25 for Qubes 4.0

* [x] Bump RPM version to 0.6.3
* [x] Create signed tag for 0.6.3
* [x] Build RPM, sign with test key, submit to dev lfs repo 
* [x] Resign RPM with prod key, submit to prod lfs repo
* [x] Re-test changes introduced in https://github.com/freedomofpress/securedrop-workstation/pull/786 (see QA Test Plan below)
* [x] Post-release check (run `make clean && make prod` to get the new package from the yum repo)

## QA Test Plan
**Testing**
- Ensure your Qubes 4.0 workstation is set to a prod environment
- Run the command `gpg /etc/pki/rpm-gpg/RPM-GPG-KEY-securedrop-workstation`.
  -  [x]  Confirm that you're either seeing the test key, or a key with the 2022 expiry.
- Force a run of the updater with `/opt/securedrop/launcher/sdw-launcher.py --skip-delta 0`
- [x] Confirm that you're now seeing the updated key

**Post-release check**
- Ensure your Qubes 4.0 workstation is set to a prod environment... if you have an existing install:
  - Run the command `gpg /etc/pki/rpm-gpg/RPM-GPG-KEY-securedrop-workstation`.
  -  [ ]  Confirm that you're either seeing the test key, or a key with the 2022 expiry.
  - For bonus points, double-check that the key isn't hiding in RPM's keyring with the command `rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'`.
- Force a run of the updater with `/opt/securedrop/launcher/sdw-launcher.py --skip-delta 0`
- [ ] Confirm that you're now seeing the updated key

**Comment by gonzalo-bulnes** [comment]
Testing on a R4.0 **production** workstation:

**Testing**
- [x] Ensure your Qubes 4.0 workstation is set to a prod environment
- Run the command `gpg /etc/pki/rpm-gpg/RPM-GPG-KEY-securedrop-workstation`.
  -  [x]  Confirm that you're either seeing the test key, or a key with the 2022 expiry. (`[expires 2022-07-04]` :green_circle: )
- Force a run of the updater with `/opt/securedrop/launcher/sdw-launcher.py --skip-delta 0`
- [ ] Confirm that you're now seeing the updated key

**Post-release check**
- Ensure your Qubes 4.0 workstation is set to a prod environment... if you have an existing install:
  - Run the command `gpg /etc/pki/rpm-gpg/RPM-GPG-KEY-securedrop-workstation`.
  -  [ ]  Confirm that you're either seeing the test key, or a key with the 2022 expiry.
  - For bonus points, double-check that the key isn't hiding in RPM's keyring with the command `rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'`.
- Force a run of the updater with `/opt/securedrop/launcher/sdw-launcher.py --skip-delta 0`
- [ ] Confirm that you're now seeing the updated key
