### ISSUE TITLE
`lpinfo: Bad file descriptor` error when attempting to print from client

### ISSUE THREAD

**Issue by eaon** [freedomofpress/securedrop-workstation#794]
When attempting to print from the client with current nightlies, trying to print results the following error:

![image](https://user-images.githubusercontent.com/201369/176218694-cb84cc86-cd23-489b-9c4e-3e813dc4ad9f.png)

It looks as if we might be missing some CUPS packages.

**Comment by deeplow** [comment]
Looks this this also closes https://github.com/freedomofpress/securedrop-workstation/issues/757
