### ISSUE TITLE
`sd-fedora-dvm` setting change sometimes fails on uninstall

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#799]
#764 switches `sys-usb` to `sd-fedora-dvm` if it is disposable (which it will be in the configuration we will recommend to users). It also added logic to clean up this association upon uninstall:

https://github.com/freedomofpress/securedrop-workstation/blob/b7eebfe3f54db6422afc3ba7e7d502bbc2a24cc6/dom0/sd-clean-all.sls#L12-L35

This logic failed for me on one uninstall attempt; I unfortunately did not capture the error output, and it subsequently succeeded. If you see this issue on uninstalling, please add the detailed output for reference.

**Comment by eloquence** [comment]
Since the logic uses a `sleep` command, one question it raises for me is under what circumstances the sleep period may be exceeded, and whether there's an alternative to using `sleep` here to mitigate timing issues.

**Comment by zenmonkeykstop** [comment]
Closing as not reproduced on 4.2 - will reopen if we see it
