### ISSUE TITLE
consider Salting workaround for AX210 firmware compatibility

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-workstation#807]
In freedomofpress/securedrop-workstation-docs#109, we document and minimally script a workaround for an incompatibility in the latest Intel AX210 firmware provided by Fedora's `iwlax2xx-firmware`.  Other Qubes users have [reported](https://forum.qubes-os.org/t/ax210-211-wifi-card-not-showing-any-networks/9498) the same problem (among others closely related), for which the most-canonical upstream tickets appear to be [kernel bug no. 212371](https://bugzilla.kernel.org/show_bug.cgi?id=212371) and [Fedora bug no. 1940263](https://bugzilla.redhat.com/show_bug.cgi?id=1940263).

Depending on the upstream prognosis, we _may_ want to automate this workaround further, for example via a `sys-net` systemd unit with `{Before,Wants}=network-pre.target`.  That would lessen the burden of this workaround on administrators newly installing their Workstations, at some cost:

1. to administrators, of having to do all pre-workaround setup via Ethernet, before it restores Wi-Fi connectivity; and
2. to us, of having to maintain and testing this workaround, which is only applicable on certain hardware.

The broader questions here are:
1. What kinds and sizes of workarounds are we willing to develop and maintain in order to consider a given hardware platform supported for the SecureDrop Workstation?
2. How should we distribute these workarounds, especially if they take the form of shim scripts?
    * freedomofpress/securedrop-workstation-docs#109 takes a minimalist download-and-verify approach that could be made more robust by verifying hashes we do for binary artifacts we ask administrators to install manually.

**Comment by zenmonkeykstop** [comment]
Workaround no longer required.
