### ISSUE TITLE
Clean up old-format rpc policy tests and checks

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop-workstation#818]
Did a search (https://github.com/freedomofpress/securedrop-workstation/search?q=qubes-rpc) and looks like there are potentially some places we can clean up old-format rpc policy code.

e.g. 
[securedrop-workstation/dom0/sd-clean-all.sls](https://github.com/freedomofpress/securedrop-workstation/blob/c19461996b5af7ea9c32c9e1bd01a646709b5801/dom0/sd-clean-all.sls#L79)

Open question: Can we also remove https://github.com/freedomofpress/securedrop-workstation/blob/c19461996b5af7ea9c32c9e1bd01a646709b5801/dom0/sd-clean-all.sls#L80

_See conversation thread in https://github.com/freedomofpress/securedrop-workstation/pull/814#discussion_r943055911_

**Comment by rocodes** [comment]
Will be closed by https://github.com/freedomofpress/securedrop-workstation/pull/990, removing from the board
