### ISSUE TITLE
after changing `hidserv` values, `sdw-admin --apply` does not restart `sd-whonix`'s `tor`

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-workstation#821]
After using `sdw-admin --apply` to switch to a different instance, `sd-whonix:/var/lib/tor/keys/app-journalist.auth_private` is updated with the new instance's `hidserv` values, but `sd-whonix` or its `tor` service must be manually restarted for them to take effect.

## Steps to reproduce

On an already-configured SecureDrop Workstation:

1. Change the `hidserv` values in `/usr/share/securedrop-workstation-dom0-config/config.json`.
2. Run `sdw-admin --{validate,apply}`.
3. Try to sign into the SecureDrop Client.

## Expected behavior

Sign-in succeeds against the newly-configured hidden service.

### `sd-app`

The SecureDrop Client cannot connect to the (newly-configured) hidden service until `sd-whonix` or its `tor` service are manually restarted with the new `/var/lib/tor/keys/app-journalist.auth_private`.

### `sd-proxy`

```
Aug 23 15:30:08 sd-proxy python[1054]: 2022-08-23 15:30:08,047 - securedrop_proxy.proxy:257(proxy) ERROR: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

## Comments

Like the very similar freedomofpress/securedrop-client#1431, this will probably only ever occur in development and testing environments, so I intend this ticket mostly as documentation.

**Comment by legoktm** [comment]
This was effectively fixed by 8baeafdc4b52c0658868f3721a18203154b26a86 (ignore the "temporary"), since we now shutdown sd-whonix after re-provisioning, so it picks up the new config after booting.
