### ISSUE TITLE
user ID 1000 on LUKS Export Device

### ISSUE THREAD

**Issue by illumi420** [freedomofpress/securedrop-workstation#822]
Hello, I am facing a Problem after Exporting Decrypted files on an Export USB, the files has user ID 1000 by default, and our Journalists have different User IDs which is complicating the workflow of exporting the data.

as a work around I tried to change the "facl" permissions and had to "chmod g+rw" the directory in order to have a read/write permissions on the data. The problem when a new Export folder is created it has no Group permissions so the "facl" is not working.

**Comment by rocodes** [comment]
(Closing in favour of https://github.com/freedomofpress/securedrop-export/issues/104 - thanks both for re-filing, apologies for the delay)
