### ISSUE TITLE
`LICENSE` is the AGPL, `.spec` says the project licensed with the GPL

### ISSUE THREAD

**Issue by eaon** [freedomofpress/securedrop-workstation#829]
Looks like there was an oversight: `LICENSE` is a copy of the AGPL while … [the spec implies it should be the GPL](https://github.com/freedomofpress/securedrop-workstation/blob/main/rpm-build/SPECS/securedrop-workstation-dom0-config.spec#L22).

Given that this repo does not cover any network accessible applications, I think it'd be reasonable to go with the GPL, plus other components like `securedrop-proxy` are licensed under the GPL as well.

**Comment by creviera** [comment]
commenting to get this on my radar (no time today) but would be interested to hear your feedback on https://github.com/freedomofpress/securedrop/issues/6219

**Comment by kushaldas** [comment]
When we started working on the project, there was a general agreement to keep everything under AGPL to keep things simple.

The issue with the `SPEC` file is a pure bug for sure.

**Comment by eaon** [comment]
Aye, I did not spend enough :brain: on this when I filed the issue, further discussions about license changes made it clear that we can't just switch to the GPL anyway. Update for the spec file it is! Thanks for your input and the historic perspective @kushaldas!
