### ISSUE TITLE
Selection during deletion selects the wrong message

### ISSUE THREAD

**Issue by philmcmahon** [freedomofpress/securedrop-workstation#833]
For a large inbox, deleting a source account can take a few seconds. During this time it's possible to 'select' a source from the source list - in that you get the hover over cursor/shading changes, then when you click the UI appears to show that the source has been selected. However, nothing happens - the deletion in progress message still shows.  When the source account finishes deleting, the message list is refreshed minus the old entry. At this point the UI refreshes to show the source that was selected during the deletion.

There appears to be an off by one error of some kind occuring here because if you select a source 'below' the source you are in the process of deleting, then when the source account finishes deleting you end up opening the source below the one you selected. 

Accidentally opening a message is an problem because it them marks the message as read.

**Comment by philmcmahon** [comment]
Replaced by https://github.com/freedomofpress/securedrop-client/issues/1567

**Comment by gonzalo-bulnes** [comment]
Yes, the **securedrop-client** is the best location. Thanks @philmcmahon :+1:
