### ISSUE TITLE
grsec based workstation kernels require at least 1GB of RAM

### ISSUE THREAD

**Issue by eaon** [freedomofpress/securedrop-workstation#838]
The workstation's memory footprint is pretty large, and most of that is for good reason. However, some of our VMs like `sd-gpg` and `sd-proxy` should not need more RAM than for example `sys-net` or `sys-usb`, but they are in fact configured with pretty large defaults. 

So I recently tried lowering the RAM settings for `sd-proxy` and `sd-gpg` to see what optimisation was possible, but it turns out that our grsec based kernels crash on boot when configured with anything lower than ~1GB (may be 1.2GB). Interestingly though, once booted, the kernel claimed that there were at least 800MB memory unused.

I checked if this was a HVM constraint, but as soon as I assigned a kernel provided by Qubes `sd-proxy` and `sd-gpg` booted fine. 

Low priority for now, but as we move towards making the workstation the primary way to interact with SD, it'll be worth it to look into not wasting resources to expand hardware compatibility ever so slightly.

**Comment by zenmonkeykstop** [comment]
I wonder if there's anything in the kernel config that's enforcing this or causing it as a side effect? Might be worth trying with a server grsec kernel just for funsies.

**Comment by zenmonkeykstop** [comment]
Current hardware reccos are for systems with 32GB or greater - it would be good to optimize for memory usage but not required right now.
