### ISSUE TITLE
October 2022 Linux kernel update

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-workstation#839]
We *really* need to do another Linux kernel update. Should be done in coordination with https://github.com/freedomofpress/securedrop/issues/6660.

## Checklist
* [x] Source tarball saved internally
* [x] Uploaded to apt-test.freedom.press
* [x] Tested on recommended hardware ([Instructions on testing procedure](https://developers.securedrop.org/en/latest/kernel.html))
* [ ] Uploaded to apt.freedom.press and released

**Comment by eaon** [comment]
Workstation kernel works as expected!
