### ISSUE TITLE
Switch to Fedora 37

### ISSUE THREAD

**Issue by eaon** [freedomofpress/securedrop-workstation#841]
The release of Fedora 37 is around the corner, but Fedora 36 isn't EOL yet, so we're not particularly in a rush to switch to it even if templates become available soon (https://github.com/QubesOS/qubes-issues/issues/7807). I'd even go further and argue to hold off for a couple weeks anyway as new Fedora releases are often a bit bumpier of a ride when they're fresh.

But it will have to happen so here's the issue for it :+1:

**Comment by marmarek** [comment]
FYI fedora-37 will be shipped by default with upcoming 4.1.2 point release
