### ISSUE TITLE
User must manually specify target VM for decrypted submissions

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#86]
Currently after kicking off a decrypt process, the following dialog opens:

![qubesdialog](https://user-images.githubusercontent.com/213636/39073439-a60e9f8a-44a2-11e8-8040-e37899c91dcc.jpg)

This is not documented (new in Qubes 4?). It also seems to add no value. Can we eliminate it?

**Comment by msheiny** [comment]
I confirm I am also getting this prompt on a brand-new install. To add (I'm not sure if this is "known knowledge") if I select anything besides `sd-svs` I get a pop-up with an `archive` GUI telling me the archive is corrupted.

**Comment by joshuathayer** [comment]
Interesting, that does seem like a bug. That permission should be baked in to the systemwide qrexec permissions.
