### ISSUE TITLE
Make sure `make test` expects correct kernel package depending on build flavour

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-workstation#872]
Currently `make test` in a dom0 staging setup can produce failures when the workstation [grsec kernel version on apt-test](https://apt-test.freedom.press/pool/main/l/linux-upstream/) is newer than expected.

**Comment by rocodes** [comment]
[Side note to anyone coming across this issue later and trying to troubleshoot: if you have configured a staging setup and then switch to a dev setup, you may also see kernel test failures in dom0. We don't publish nightly kernel builds so your machine may be provisioned against the newer staging kernel, and will not be downgraded when you run `make dev`].

**Comment by legoktm** [comment]
I didn't realize we were also hardcoding the kernel version in this repository as well. I think we should do the same as we did in server, in which we only assert the kernel major version is the same (e.g. 5.15) and that it's the grsec flavor.
