### ISSUE TITLE
Configure branch protection for `release/` branches

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#879]
We've got a branch protection rule for `main`, but none for release branches. To avoid accidental pushes in release branches, it would make sense to set up a `release/*`branch pattern pattern as we have for SecureDrop, with required review prior to merge.

Note that historical release branches have used varying branch name patterns; as part of this change, we could canonicalize the `release/` pattern used in the `securedrop` repo.

(Thanks to @rocodes for identifying the issue.)

**Comment by mig5** [comment]
@eloquence I've configured `release/*` branch protection on this repository to match that of securedrop's. Please double-check the settings to make sure you're OK with them, then I think this is OK to close out.

**Comment by rocodes** [comment]
@eloquence: Are you happy with the setup & can we close this? Thank you!

**Comment by eloquence** [comment]
Yep works for me if it works for y'all!
