### ISSUE TITLE
Release securedrop-workstation-dom0-config with updated pubkey

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-workstation#886]
Once https://github.com/freedomofpress/securedrop-workstation/issues/885 is complete, a release of securedrop-workstation-dom0-config should follow before the expiry deadline.

**Comment by eaon** [comment]
My guess is we probably want to cherry-pick the key change, bump version and release that?

**Comment by rocodes** [comment]
Closing in favour of #903
