### ISSUE TITLE
Release Workstation base template RPM with updated securedrop-keyring package

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-workstation#888]
Once https://github.com/freedomofpress/securedrop-workstation/issues/887 passes, the new base template should be released.

**Comment by rocodes** [comment]
# Test Plan (yum-qa)
Hardware:
Scenario: **Fresh Install** (Since we're testing the new template, ensure your machine has not had a staging/dev SDW setup on it, i.e., wipe/reinstall QubesOS).
 - Follow the fresh install instructions to download the dom0 config RPM from `yum.securedrop.org`, install it, and  configure your instance-specific details in `config.json`. In `config.json`, leave the environment as `prod.`
 - Once the rpm installs, use text editor with elevated privileges to edit the file `/srv/salt/sd-config.yml` to change the prod `dom0_yum_repo_url` from `yum.securedrop.org/workstation/dom0` to `yum-qa.securedrop.org/workstation/dom0`
 - Let 'er rip! `sdw-admin --apply`

Testing:
- [ ] Installation completes successfully
- [ ] Do not run the updater. Inspect a VM based on the qubes-template-securedrop-workstation-bullseye template (i.e. one of our `sd-` VMs) and ensure it has the updated securedrop-keyring 0.2.1 package with the updated 2024 key expiry (`apt show securedrop-keyring`)
- [ ] Basic inter-VM functionality works (logs flow from `sd-` VMs to `sd-log`, VMs start and shut down correctly, etc).

**Comment by eaon** [comment]
# Test Plan (yum-qa)
Hardware: ThinkPad X1 Carbon Gen 6
Scenario: **Fresh Install**

Testing results:
- [x] Installation completes successfully
- [x] Do not run the updater. Inspect a VM based on the qubes-template-securedrop-workstation-bullseye template (i.e. one of our `sd-` VMs) and ensure it has the updated securedrop-keyring 0.2.1 package with the updated 2024 key expiry (`apt show securedrop-keyring`)
- [x] Basic inter-VM functionality works (logs flow from `sd-` VMs to `sd-log`, VMs start and shut down correctly, etc).

Happy to report this all checks out! As far as I'm concerned, the RPM is ready for promotion to prod.
