### ISSUE TITLE
Document/implement deb testing process that uses apt-qa instead of manual downloads

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-workstation#891]
Generally the final pre-release QA step is to point a prod setup at apt-qa.freedom.press (signed by the release key) and go through some form of the test plan.

But on the workstation we don't really do this and just download the debs into VMs manually and install them. We need to document and/or implement a process that uses apt-qa for final pre-release QA.

**Comment by nathandyer** [comment]
I've started reading through our current process to try and document an updated procedure, but I'm a bit confused about how the current process differs from the ideal process described above.

In our developer documentation, I'm not seeing where we suggest manually downloading packages into a VM. If I'm reading it correctly, our current process suggests adding the apt-qa.freedom.press repo to a Template VM: https://developers.securedrop.org/en/latest/workstation_release_management.html#step-6-perform-the-apt-qa-preflight-check 

@legoktm It's probably just me not fully understanding the current situation, but can you clarify the changes we're looking to make here?

**Comment by legoktm** [comment]
I'm trying to remember which release this is about, and don't see which release lines up with May 26...

But see e.g. https://github.com/freedomofpress/securedrop-apt-prod/pull/113#issuecomment-1533906832 and https://github.com/freedomofpress/securedrop-apt-prod/pull/116#issuecomment-1579408680 where QA was just installing the package in a VM.

I think the issue is that changing the apt sources isn't as easy in Qubes?  The workflow is something like, start the correct template, edit sources.list, run `apt update && apt upgrade -y` and then restart all VMs and then start the client...?

**Comment by legoktm** [comment]
I think https://github.com/freedomofpress/securedrop-dev-docs/pull/114 is good enough to close this, if there are more workflow improvements we want/need, we can keep iterating in separate tickets.
