### ISSUE TITLE
Set up required status checks in this repo

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#900]
Branch protection for `main` is enabled, but currently we do not require any status checks to pass. I would suggest we require all of them:

- sd-ci-runner (the new SDW CI runner - this would only prevent merges into `main` if those tests fail) 
- launcher-tests (while it exists)
- lint

**Comment by legoktm** [comment]
Let's do it.

**Comment by leee** [comment]
`lint` and `launcher-tests` required, left `sd-ci-runner` out for now since it's a single worker CI at the moment.
