### ISSUE TITLE
`make clone` is currently failing in CI with error: Multiple top-level packages discovered in a flat-layout: ['dom0', 'launcher']

### ISSUE THREAD

**Issue by mig5** [freedomofpress/securedrop-workstation#905]
Whilst troubleshooting a CI issue observed in PR #904, I found that `make clone` is currently failing on dom0, against that commit (not sure if also true of `main` branch).

This is the error:

```
Jun 27 07:29:40 sd-ssh qubes.VMShell-dom0[1556]: error: Multiple top-level packages discovered in a flat-layout: ['dom0', 'launcher'].
Jun 27 07:29:40 sd-ssh qubes.VMShell-dom0[1556]: 
Jun 27 07:29:40 sd-ssh qubes.VMShell-dom0[1556]: To avoid accidental inclusion of unwanted files or directories,
Jun 27 07:29:40 sd-ssh qubes.VMShell-dom0[1556]: setuptools will not proceed with this build.
Jun 27 07:29:40 sd-ssh qubes.VMShell-dom0[1556]: 
Jun 27 07:29:40 sd-ssh qubes.VMShell-dom0[1556]: If you are trying to create a single distribution with multiple packages
Jun 27 07:29:40 sd-ssh qubes.VMShell-dom0[1556]: on purpose, you should not rely on automatic discovery.
Jun 27 07:29:40 sd-ssh qubes.VMShell-dom0[1556]: Instead, consider the following options:
Jun 27 07:29:40 sd-ssh qubes.VMShell-dom0[1556]: 
Jun 27 07:29:40 sd-ssh qubes.VMShell-dom0[1556]: 1. set up custom discovery (`find` directive with `include` or `exclude`)
Jun 27 07:29:40 sd-ssh qubes.VMShell-dom0[1556]: 2. use a `src-layout`
Jun 27 07:29:40 sd-ssh qubes.VMShell-dom0[1556]: 3. explicitly set `py_modules` or `packages` with a list of names
Jun 27 07:29:40 sd-ssh qubes.VMShell-dom0[1556]: 
Jun 27 07:29:40 sd-ssh qubes.VMShell-dom0[1556]: To find more information, look for "package discovery" on setuptools docs.
Jun 27 07:29:40 sd-ssh qubes.VMShell-dom0[1556]: make: *** [Makefile:26: dom0-rpm] Error 1
```

I'm not sure what it's about, or if it is CI specific (if it is, I'll move the issue there!). We have slightly complicated the current CI state in that Maeve and I both recently reinstalled our respective CI platforms to test out a more streamlined set of installation steps, and not sure if that's played a part or if just coincidence.

Does anyone reproduce? Anyone seen it before?

**Comment by eaon** [comment]
My assumption is that this is because current CI has been modified to handle the new file locations/podman based building, whereas the 0.8.x releases are in the old style of doing things (#904 is the last release)

If the the only branches this affects are 0.8.x based, I think that can be ignored.

**Comment by legoktm** [comment]
> So, I think it still means that make clone is broken on 0.8.x either way? But if that's not such a big concern given its lifecycle, no problem :)

Yeah, it's broken on F37+ because of setuptools changes. But main now builds inside a F32 container so it's isolated from underlying host VM changes/upgrades. So going forwards this hopefully won't be an issue :)
