### ISSUE TITLE
September 2023 Linux kernel update

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-workstation#916]
Being done in coordination with freedomofpress/securedrop#6938.

## Checklist
* [x] Source tarball saved internally ([instructions](https://wiki.freedom.press/wiki/Responding_to_source_requests_for_SecureDrop_kernels#How_to_respond_to_a_source_request_for_SecureDrop_kernels))
* [x] Logs and build info uploaded to `build-logs`
* [x] Uploaded to `apt-test.freedom.press`
    * freedomofpress/securedrop-apt-test#203
* [x] Tested in our template ([instructions](https://developers.securedrop.org/en/latest/kernel.html)): @rocodes or @cfm 
* [ ] Uploaded to `apt.freedom.press` and released
    * freedomofpress/securedrop-apt-prod#121

## Test plan

- [ ] Per <https://github.com/freedomofpress/securedrop/issues/6762#issuecomment-1520569189>:

    > Build next next ~(June)~ kernel using the new version format, drop the manual dependency on 5.15.89. unattended-upgrades will automatically keep 3 kernel packages around, so the ~May~ August kernel should not be removed.

**Comment by cfm** [comment]
This is blocked on <https://github.com/freedomofpress/securedrop-apt-test/pull/202#issuecomment-1709117337>, which will be resolved with new packages tomorrow.

**Comment by cfm** [comment]
Unblocked by freedomofpress/securedrop-apt-test#203.  We're hoping to complete testing in time to promote to `securedrop-apt-prod` on Monday.

**Comment by cfm** [comment]
Thanks, @ro.  Per <https://github.com/freedomofpress/securedrop/issues/6938#issuecomment-1716625204>, do you get the same results (with the same `meltdown.sh`) on the previous kernel?

**Comment by rocodes** [comment]
Yes - on the 5.15.123-1 grsec workstation kernel I get the same result for the SRBDS.
