### ISSUE TITLE
Release securedrop-workstation-dom0-config 0.9.0

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-workstation#920]
This is a tracking issue for the release of securedrop-workstation-dom0-config-0.9.0. 

## Roles:
- RM: @zenmonkeykstop 
- Deputy RM: TK
- Comms: TK
- QA: @eloquence @legoktm @rocodes 

### RC1:
- [x] [In release branch] bump rc version using `update_version` script, update changelog in rpm .spec file
- [x] [In release branch] create rc tag 
- [x] [In release branch] build rc, commit build logs, and publish artifact to yum-test

### RC2:
- [x] [In release branch] bump rc version using `update_version` script, update changelog in rpm .spec file
- [x] [In release branch] create rc tag 
- [x] [In release branch] build rc, commit build logs, and publish artifact to yum-test

### Fresh install (prodlike install)
Qubes 4.1.2 expected, please note hardware
#### Prep:
- Ensure fedora 38 templates are _not_ installed on this machine. (Ideally, have never been installed). Note fedora-37 based sys-net, sys-usb, and default management dvm. 
- Ensure clean install state (SDW is not installed and sdw remants are not there; ideally, start from a fresh Qubes install). 
- Download the RPM from https://yum-test.securedrop.org/ [[link here](https://yum-test.securedrop.org/workstation/dom0/f32/securedrop-workstation-dom0-config-0.9.0-0.rc1.1.fc32.noarch.rpm)]. It should be signed with the SD Test Key. Ensure you have the test key imported to whatever your download environment was (via `rpm --import /path/to/key.asc`) and then verify the rpm signature using `rpm -Kv path-to-0.9.0-rc1.rpm`.
- Copy the RPM in dom0 [per our setup instructions, then install it](https://workstation.securedrop.org/en/stable/admin/install.html#download-and-install-securedrop-workstation).
#### Testing:
- [ ] RPM installs successfully in dom0
- [ ] Put your config info into `config.json` and run `sdw-admin --apply`. Verify apply run completes successfully.
- [ ] Fedora-38 template is downloaded during apply run
- [ ] Shut down and reboot if prompted. Restart all running VMs otherwise.
##### Option A: 
- [ ] `sys-net` and `sys-usb` use `fedora-38-dvm` and `sd-fedora-38-dvm` templates, respectively
- [ ] `sys-usb` contains sdw udev rules file `/etc/udev/rules.d/99-sd-devices.rules`
- [ ] `qvm-prefs default-mgmt-dvm template` in dom0 returns `fedora-38`
##### Option B:
- [ ] Check out the release tag in your dev vm, then clone an updated version of the sdw repo to dom0 using `qvm-run --pass-io` (no need to `make clone` since that also installs a dev rpm). Then run `make test`. Ensure dom0 tests pass. Note any test failures in this ticket. 
 
### Upgrade from 0.8.1 (no f38 templates preinstalled)
Qubes 4.1.2 expected, please note hardware
#### Testing: 
Run the SDW updater. This is also a great time to grab a coffee, since the updater run will take a while.
- [ ] dom0 rc1 package is installed successfully.
- [ ] f38 template is downloaded during updater run, and all salt states are run during updater run
- [ ] Test plan (either option A or B, as seen above) completes successfully

### Upgrade from 0.8.1 (f38 templates are preinstalled)
(Already completed: https://github.com/freedomofpress/securedrop-workstation/issues/920#issuecomment-1826112720)
- [x] dom0 package installs correctly and `sdw-admin --apply` is successful (or updater completes successfully, if using SDW updater)
- [x] Test plan (option A, as above) completes successfully   

### Release:
- [x] [In release branch] Bump version via `update_version` script, and update [changelog in rpm .spec file](https://github.com/freedomofpress/securedrop-workstation/blob/main/rpm-build/SPECS/securedrop-workstation-dom0-config.spec)
- [x] [In release branch]  Create prod tag (signed by release signing key)
- [x] Build prod artifact, sign with release key, commit build logs
- [x] QA/smoketest of prod artifact (stuff rpm in dom0 of SDW prod machine)
- [x] Publish prod artifact to yum repo

### Post-release
- [ ] Backport version and changelog updates to main branch from release branch
- [ ] freedomofpress/securedrop-dev-docs#113
- [ ] Retro if/as needed

**Comment by rocodes** [comment]
# rc1 results (existing install, f38 template was already downloaded)
- [x] successfully updated to 0.9.0-rc1
- [x] `sdw-admin --apply` completes successfully (f38 template was already downloaded)
- [x] sys-usb uses sd-fedora-38-dvm appvm template and udev rules are in place. sys-firewall uses fedora-38-dvm template.  
Note: the `top_file_merging_strategy` warning message appears in the console after sdw-admin apply (https://github.com/freedomofpress/securedrop-workstation/issues/868), which we should briefly investigate (but ultimately probably address with changes to our layout/provisioning)

**Comment by zenmonkeykstop** [comment]
Release docs notes here so I don't forget them:
- docs describe final prod release process only. General release flow should go like:
  - cut a release/U.V.W branch
  - while release not passed QA, create an rc by:
    - running update_version.sh U.V.W-rcN
    - manually updating the changelog in the spec file (under rpm-build/SPECS)
    - manually cutting a U.V.W-rcN tag (sign with personal key if preferred but commit should definitely be signed)
    - PR into release/U.V.W branch for N>1 (otherwise it's just the first push of release/U.V.W)
    - build from this tag in a clean environment and PR rpm into yum-test repo, commit logs to build-logs repo
    - once yum-test PR is merged, have folks perform QA
  - once QA passed, go through prod release process (which *will* require a tag signed with release key).

**Comment by eloquence** [comment]
Poking at RC1 fresh install scenario on a T480 (from a 4.1.2 ISO).

**Comment by zenmonkeykstop** [comment]
> Poking at RC1 fresh install scenario on a T480 (from a 4.1.2 ISO).

If you wanna hold off for a few we can get an RC2 built clean in there.

**Comment by eloquence** [comment]
Cool, will take a while to get fresh 4.1.2 env up anyway :)

**Comment by cfm** [comment]
@zenmonkeykstop, my T14 is on Qubes 4.1 *without* Fedora 38 installed, so feel free to assign me to cover (or back up someone else on) that case.

**Comment by legoktm** [comment]
### Upgrade from 0.8.1 (no f38 templates preinstalled)
Qubes 4.1.2, with a T490 
#### Testing: 
Ran the SDW updater
- [x] dom0 rc2 package is installed successfully.
- [x] f38 template is downloaded during updater run, and all salt states are run during updater run
- [x] Test plan (either option A or B, as seen above) completes successfully
##### Option A: 
- [x] `sys-net` and `sys-usb` use `fedora-38-dvm` and `sd-fedora-38-dvm` templates, respectively
- [x] `sys-usb` contains sdw udev rules file `/etc/udev/rules.d/99-sd-devices.rules`
- [x] `qvm-prefs default-mgmt-dvm template` in dom0 returns `fedora-38`

**Comment by rocodes** [comment]
## Unofficial upgrade from rc1 (f38 templates preinstalled)
Qubes 4.1.2 / t490 
Upgraded via GUI updater, then ran `sdw-admin --apply`.  For bonus points I also changed the sys-usb template to another template before running apply, but this is mostly a smoketest/sanity test since rc1 already installed successfully

Option A:
- [x]  sys-net, sys-usb use fedora-38-dvm and sd-fedora-38-dvm
- [x] sys-usb contains udev rules
- [x] fedora-38 is default mgmt dvm template

**Comment by eloquence** [comment]
## Fresh install of 0.9.0 on stock 4.1.2 system

Hardware: T480

- [x] Ensure fedora 38 templates are _not_ installed on this machine. (Ideally, have never been installed). Note fedora-37 based sys-net, sys-usb, and default management dvm. 
- [x] Ensure clean install state (fresh install from 4.1.2 ISO)
- [x]  Download the RPM from https://yum-test.securedrop.org/ [[link here](https://yum-test.securedrop.org/workstation/dom0/f32/securedrop-workstation-dom0-config-0.9.0-0.rc1.1.fc32.noarch.rpm)]. It should be signed with the SD Test Key. Ensure you have the test key imported to whatever your download environment was (via `rpm --import /path/to/key.asc`) and then verify the rpm signature using `rpm -Kv path-to-0.9.0-rc1.rpm`.
- [x] Copy the RPM in dom0 [per our setup instructions, then install it](https://workstation.securedrop.org/en/stable/admin/install.html#download-and-install-securedrop-workstation).
#### Testing:
- [x] RPM installs successfully in dom0
- [x] Put your config info into `config.json` and run `sdw-admin --apply`. Verify apply run completes successfully.
- [x] Fedora-38 template is downloaded during apply run
- [ ] Shut down and reboot if prompted. Restart all running VMs otherwise.
- [x] `sys-net` and `sys-usb` use `fedora-38-dvm` and `sd-fedora-38-dvm` templates, respectively
- [x] `sys-usb` contains sdw udev rules file `/etc/udev/rules.d/99-sd-devices.rules`
- [x] `qvm-prefs default-mgmt-dvm template` in dom0 returns `fedora-38`


However, `sdw-admin --apply` failed with this error:

```
  Summary for sd-gpg
  ------------
  Succeeded: 6 (changed=6)
  Failed:    0
  ------------
  Total states run:     6
  Total run time:   1.500 s
sd-viewer:
  [ERROR   ] An un-handled exception was caught by Salt's global exception handler:
  TypeError: '>' not supported between instances of 'NoneType' and 'int'
  Traceback (most recent call last):
    File "/usr/bin/salt-ssh", line 8, in <module>
      sys.exit(salt_ssh())
               ^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/salt/scripts.py", line 470, in salt_ssh
      client.run()
    File "/usr/lib/python3.11/site-packages/salt/cli/ssh.py", line 20, in run
      ssh.run()
    File "/usr/lib/python3.11/site-packages/salt/client/ssh/__init__.py", line 819, in run
      final_exit = max(final_exit, retcode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: '>' not supported between instances of 'NoneType' and 'int'
  Traceback (most recent call last):
    File "/usr/bin/salt-ssh", line 8, in <module>
      sys.exit(salt_ssh())
               ^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/salt/scripts.py", line 470, in salt_ssh
      client.run()
    File "/usr/lib/python3.11/site-packages/salt/cli/ssh.py", line 20, in run
      ssh.run()
    File "/usr/lib/python3.11/site-packages/salt/client/ssh/__init__.py", line 819, in run
      final_exit = max(final_exit, retcode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

That appears to be https://github.com/saltstack/salt/issues/64575. Re-running.

**Comment by eloquence** [comment]
Second run completed without errors. Salt issue appears to be a regression in Salt, see #927.

Stepped through some smoke tests (login, sync, open files, export) and all looks good there as well. :)

**Comment by rocodes** [comment]
(Thanks as always @eloquence for your diligent testing <3)
