### ISSUE TITLE
Installation can fail with `TypeError: '>' not supported between instances of 'NoneType' and 'int'`

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#927]
STR:
- Install SecureDrop Workstation on Qubes 4.1.2 (fresh install)
- Salt package in `dom0` is at version `3001.7`

Expected behavior:
- `sdw-admin --apply` runs without errors

Actual behavior:
- `sdw-admin --apply` may fail with Salt error:

```
sd-viewer:
  [ERROR   ] An un-handled exception was caught by Salt's global exception handler:
  TypeError: '>' not supported between instances of 'NoneType' and 'int'
  Traceback (most recent call last):
    File "/usr/bin/salt-ssh", line 8, in <module>
      sys.exit(salt_ssh())
               ^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/salt/scripts.py", line 470, in salt_ssh
      client.run()
    File "/usr/lib/python3.11/site-packages/salt/cli/ssh.py", line 20, in run
      ssh.run()
    File "/usr/lib/python3.11/site-packages/salt/client/ssh/__init__.py", line 819, in run
      final_exit = max(final_exit, retcode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: '>' not supported between instances of 'NoneType' and 'int'
  Traceback (most recent call last):
    File "/usr/bin/salt-ssh", line 8, in <module>
      sys.exit(salt_ssh())
               ^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/salt/scripts.py", line 470, in salt_ssh
      client.run()
    File "/usr/lib/python3.11/site-packages/salt/cli/ssh.py", line 20, in run
      ssh.run()
    File "/usr/lib/python3.11/site-packages/salt/client/ssh/__init__.py", line 819, in run
      final_exit = max(final_exit, retcode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by eloquence** [comment]
@marmarek FYI, just saw this on 4.1.2 with fresh provisioning of the SecureDrop Workstation - flagging because you opened the upstream issue https://github.com/saltstack/salt/issues/64575. The provisioning process itself installs fedora-38; I'm not entirely sure what Salt version was in play during this particular step.

**Comment by marmarek** [comment]
What is the template of default-mgmt-dvm? Also fedora-38? Which version of `salt-ssh` package do you have there?

**Comment by eloquence** [comment]
It's `fedora-38`. The provisioning installs `fedora-38` and configures it as the default. Since that happened successfully as part of the provisioning run that failed with this error, I suspect the failed operation was done via `fedora-38` and not `fedora-37`.

The `salt-ssh` version on this fresh install is `3006.4` in `fedora-38`, and `3006.2` in `fedora-37`.

**Comment by marmarek** [comment]
Oh, the [fix](https://github.com/saltstack/salt/pull/64576) got merged upstream just 15h ago. But in the meantime 3006.4 (newer than the version with the fix in our repositories) was released. I'll update our package with a temporary backport one last time...
