### ISSUE TITLE
Create shared library for generic code

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-workstation#93]
To reduce duplication of code, we should factor generic functions that many SecureDrop VMs need into a shared library (suggested by @joshuathayer [here](https://github.com/freedomofpress/securedrop-workstation/blob/master/sd-svs/accept-sd-xfer-extracted#L10)). A minimal approach would be a single Python file that we drop into all SecureDrop VMs via Salt.

**Comment by eloquence** [comment]
Per discussion with @redshiftzero, removing this from the must-do alpha requirements. Recent code deletions have already reduced the level of duplication significantly. We can reconsider additional refactor/cleanup post-alpha.

**Comment by redshiftzero** [comment]
I don't think we have a need for this anymore
