### ISSUE TITLE
Deal with Whonix 16 EOL

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-workstation#934]
It's on Jan 18, 2024. See <https://www.qubes-os.org/news/2023/12/22/whonix-16-approaching-eol/>.

**Comment by adrelanos** [comment]
More of a porting to Qubes R4.2 issue (https://github.com/freedomofpress/securedrop-workstation/issues/863) than Whonix issue?

Would it help if Whonix 17 was supported on Qubes R4.1?

**Comment by zenmonkeykstop** [comment]
Hey @adrelanos, that would be great if possible. There's still a bit of work to do on updating SDW for 4.2, so there will be users on 4.1 for the next few months until Qubes 4.1 hits its EOL.

**Comment by adrelanos** [comment]
Discussed with @marmarek. Let's see what can be done.

**Comment by adrelanos** [comment]
Just a just a short status update.

Marek doing builds apparently. (https://github.com/QubesOS/updates-status/issues/566#issuecomment-1889747530) I'll see what I can do if something is needed from my side.

This is not an announcement / call for testers / etc.

**Comment by eloquence** [comment]
Thanks a lot @adrelanos (and @marmarek). Since we'll likely go a little bit past the EOL date here - will users receive see any warning screens about the end-of-life e.g. when booting up the VM or making a Tor connection?

**Comment by adrelanos** [comment]
There's a `one-time-popup` script. [1] It's supposed to be shown at boot time.

Package `legacy-dist` [2] ships:

* `/usr/libexec/legacy-dist/deprecation-popup`
* `/etc/xdg/autostart/legacy-dist-deprecation-notice.desktop`

So yeah, actually the plan was as usual to show a one time deprecation popup. One time means there is a "don't show this again" check box which if checked will result in not showing that notice again.

If you want to nuke it then  `rm -f /etc/xdg/autostart/legacy-dist-deprecation-notice.desktop` should be sufficient. For the future, if a better mechanism to control that is desired, I could invent something else. (Status file to disable or settings drop-in folder.)

----

[1] In Whonix 17 it's in `/usr/libexec/msgcollector/one-time-popup`. Part of `msgcollector` repository. Might be in a different location in Whonix 16 but can be easily found if needed.

[2] Paths could be slightly different in Whonix 16.
