### ISSUE TITLE
 Support Fedora-39 (must do by 2024-05-14)

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/securedrop-workstation#975]
Fedora 39 templates are available: https://www.qubes-os.org/news/2024/02/13/fedora-39-templates-available-fedora-38-approaching-eol/. Following the issue structure of [the previous version bump](https://github.com/freedomofpress/securedrop-workstation/issues/892):

- [ ] Bump supported_fedora_version to fedora-39 and convert system-wide default dispvm to fedora-39-dvm
- [ ] Create sd-fedora-39-dvm with USB autoattach rules and use as template for sys-usb (unless we decide to revisit this behaviour)
- [ ] Update docs, including developers.securedrop.org (multi-machine setup on Qubes) docs and workstation.securedrop.org, to include correct fedora version

Related:
  - https://github.com/freedomofpress/securedrop-workstation/issues/882

**Comment by zenmonkeykstop** [comment]
I don't recall one - I think the big issue for me with that would be deviation from stock Qubes.

**Comment by zenmonkeykstop** [comment]
In terms of the f39 update, it's pretty straightforward and I'd be inclined to do a 4.1 point release to cover it (with absolutely nothing else in scope, branching off the last release). We don't have to worry about it for 4.2 as the 4.2.1 ISO is already on f39.

**Comment by legoktm** [comment]
> The cadence of Fedora release makes this a twice-a-year effort. Has there been discussion on having having debian templates as default for sys-*?

Do you want to file a separate discussion issue for this? I like the idea, I just assumed that sticking with stock Qubes setup of Fedora for sys-* was preferred.

**Comment by legoktm** [comment]
Completed in https://github.com/freedomofpress/securedrop-workstation/issues/999.
