### ISSUE TITLE
[4.2] sd-proxy connectivity issues

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-workstation#978]
* [x] I have searched for duplicates or related issues

## Description

On freshly-provisioned 4.2 system (dev), sd-proxy lacks network connectivity.

## Steps to Reproduce

Provision 4.2 system using tip of deb12-compat branch (yesterday) or tip of main (today) and attempt to log in.

## Expected Behavior

sd-proxy has network connectivity, client can log in.

## Actual Behavior

Observe immediate failure to authenticate, and logs in `sd-proxy` noting `HTTPConnectionPoolError` complaining about dns failure, which is actually a signal that sd-proxy does not have connectivity (test by attempting to ping, running apt update, etc - network is unreachable). 

## Comments

n/a

**Comment by zenmonkeykstop** [comment]
D'oh, this is a mimimal template casualty I think - it needs `qubes-core-agent-networking`

**Comment by rocodes** [comment]
Confirmed, that resolves the issue. thanks for speedy diagnosis.

**Comment by rocodes** [comment]
Er, a further update: `qubes-core-agent-networking` does allow for login/authentication and sync, but I'm out of the woods yet. I see message download failures in the client logs (`on_reply_download_failure` reporting that `on_reply_download_failed` could not be emitted), and in the proxy, an error (`Connection aborted`, `RemoteDisconnected`: `remote end closed connection without reponse`). This isn't a very client-sounding error message, but my server is up and online, accepts submissions, and new submissions are being sent to the client (so a submission from a new codename shows up in the client upon next sync, it's just messages /replies that aren't available). Curious if others can repro this or not.
