### ISSUE TITLE
Base on debian-12 (GNOME) templates for now

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-workstation#980]
* [x] I have searched for duplicates or related issues

## Description

I was trying to look into https://github.com/freedomofpress/securedrop-workstation/issues/978 and then realized there was no `curl` installed in the template. Given how much else is changing right now, I think we should use the GNOME `debian-12` templates as a base, and switch to minimal at some other point so we're not also fighting minimalness while trying to do other things.

**Comment by zenmonkeykstop** [comment]
Installing `curl` or other troubleshooting-motivated packages in the large/small template and kicking the affected VM is also an option. IMO, if we move back to a full template we'll just need to do the move and test against minimal again later. I'd rather discover and deal with breakage now.

**Comment by legoktm** [comment]
I think it's just additional cognitive load and breakage that, IMO, we could do without. Using the GNOME templates is sticking with the status quo, using minimal templates (which I would like to eventually move to as well!!) is a deviation and not really crucial to the 1.0 roadmap.

**Comment by zenmonkeykstop** [comment]
Looking at the diff in packages for the 4.1 base template vs. 4.2, there is a lot of missing Qubes-specific functionality, all of which could be pulled in via `qubes-vm-recommmended` - so one compromise here could be to:
- keep using debian-12-minimal, cloning it and installing just enough to support installing the grsec kernel
- add `qubes-vm-recommended` to the cloned base before cloning small and large
- drop the cloned base once the second cloning operation is complete.

**Comment by legoktm** [comment]
Installing `qubes-vm-recommended` is roughly the definition of the standard templates, so that's fine with me as a compromise. I can't tell from https://github.com/QubesOS/qubes-meta-packages/blob/4eff43a6dad8c051c3740bb4956a57b5a32c8f2d/debian/control#L31 whether it's going to pull in GNOME or XFCE though. 

> If we have appetite for further attack surface reductions, the packages introduced by qubes-vm-recommends would then be the rational place to start - for example, we don't need networking support anywhere but sd-proxy, and can probably drop passwordless root elsewhere too.

I think it would be good to have a dedicated ticket for this (once we un-minimize the template) so we can discuss/prioritize accordingly. I don't agree with removing networking support, but would want to remove passwordless root.

**Comment by zenmonkeykstop** [comment]
Probably gonna pull in base xfce stuff via xfce4-notifyd and base gnome via qubes-core-agent-nautilus. But not everything currently in debian-12-xfce at least which also includes a bunch of application packages.

If we do get back to minification at some point, we could probably swap nautilus out for thunar and save some weight that way - but that would be a reasonably significant UX change, I doubt they're perfectly equivalent.
