### ISSUE TITLE
`make build-rpm` fails on first run with failure to resolve registry.fedoraproject.org

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-workstation#989]
On a an debian-12-xfce AppVM on Qubes 4.2, running `make build-rpm` either directly or via `make clone` in dom0 sometimes fails on the first attempt with a failure to lookup registry.fedoraproject.org. It usually succeeds immediately after.

This is just annoying in development, but causes the occasional failure in CI, so worth looking into at some stage.

**Comment by legoktm** [comment]
If this happens more frequently we can have CI attempt the `make clone` step twice pretty trivially.

**Comment by zenmonkeykstop** [comment]
No CI failures so this is most likely dev machine specific. Closing.
