### ISSUE TITLE
Enable securedrop server dev environment on Qubes

### ISSUE THREAD

**Issue by joshuathayer** [freedomofpress/securedrop-workstation#99]
As we move towards building a client application, it's likely that we're going to be doing parallel development of the server (to extend and debug the API) and the new the client. We've made real progress on hosting the staging environment on Qubes, but in order to facilitate SD server development we'll want to be able to host the development environment as well.

So: determine the best process for hosting the dev environment, and write documentation and make any changes to the repo which enables it.

**Comment by eloquence** [comment]
We've had these docs for a while now, so closing this issue:
https://docs.securedrop.org/en/stable/development/setup_development.html#qubes
