### ISSUE TITLE
Release securedrop-workstation-dom0-config 0.11.0

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-workstation#999]
- RM: @zenmonkeykstop 
- Deputy RM: TK
- Comms: TK
- QA: TK

This release targets Qubes 4.1 and increments the fedora version from -38 to -39, mirroring previous bumps almost identically. It is numbered as 0.11.0 for consistency, but is treated as a hotfix release in that it  is based on release/0.10.0, not main, as main is now 4.2-only.

For initial QA, the 0.11.0 rpm can be built locally from the `release/0.11.0` branch and applied via dnf as described in the test plan. For preflight testing, it should be installed via yum-qa.securedrop.org.

### Release:
- [x] [In release branch] Bump version via `update_version` script, and update [changelog in rpm .spec file](https://github.com/freedomofpress/securedrop-workstation/blob/main/rpm-build/SPECS/securedrop-workstation-dom0-config.spec)
- [x] [In release branch]  Create prod tag (signed by release signing key)
- [x] Build prod artifact, sign with release key, commit build logs
- [x] QA/smoketest of prod artifact (stuff rpm in dom0 of SDW prod machine)
- [x] Publish prod artifact to yum repo

### Post-release
- [ ] freedomofpress/securedrop-dev-docs#113
- [ ] Retro if/as needed
- [ ] Update documentation: https://github.com/freedomofpress/securedrop-workstation-docs/issues/200

### Fresh install (prodlike install)
Qubes 4.1.2 expected, please note hardware
#### Testing:
- [x] RPM installs successfully in dom0
- [x] with config in place, `sdw-admin --apply` completes successfully
- [x] fedora-39 wis installed as part of `--apply` run
- [x] sys-* AppVMs use fedora-39 versions of their expected templates
- [x] basic client functionality requiring network access (login, first sync) completed successfully.
- [x] basic client functionality requiring USB support (export, print) completed successfully
 
### Upgrade from 0.10.0 (no fedora-39 templates preinstalled)
Qubes 4.1.2 expected, please note hardware
#### Testing: 
- [ ] RPM installs succesfully via `sudo dnf install <name>` in dom0, replacing the existing 0.10.0 rpm
- [ ] with config in place, `sdw-admin --apply` completes successfully
- [ ] fedora-39 wis installed as part of `--apply` run
- [ ] sys-* AppVMs use fedora-39 versions of their expected templates
- [ ] basic client functionality requiring network access (login, first sync) completed successfully.
- [ ] basic client functionality requiring USB support (export, print) completed successfully

### [@cfm] Upgrade from 0.10.0 (with fedora-39 templates preinstalled)
Qubes 4.1.2 expected, please note hardware
#### Testing: 
- [ ] RPM installs succesfully via `sudo dnf install <name>` in dom0, replacing the existing 0.10.0 rpm
- [ ] with config in place, `sdw-admin --apply` completes successfully
- [ ] fedora-39 wis installed as part of `--apply` run
- [ ] sys-* AppVMs use fedora-39 versions of their expected templates
- [ ] basic client functionality requiring network access (login, first sync) completed successfully.
- [ ] basic client functionality requiring USB support (export, print) completed successfully

**Comment by cfm** [comment]
## Upgrade from 0.10.0 (no `fedora-39` templates preinstalled)
**Qubes 4.1.2 expected, please note hardware:**  ThinkPad X1 Carbon

- [x] RPM installs succesfully via `sudo dnf install <name>` in dom0, replacing the existing 0.10.0 rpm
- [ ] with config in place, `sdw-admin --apply` completes successfully

**No; `sys-usb` fails boot on `fedora-39`.**  Investigating....

- [x] `fedora-39` is installed as part of `--apply` run
- [x] `sys-*` AppVMs use fedora-39 versions of their expected templates
- [ ] basic client functionality requiring network access (login, first sync) completed successfully.
- [ ] basic client functionality requiring USB support (export, print) completed successfully

**Comment by zenmonkeykstop** [comment]
Checked to be sure - can't repro on a 6th-gen X1 Carbon. sys-usb is using sd-fedora-39-dvm and is booting and functional.

**Comment by cfm** [comment]
I've finished my testing in <https://github.com/freedomofpress/securedrop-workstation/issues/999#issuecomment-2078117446> and narrowed it down to `sys-usb` in HVM mode (which doesn't work) versus PV mode (which does).  Everything else works as expected.

If we don't see this again in further testing, then either:
1. I should prepare and run another upgrade scenario from v0.10 (quite time-expensive if I'm going to reset my main machine); or
2. we should accept this change of mode as the workaround we'll recommend if anyone encounters it in production.

**Comment by zenmonkeykstop** [comment]
Does the fedora-39 template in *general* fail for you in HVM mode?

**Comment by cfm** [comment]
In my latest testing `sys-usb` boots fine in HVM mode from both `fedora-39-dvm` and `sd-fedora-39-dvm`.  I can't account for the initial failure without retesting on a fresh installation of Qubes 4.1.  Let me know if you think that's worthwhile.

**Comment by zenmonkeykstop** [comment]
## Preflight test:
- hardware: 6th-gen X1 Carbon
- Qubes version: 4.1.2

### Prep:
- installed RPM as per workstation.securedrop.org docs
- before running sdw-admin --apply, updated `dom0_yum_repo_url` value to https://yum-qa.securedrop.org/workstation/dom0` in dom0:/srv/salt/sd-default-config.yml

### Testing:
- [x] RPM installs successfully in dom0
- [x] with config in place, `sdw-admin --apply` completes successfully
- [x] fedora-39 wis installed as part of `--apply` run
- [x] sys-* AppVMs use fedora-39 versions of their expected templates
- [x] basic client functionality requiring network access (login, first sync) completed successfully.
- [x] basic client functionality requiring USB support (export, print) completed successfully **print not tested**

**Comment by cfm** [comment]
## Upgrade from v0.10.0 (with `fedora-39` templates preinstalled)
**Qubes 4.1.2 expected, please note hardware:**  ThinkPad T14

- [x] RPM installs succesfully via `sudo dnf install <name>` in dom0, replacing the existing 0.10.0 rpm
- [x] with config in place, `sdw-admin --apply` completes successfully
- ~~`fedora-39` is installed as part of `--apply` run~~
- [x] `sys-*` AppVMs use `fedora-39` versions of their expected templates
- [x] basic client functionality requiring network access (login, first sync) completed successfully.
- [x] basic client functionality requiring USB support (export, print) completed successfully

**Comment by legoktm** [comment]
This was released in https://github.com/freedomofpress/securedrop-yum-prod/pull/52 - see also https://securedrop.org/news/securedrop_workstation_0_11_0_released/
